# ========== 市级核心场馆 ==========
SZLIB_URL = "https://www.szlib.org.cn/m/activity/lecture.html"
SZ_CHILDREN_LIB_URL = "https://www.szclib.org.cn"
SZBWG_URL = "https://www.shenzhenmuseum.com"
SZSTM_URL = "https://www.szstm.org.cn"
SZCP_URL = "http://www.szcp.com"
SZAAC_URL = "https://www.szaac.com"
SZNM_URL = "https://www.sznm.org.cn"
SZBO_URL = "http://www.szbo.com.cn"
SZCONCERT_URL = "https://www.shenzhenconcerthall.com"
SZMOCAP_URL = "https://www.szmocap.org"
SZSPORTS_URL = "https://www.szsportscenter.com"
SZMASSART_URL = "https://www.szmassart.com"

# ========== 区级图书馆 ==========
NSLIB_URL = "https://activity.nslib.cn"
BALIB_URL = "https://www.balib.cn/"
FTLIB_URL = "https://www.ftlib.org.cn"
LHLIB_URL = "https://szlhlib.org.cn"
LGLIB_URL = "https://www.szlglib.cn"
LHXQLIB_URL = "https://www.szlhlib.com.cn"
GMLIB_URL = "https://www.szgmlib.com.cn"
PSLIB_URL = "https://www.szpslib.cn"
YTLIB_URL = "https://www.ytlib.cn"
DPLIB_URL = "https://www.dplib.org.cn"

# ========== 区级博物馆与科普馆 ==========
NSMUSEUM_URL = "https://www.nanshanmuseum.com"
LGMUSEUM_URL = "https://www.lgmuseum.cn"
BAMUSEUM_URL = "https://www.baoan.gov.cn"
LHMUSEUM_URL = "https://www.szlh.gov.cn"
LHMUSEUM2_URL = "https://www.sz.gov.cn"
DPGEOPARK_URL = "https://www.dapeng.gov.cn"
BAOAN_KJG_URL = "https://www.baoan.gov.cn"
LGKJG_URL = "https://www.lg.gov.cn"
LHKJG_URL = "https://www.szlh.gov.cn"
YTKJG_URL = "https://www.yantian.gov.cn"
GM_KJG_URL = "https://www.szstm.org.cn"

# ========== 青少年宫/少儿活动中心 ==========
BAOAN_QSNG_URL = "https://www.baoan.gov.cn"
NSQSNG_URL = "https://www.szns.gov.cn"
LGQSNG_URL = "https://www.lg.gov.cn"
LHQSNG_URL = "https://www.szlh.gov.cn"
LHQSNG2_URL = "https://szlhlib.org.cn"
GMQSNG_URL = "https://www.szgmlib.com.cn"
PSQSNG_URL = "https://www.szpslib.cn"

# ========== 区级体育中心 ==========
BAOAN_TY_URL = "http://www.baoan.gov.cn/bawtlyj/"
NSWTZX_URL = "https://www.szns.gov.cn"
SZWTY_URL = "https://www.szns.gov.cn"
LHTYZX_URL = "https://www.lg.gov.cn"
LHWTX_URL = "https://www.szlh.gov.cn"
GMTYZX_URL = "https://www.szgmlib.com.cn"
LHTYZX2_URL = "https://szlhlib.org.cn"
PSTYZX_URL = "https://www.szpslib.cn"
YTTYZX_URL = "https://www.yantian.gov.cn"

# ========== 其他公立场馆 ==========
NSWHG_URL = "https://whgy.szmassart.com/nsqwhg/web/activity/list.html"
BAOAN_1990_URL = "https://www.baoan.gov.cn"
BAYAREA_EYE_URL = "https://www.baoan.gov.cn"
BAOAN_GUIHUA_URL = "https://www.baoan.gov.cn"
LGGUIHUA_URL = "https://www.lg.gov.cn"
NSGUIHUA_URL = "https://www.szns.gov.cn"
LH_PRINTMAKING_URL = "https://www.szlh.gov.cn"
NSAQJY_URL = "https://www.szns.gov.cn"
SKHYKPG_URL = "https://www.szns.gov.cn"

# ========== 旧字段兼容 ==========
SZCEC_URL = "https://www.szcec.com/szcec/cn-schedule/review-2025/index.html"
SHENZHEN_WORLD_URL = "https://www.shenzhen-world.com/scheduling/index.html"
OCT_WETLAND_URL = "https://www.szns.gov.cn"
LG_HAKKA_URL = "https://www.lg.gov.cn"
LH_ECOLOGY_URL = "https://www.szlh.gov.cn"
LH_PALEO_URL = "https://www.sz.gov.cn"
DP_NUCLEAR_URL = "https://www.dapeng.gov.cn"
DP_GEOPARK_URL = "https://www.dapeng.gov.cn"
YT_HISTORY_URL = "https://www.yantian.gov.cn"
SZ_SAFETY_URL = "https://www.sz.gov.cn"
PS_NATURE_URL = "https://www.szns.gov.cn"
GM_LIB_URL = "https://www.szgmlib.com.cn"
YT_LIB_URL = "https://www.ytlib.cn"
SARC_URL = "https://www.szns.gov.cn"
NTGC_URL = "https://www.szns.gov.cn"
ZSJBWG_URL = "https://www.szns.gov.cn"
NSSXF_URL = "https://activity.nslib.cn"

# ========== 输出配置 ==========
OUTPUT_DIR = "output"
ICS_FILE = "exhibitions.ics"
JSON_FILE = "exhibitions.json"

# ========== 场馆名称 ==========
# 市级核心场馆
SZLIB_NAME = "深圳图书馆"
SZ_CHILDREN_LIB_NAME = "深圳少年儿童图书馆"
SZBWG_NAME = "深圳博物馆"
SZSTM_NAME = "深圳科学技术馆"
SZCP_NAME = "深圳市少年宫"
SZAAC_NAME = "深圳市青少年活动中心"
SZNM_NAME = "深圳自然博物馆"
SZBO_NAME = "深圳滨海艺术中心"
SZCONCERT_NAME = "深圳音乐厅"
SZMOCAP_NAME = "深圳市当代艺术与城市规划馆"
SZSPORTS_NAME = "深圳市体育中心"
SZMASSART_NAME = "深圳市文化馆"

# 区级图书馆
NSLIB_NAME = "南山图书馆"
BALIB_NAME = "宝安图书馆"
FTLIB_NAME = "福田区图书馆"
LHLIB_NAME = "罗湖区图书馆"
LGLIB_NAME = "龙岗区图书馆"
LHXQLIB_NAME = "龙华区图书馆"
GMLIB_NAME = "光明区图书馆"
PSLIB_NAME = "坪山区图书馆"
YTLIB_NAME = "盐田区图书馆"
DPLIB_NAME = "大鹏新区图书馆"

# 区级博物馆
NSMUSEUM_NAME = "南山博物馆"
LGMUSEUM_NAME = "龙岗区博物馆"
BAMUSEUM_NAME = "宝安区博物馆"
LHMUSEUM_NAME = "龙华区博物馆"
LHMUSEUM2_NAME = "罗湖区博物馆"
DPGEOPARK_NAME = "大鹏半岛国家地质公园博物馆"

# 科技馆
BAOAN_KJG_NAME = "宝安科技馆"
LGKJG_NAME = "龙岗区科技馆"
LHKJG_NAME = "龙华区科技馆"
YTKJG_NAME = "盐田区科技馆"
GM_KJG_NAME = "深圳科学技术馆（光明新馆）"

# 青少年宫
BAOAN_QSNG_NAME = "宝安区青少年宫"
NSQSNG_NAME = "南山区青少年活动中心"
LGQSNG_NAME = "龙岗区青少年宫"
LHQSNG_NAME = "龙华区青少年宫"
LHQSNG2_NAME = "罗湖区青少年活动中心"
GMQSNG_NAME = "光明区青少年活动中心"
PSQSNG_NAME = "坪山区青少年宫"

# 体育中心
BAOAN_TY_NAME = "宝安体育中心"
NSWTZX_NAME = "南山文体中心"
SZWTY_NAME = "深圳湾体育中心"
LHTYZX_NAME = "龙岗体育中心"
LHWTX_NAME = "龙华文体中心"
GMTYZX_NAME = "光明区群众体育中心"
LHTYZX2_NAME = "罗湖区体育中心"
PSTYZX_NAME = "坪山体育中心"
YTTYZX_NAME = "盐田体育中心"

# 其他
NSWHG_NAME = "南山区文化馆"
BAOAN_1990_NAME = "宝安1990文化馆"
BAYAREA_EYE_NAME = "湾区之眼"
BAOAN_GUIHUA_NAME = "宝安城市规划展览馆"
LGGUIHUA_NAME = "龙岗城市规划展览馆"
NSGUIHUA_NAME = "南山城市规划展览馆"
LH_PRINTMAKING_NAME = "中国版画博物馆"
NSAQJY_NAME = "南山安全教育体验馆"
SKHYKPG_NAME = "蛇口海洋科普馆"

# 旧字段兼容
SZCEC_NAME = "深圳会展中心"
SHENZHEN_WORLD_NAME = "深圳国际会展中心"
OCT_WETLAND_NAME = "华侨城湿地生态展厅"
LG_HAKKA_NAME = "龙岗客家民俗博物馆"
LH_ECOLOGY_NAME = "龙华生态文明展览馆"
LH_PALEO_NAME = "深圳古生物博物馆"
DP_NUCLEAR_NAME = "大亚湾核能科技馆"
YT_HISTORY_NAME = "中英街历史博物馆"
SZ_SAFETY_NAME = "深圳市安全教育基地"
PS_NATURE_NAME = "深圳自然博物馆"
GM_LIB_NAME = "光明区少年儿童图书馆"
YT_LIB_NAME = "盐田区图书馆"
SARC_NAME = "深爱人才馆"
NTGC_NAME = "南头古城博物馆群"
ZSJBWG_NAME = "招商局历史博物馆"
NSSXF_NAME = "南山书房"

CALENDAR_NAME = "童行 (深圳亲子活动)"
CALENDAR_DESCRIPTION = "深圳展览与亲子活动日历 - 涵盖展览、图书馆活动、文体活动、科技馆活动等"
CALENDAR_TIMEZONE = "Asia/Shanghai"
