SZCEC_URL = "https://www.szcec.com/szcec/cn-schedule/review-2025/index.html"
SHENZHEN_WORLD_URL = "https://www.shenzhen-world.com/scheduling/index.html"
BALIB_URL = "https://www.balib.cn/"
SZLIB_URL = "https://www.szlib.org.cn/m/activity/lecture.html"
BAYAREA_EYE_URL = "https://www.baoan.gov.cn/"
BAOAN_KJG_URL = "https://www.baoan.gov.cn/"
BAOAN_TY_URL = "http://www.baoan.gov.cn/bawtlyj/"

OUTPUT_DIR = "output"
ICS_FILE = "exhibitions.ics"
JSON_FILE = "exhibitions.json"

SZCEC_NAME = "深圳会展中心"
SHENZHEN_WORLD_NAME = "深圳国际会展中心"
BALIB_NAME = "宝安图书馆"
SZLIB_NAME = "深圳图书馆"
BAYAREA_EYE_NAME = "湾区之眼"
BAOAN_KJG_NAME = "宝安科技馆"
BAOAN_TY_NAME = "宝安体育中心"

CALENDAR_NAME = "深圳亲子活动"
CALENDAR_DESCRIPTION = "深圳展览与亲子活动日历 - 涵盖展览、图书馆活动、文体活动、科技馆活动等"
CALENDAR_TIMEZONE = "Asia/Shanghai"