SZCEC_URL = "https://www.szcec.com/szcec/cn-schedule/review-2025/index.html"
SHENZHEN_WORLD_URL = "https://www.shenzhen-world.com/scheduling/index.html"
BALIB_URL = "https://www.balib.cn/"
SZLIB_URL = "https://www.szlib.org.cn/m/activity/lecture.html"
BAYAREA_EYE_URL = "https://www.baoan.gov.cn/"
BAOAN_KJG_URL = "https://www.baoan.gov.cn/"
BAOAN_TY_URL = "http://www.baoan.gov.cn/bawtlyj/"

# 南山区场馆
NSLIB_URL = "https://activity.nslib.cn"
NSMUSEUM_URL = "https://www.nanshanmuseum.com"
NSWHG_URL = "https://whgy.szmassart.com/nsqwhg/web/activity/list.html"
SKHYKPG_URL = "https://www.szns.gov.cn"
SARC_URL = "https://www.szns.gov.cn"
NTGC_URL = "https://www.szns.gov.cn"
ZSJBWG_URL = "https://www.szns.gov.cn"
NSQSNG_URL = "https://www.szns.gov.cn"
NSWTZX_URL = "https://www.szns.gov.cn"
SZWTY_URL = "https://www.szns.gov.cn"
SKWTPARK_URL = ""
HQCWH_URL = ""
NSAQJY_URL = "https://www.szns.gov.cn"
NSSXF_URL = "https://activity.nslib.cn"
RCPY_URL = ""
SZWGY_URL = ""
QHS_URL = ""

OUTPUT_DIR = "output"
ICS_FILE = "exhibitions.ics"
JSON_FILE = "exhibitions.json"

SZCEC_NAME = "深圳会展中心"
SHENZHEN_WORLD_NAME = "深圳国际会展中心"
BALIB_NAME = "宝安图书馆"
SZLIB_NAME = "深圳图书馆"
BAYAREA_EYE_NAME = "湾区之眼"
BAOAN_KJG_NAME = "宝安科技馆"
BAOAN_TY_NAME = "宝安体育中心"

# 南山区场馆名称
NSLIB_NAME = "南山图书馆"
NSMUSEUM_NAME = "南山博物馆"
NSWHG_NAME = "南山区文化馆"
SKHYKPG_NAME = "蛇口海洋科普馆"
SARC_NAME = "深爱人才馆"
NTGC_NAME = "南头古城博物馆群"
ZSJBWG_NAME = "招商局历史博物馆"
NSQSNG_NAME = "南山区青少年活动中心"
NSWTZX_NAME = "南山文体中心"
SZWTY_NAME = "深圳湾体育中心"
SKWTPARK_NAME = "蛇口文体公园"
HQCWH_NAME = "华侨城体育文化中心"
NSAQJY_NAME = "南山安全教育体验馆"
NSSXF_NAME = "南山书房"
RCPY_NAME = "人才公园"
SZWGY_NAME = "深圳湾公园"
QHS_NAME = "前海石公园"

CALENDAR_NAME = "深圳亲子活动"
CALENDAR_DESCRIPTION = "深圳展览与亲子活动日历 - 涵盖展览、图书馆活动、文体活动、科技馆活动等"
CALENDAR_TIMEZONE = "Asia/Shanghai"