import json

new_activities = [
    {
        "title": "广东科学中心暑期假日科学派",
        "venue": "广东科学中心",
        "city": "guangzhou",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.gdsc.cn",
        "description": "暑期假日科学派包含趣味科学实验、科普剧场、科学工坊等系列活动，每天定时开展不同主题的亲子科普体验，让孩子们在玩乐中探索科学奥秘。",
        "category": "科普活动",
        "fee": "免费需预约",
        "contact": "",
        "family_friendly": True,
        "source": "广东科学中心"
    },
    {
        "title": "尼罗河的赠礼——古埃及文物与数字艺术展",
        "venue": "南越王博物院",
        "city": "guangzhou",
        "start_date": "2026-07-01",
        "end_date": "2026-10-18",
        "link": "https://www.yuewangmuseum.com",
        "description": "展览汇聚古埃及珍贵文物，结合数字艺术技术呈现尼罗河文明的辉煌历史，设置多个互动体验区，适合亲子共同探索古文明奥秘。",
        "category": "展览",
        "fee": "免费需预约",
        "contact": "",
        "family_friendly": True,
        "source": "南越王博物院"
    },
    {
        "title": "广州图书馆暑期系列活动",
        "venue": "广州图书馆",
        "city": "guangzhou",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.gzlib.org.cn",
        "description": "暑期推出'阅读夏令营'、'绘本故事会'、'科普讲座'等系列活动，涵盖少儿阅读、科普教育、艺术欣赏等多个领域，丰富孩子们的暑期生活。",
        "category": "讲座阅读",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "广州图书馆"
    },
    {
        "title": "广州青少年科技馆暑期互动体验",
        "venue": "广州青少年科技馆",
        "city": "guangzhou",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "http://www.gzyouthscitech.com",
        "description": "暑期开放多个互动展厅，包括航空航天、机器人、能源科学等主题，每天举办科学实验秀和科普讲座，为青少年提供沉浸式科技体验。",
        "category": "科普活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "广州青少年科技馆"
    },
    {
        "title": "广州地铁博物馆暑期体验",
        "venue": "广州地铁博物馆",
        "city": "guangzhou",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.gzmtrmuseum.com",
        "description": "暑期推出地铁主题亲子活动，包括地铁模型拼装、安全知识讲座、模拟驾驶体验等，让孩子们了解地铁运营背后的科学知识。",
        "category": "科普活动",
        "fee": "免费需预约",
        "contact": "",
        "family_friendly": True,
        "source": "广州地铁博物馆"
    },
    {
        "title": "广州市文化馆新馆暑期文化体验",
        "venue": "广州市文化馆新馆",
        "city": "guangzhou",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "",
        "description": "暑期开展岭南文化体验活动，包括广绣、木雕、古琴等非遗技艺展示与体验课程，让孩子们感受传统文化魅力。",
        "category": "亲子活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "广州市文化馆"
    },
    {
        "title": "'科'好玩了——2026暑假营",
        "venue": "上海科技馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.sstm.cn",
        "description": "上海科技馆暑期推出多个主题夏令营，包括机器人编程、科学实验、自然探索等，让孩子们在互动中学习科学知识，培养创新思维。",
        "category": "科普活动",
        "fee": "收费",
        "contact": "",
        "family_friendly": True,
        "source": "上海科技馆"
    },
    {
        "title": "巴斯夫'小小化学家'暑期活动",
        "venue": "上海科技馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.sstm.cn",
        "description": "专为6-12岁儿童设计的趣味化学实验活动，通过安全有趣的实验让孩子们探索化学世界，培养科学兴趣和动手能力。",
        "category": "科普活动",
        "fee": "免费需预约",
        "contact": "",
        "family_friendly": True,
        "source": "上海科技馆"
    },
    {
        "title": "《只有树知道》临展暑期限时活动",
        "venue": "上海自然博物馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.snhm.org",
        "description": "通过沉浸式展览展示树木的生命奥秘，设置多个互动装置和科普讲解，让观众感受大自然的神奇与美丽。",
        "category": "展览",
        "fee": "需购票",
        "contact": "",
        "family_friendly": True,
        "source": "上海自然博物馆"
    },
    {
        "title": "夜宿上海自然博物馆",
        "venue": "上海自然博物馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.snhm.org",
        "description": "暑期特别推出夜宿博物馆活动，孩子们可以在恐龙化石旁入睡，体验奇妙的博物馆之夜，包含科普讲解和趣味活动。",
        "category": "亲子活动",
        "fee": "收费",
        "contact": "",
        "family_friendly": True,
        "source": "上海自然博物馆"
    },
    {
        "title": "世界树之巅——美洲古代文明大展",
        "venue": "上海博物馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-10-15",
        "link": "https://www.shanghaimuseum.net",
        "description": "汇聚美洲古代文明珍贵文物，包括玛雅、阿兹特克等文明的艺术珍品，系统展示美洲古代文明的辉煌成就，设置互动体验区。",
        "category": "展览",
        "fee": "免费需预约",
        "contact": "",
        "family_friendly": True,
        "source": "上海博物馆"
    },
    {
        "title": "上海少年儿童图书馆暑期活动",
        "venue": "上海少年儿童图书馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.sstl.org.cn",
        "description": "暑期推出'阅读之星'、'绘本故事会'、'小小志愿者'等系列活动，为少年儿童提供丰富的阅读体验和社会实践机会。",
        "category": "讲座阅读",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "上海少年儿童图书馆"
    },
    {
        "title": "世界技能博物馆暑期体验",
        "venue": "世界技能博物馆",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.worldskillsmuseum.com",
        "description": "暑期开放多个技能体验工坊，包括机械加工、电子技术、艺术设计等，让青少年感受技能的魅力，培养职业兴趣。",
        "category": "科普活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "世界技能博物馆"
    },
    {
        "title": "徐家汇书院暑期阅读",
        "venue": "徐家汇书院",
        "city": "shanghai",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "",
        "description": "暑期推出'阅读马拉松'、'作家见面会'、'亲子阅读分享'等活动，为读者提供丰富的阅读体验和文化交流机会。",
        "category": "讲座阅读",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "徐家汇书院"
    },
    {
        "title": "快乐暑期，科海扬帆——北京科学中心暑期活动",
        "venue": "北京科学中心",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.bjsc.net.cn",
        "description": "暑期推出多个主题科普活动，包括天文观测、物理实验、化学探秘等，每天定时开展科学实验秀和科普讲座，适合亲子共同参与。",
        "category": "科普活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "北京科学中心"
    },
    {
        "title": "北科展教坊专题课程",
        "venue": "北京科学中心",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.bjsc.net.cn",
        "description": "暑期开设多个专题课程，包括机器人编程、3D打印、科学摄影等，由专业老师指导，培养青少年的科技创新能力。",
        "category": "科普活动",
        "fee": "收费",
        "contact": "",
        "family_friendly": True,
        "source": "北京科学中心"
    },
    {
        "title": "北科剧院科学剧场",
        "venue": "北京科学中心",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.bjsc.net.cn",
        "description": "暑期推出科学剧场演出，通过生动有趣的表演形式展示科学原理，让孩子们在欢乐中学习科学知识。",
        "category": "演出",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "北京科学中心"
    },
    {
        "title": "中国科技馆暑期科学实验秀",
        "venue": "中国科学技术馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.cstm.net.cn",
        "description": "暑期每天定时开展科学实验秀，通过精彩的实验演示展示物理、化学、生物等科学原理，吸引孩子们探索科学奥秘。",
        "category": "科普活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "中国科学技术馆"
    },
    {
        "title": "中国科技馆夜场开放",
        "venue": "中国科学技术馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.cstm.net.cn",
        "description": "暑期每周五、周六延长开放至21:00，推出夜间科学探索活动，包括星空观测、科学电影、互动展览等，提供独特的夜间参观体验。",
        "category": "展览",
        "fee": "免费需预约",
        "contact": "",
        "family_friendly": True,
        "source": "中国科学技术馆"
    },
    {
        "title": "北京天文馆暑期夜场",
        "venue": "北京天文馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.bjp.org.cn",
        "description": "暑期推出夜场星空观测活动，配备专业天文望远镜，由天文专家讲解星座知识，让孩子们感受浩瀚宇宙的魅力。",
        "category": "科普活动",
        "fee": "需购票",
        "contact": "",
        "family_friendly": True,
        "source": "北京天文馆"
    },
    {
        "title": "中国妇女儿童博物馆暑期展览",
        "venue": "中国妇女儿童博物馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.cwmuseum.org.cn",
        "description": "暑期推出多个儿童主题展览，包括儿童文学、儿童艺术、儿童科技等，设置互动体验区和亲子活动空间。",
        "category": "展览",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "中国妇女儿童博物馆"
    },
    {
        "title": "中国消防博物馆暑期安全教育",
        "venue": "中国消防博物馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.cfmuseum.com",
        "description": "暑期推出消防安全教育活动，包括火灾模拟体验、消防知识讲座、灭火演练等，提高孩子们的消防安全意识和自救能力。",
        "category": "科普活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "中国消防博物馆"
    },
    {
        "title": "中国古动物馆暑期恐龙探秘",
        "venue": "中国古动物馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.paleozoo.cn",
        "description": "暑期推出恐龙探秘活动，包括恐龙化石挖掘体验、古生物科普讲座、恐龙模型展等，让孩子们穿越时空，探索史前生命奥秘。",
        "category": "科普活动",
        "fee": "需购票",
        "contact": "",
        "family_friendly": True,
        "source": "中国古动物馆"
    },
    {
        "title": "中国园林博物馆暑期体验",
        "venue": "中国园林博物馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.yuanlinmuseum.cn",
        "description": "暑期推出园林文化体验活动，包括古典园林游览、传统手工艺体验、园林知识讲座等，让孩子们感受中国传统园林文化的魅力。",
        "category": "亲子活动",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "中国园林博物馆"
    },
    {
        "title": "首都图书馆暑期活动",
        "venue": "首都图书馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.clcn.net.cn",
        "description": "暑期推出'阅读成长计划'、'少儿科普讲座'、'传统文化体验'等系列活动，为少年儿童提供丰富的阅读和文化体验。",
        "category": "讲座阅读",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "首都图书馆"
    },
    {
        "title": "国家图书馆暑期少儿活动",
        "venue": "国家图书馆少年儿童馆",
        "city": "beijing",
        "start_date": "2026-07-01",
        "end_date": "2026-08-31",
        "link": "https://www.nlc.cn",
        "description": "暑期推出'小小图书馆员'、'绘本故事会'、'科普阅读'等活动，让孩子们在阅读中成长，培养良好的阅读习惯。",
        "category": "讲座阅读",
        "fee": "免费",
        "contact": "",
        "family_friendly": True,
        "source": "国家图书馆"
    },
]

with open('manual_data.json', 'r', encoding='utf-8') as f:
    activities = json.load(f)

existing_titles = {a['title'] for a in activities}
added_count = 0
for activity in new_activities:
    if activity['title'] not in existing_titles:
        activities.append(activity)
        print(f"添加: {activity['title']} ({activity['venue']})")
        added_count += 1

with open('manual_data.json', 'w', encoding='utf-8') as f:
    json.dump(activities, f, ensure_ascii=False, indent=2)

print(f"\n共添加 {added_count} 个活动")
