import json
import os

DATA_FILE = 'output/exhibitions.json'
OUTPUT_FILE = 'output/exhibitions.json'

new_activities = [
    # ========== 北京活动 ==========
    {"name": "奇妙动物探索夏令营", "venue": "中国农业博物馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-13", "end_date": "2026-07-17", "fee": "免费", "description": "课程根据昆虫→鱼类→两栖类→爬行类→鸟类循序渐进解锁知识，每天14:00-16:00在4号馆报告厅开展。", "source": "北京本地宝", "highlights": ["动物科普", "夏令营", "亲子活动"], "type": "亲子活动"},
    {"name": "寻迹茅盾数字游园", "venue": "中国现代文学馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-04", "end_date": "2026-08-31", "fee": "免费", "description": "到馆扫描活动二维码即可免费参与数字游园，完成任务后可领取馆藏文物《子夜》手稿参观纪念票。", "source": "北京本地宝", "highlights": ["数字游园", "文学", "互动体验"], "type": "展览"},
    {"name": "园丁养成记花园共建", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-07-25", "fee": "免费", "description": "邀请公众志愿者走进秘密花园，参与花园共建，学习园林生态知识与劳动技能。", "source": "北京本地宝", "highlights": ["花园共建", "生态知识", "志愿者"], "type": "亲子活动"},
    {"name": "自然笔记创作体验", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-04", "end_date": "2026-07-26", "fee": "免费", "description": "科普老师带领游客对片石山房内的园林景观进行观察和学习，用绘画搭配文字记录的方式创作自然笔记。", "source": "北京本地宝", "highlights": ["自然笔记", "绘画", "园林"], "type": "亲子活动"},
    {"name": "片石山房自然手工工坊", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "依托园林中的自然生态知识与物候特征，开展沉浸式科普互动与科普展示。", "source": "北京本地宝", "highlights": ["手工工坊", "自然科普", "沉浸式"], "type": "亲子活动"},
    {"name": "红楼探园十二讲", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-18", "end_date": "2026-07-18", "fee": "免费", "description": "特邀专家开展'今天我们为什么还要读红楼梦'专题讲座，品读红楼经典，共赏文学与园林文化相融的东方雅韵。", "source": "北京本地宝", "highlights": ["红楼梦", "讲座", "园林文化"], "type": "讲座"},
    {"name": "园博读书慧", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "围绕园林文化、古籍文献、造园技艺等主题，开展晚间读书分享、文化交流活动。", "source": "北京本地宝", "highlights": ["读书分享", "园林文化", "古籍"], "type": "讲座"},
    {"name": "竹外茶社文化雅集", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-15", "end_date": "2026-07-25", "fee": "免费", "description": "围绕园林物候特征与节气节俗，通过夏日手工与艺术体验，开启沉浸式文化雅集。", "source": "北京本地宝", "highlights": ["文化雅集", "手工体验", "节气"], "type": "亲子活动"},
    {"name": "像素花园拼豆艺术创作", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "当园林邂逅缤纷拼豆，创意与自然科普的碰撞，构建知识学习、艺术创作、情感交流于一体的教育平台。", "source": "北京本地宝", "highlights": ["拼豆艺术", "创意", "自然科普"], "type": "亲子活动"},
    {"name": "非遗掐丝珐琅体验", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "将中国传统园林艺术与珐琅等非遗手工艺相结合，让观众在园林诗意空间中感悟非遗技艺的精湛。", "source": "北京本地宝", "highlights": ["掐丝珐琅", "非遗", "手工艺"], "type": "亲子活动"},
    {"name": "小小化学家", "venue": "中国科学技术馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-21", "end_date": "2026-07-24", "fee": "免费", "description": "沿用'电池的奥秘'经典实验课程，引导青少年通过制作原电池探索化学世界。", "source": "北京本地宝", "highlights": ["化学实验", "电池", "科学"], "type": "亲子活动"},
    {"name": "科学体验营AI创意奇妙之旅", "venue": "中国科学技术馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "结合'数字中国'主题，通过'展品讲解+游馆打卡+实践体验'的方式，培养青少年创新思维与实践能力。", "source": "北京本地宝", "highlights": ["AI创意", "科学体验", "创新思维"], "type": "亲子活动"},
    {"name": "京华飞羽鸟类专题展", "venue": "中国科学技术馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "设置'城市睦邻''湿地精灵''山林居民''和合共生'四大展区，普及生物多样性知识，传播生态文明理念。", "source": "北京本地宝", "highlights": ["鸟类科普", "生态保护", "生物多样性"], "type": "展览"},
    {"name": "观象授时主题活动", "venue": "中国科学技术馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "7月聚焦天文，每周设置'观象授时''古代仪象''日影妙用'等分主题活动。", "source": "北京本地宝", "highlights": ["天文", "古代科技", "科普"], "type": "亲子活动"},
    {"name": "古代兵器主题活动", "venue": "中国科学技术馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-08-01", "end_date": "2026-08-31", "fee": "免费", "description": "8月以军事为主题，系统讲解古代兵器、战车、战船的发展历程，搭配自然观察智能活动。", "source": "北京本地宝", "highlights": ["古代兵器", "军事", "科普"], "type": "亲子活动"},
    {"name": "音乐剧甪端", "venue": "故宫博物院", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "故宫首部大型沉浸式家庭音乐剧，以故宫馆藏文物为原型，围绕文物传承主题展开故事，结合裸眼3D、AR技术、全息投影等前沿科技手段。", "source": "北京本地宝", "highlights": ["音乐剧", "故宫", "沉浸式"], "type": "演出"},
    {"name": "酷爽夏日主题活动", "venue": "北京环球度假区", "city": "beijing", "district": "通州区", "start_date": "2026-07-01", "end_date": "2026-08-16", "fee": "收费", "description": "夏季标志性主题活动，包含哈利·波特的魔法世界、变形金刚基地等七大主题景区的特色活动。", "source": "北京本地宝", "highlights": ["主题乐园", "酷爽夏日", "亲子游乐"], "type": "演出"},
    {"name": "重返霍格沃茨返校季", "venue": "北京环球度假区", "city": "beijing", "district": "通州区", "start_date": "2026-08-03", "end_date": "2026-09-01", "fee": "收费", "description": "哈利·波特的魔法世界主题活动，园区餐饮、纪念品商店及酒店住宿同步推出限定套餐与主题周边。", "source": "北京本地宝", "highlights": ["哈利波特", "返校季", "主题活动"], "type": "演出"},
    {"name": "谜人的三星堆儿童剧", "venue": "北京大学百周年纪念讲堂", "city": "beijing", "district": "海淀区", "start_date": "2026-08-01", "end_date": "2026-08-02", "fee": "需购票", "description": "北京儿童艺术剧院出品，以广汉三星堆遗址为原点，采用'现实考古+奇幻想象'双线叙事，借儿童视角让古蜀文物'活'起来。", "source": "北京本地宝", "highlights": ["儿童剧", "三星堆", "考古"], "type": "演出"},
    {"name": "6D沉浸式恐龙展", "venue": "国家自然博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "国内首个以中国本土恐龙为主题的6D沉浸式恐龙展，集结20余种中国本土恐龙，打造可走入、可感知的白垩纪秘境。", "source": "北京本地宝", "highlights": ["恐龙展", "6D沉浸式", "科普"], "type": "展览"},
    {"name": "奇趣书海夏梦成荫", "venue": "首都图书馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "近380场融合少儿阅读、名家讲坛、古卷匠心、视听美育四大板块的文化活动。", "source": "北京本地宝", "highlights": ["阅读", "讲座", "美育"], "type": "讲座"},
    {"name": "打开艺术之门夏令营", "venue": "北京音乐厅", "city": "beijing", "district": "西城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "47场儿童专属演出、七大艺术研学营，湖笔制作、景泰蓝点蓝等非遗体验营常态化开课。", "source": "北京本地宝", "highlights": ["艺术", "夏令营", "非遗"], "type": "演出"},
    {"name": "非遗手作体验", "venue": "珐琅厂", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "盛锡福、四联美发、珐琅厂等老字号开放夏日体验专场，推出'非遗手作+成品带走'套餐。", "source": "北京本地宝", "highlights": ["非遗", "手作", "老字号"], "type": "亲子活动"},
    {"name": "版本馆研学活动", "venue": "中国国家版本馆", "city": "beijing", "district": "昌平区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "开放周末研学活动预约通道，专业讲解引导下开启沉浸式文化探索之旅，参观版本工艺展、斯文在兹展及版本琳琅展区。", "source": "北京本地宝", "highlights": ["版本馆", "研学", "文化"], "type": "亲子活动"},
    {"name": "荣光之路文物展", "venue": "中国共产党早期北京革命活动纪念馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "'荣光之路——中国共产党的创建文物史料展'正在展出，通过105件套珍贵历史文物和文献档案，贯通呈现中国共产党确立初心、开天辟地、铸就伟业的荣光之路。", "source": "北京本地宝", "highlights": ["红色文化", "党史", "展览"], "type": "展览"},
    {"name": "历史中国鼎铸文明", "venue": "中国考古博物馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "基本陈列包括'文明起源''宅兹中国''大国一统''和融万方''民族觉醒'五个专题，集中展示五千多年中华文明与统一多民族国家形成和发展的历史。", "source": "北京本地宝", "highlights": ["考古", "文明", "展览"], "type": "展览"},
    {"name": "大眼京摩天轮", "venue": "北京欢乐谷", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "收费", "description": "全新地标'大眼京'摩天轮正式运行，总高约99米，配备恒温轿厢与VIP主题空间，可饱览城市美景。", "source": "北京本地宝", "highlights": ["摩天轮", "欢乐谷", "亲子"], "type": "演出"},
    {"name": "龙潭中湖摩天轮之夜", "venue": "龙潭中湖公园", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "整合文创市集、闲置交换、非正式音乐会与露天放映等周末主题活动，构筑集观光、购物、演艺、社交于一体的消费闭环。", "source": "北京本地宝", "highlights": ["市集", "音乐会", "露天电影"], "type": "亲子活动"},
    {"name": "越野奇兵户外探险", "venue": "昌平区玖耀里", "city": "beijing", "district": "昌平区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "涵盖射击、定向寻宝等户外探险主题活动。", "source": "北京本地宝", "highlights": ["户外", "探险", "亲子"], "type": "亲子活动"},
    {"name": "微风露台文化活动", "venue": "魏公芳华里", "city": "beijing", "district": "海淀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "登上露台远眺中轴线风光，品咖啡、听音乐、参与露天手作市集。", "source": "北京本地宝", "highlights": ["露台", "市集", "文化"], "type": "亲子活动"},
    # ========== 广州活动 ==========
    {"name": "万物皆数数学嘉年华", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-18", "end_date": "2026-07-19", "fee": "免费", "description": "联动东莞松山湖数学探索馆打造数学思维游乐场，划分古代算学、几何拼图、棋艺对战、数理生活等七大板块，50余种互动体验项目。", "source": "广州本地宝", "highlights": ["数学", "嘉年华", "互动"], "type": "亲子活动"},
    {"name": "小小气液魔法师", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-18", "end_date": "2026-07-18", "fee": "免费", "description": "孩子们化身小小气液魔法师，通过趣味实验了解气压差原理，亲手搭建液压升降台感受液压传动。", "source": "广州本地宝", "highlights": ["科学实验", "流体力学", "亲子"], "type": "亲子活动"},
    {"name": "儿童健康科普义诊", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-19", "end_date": "2026-07-19", "fee": "免费", "description": "广州医科大学附属市八医院医护团队开设近视防控、外伤应急、儿童营养三大专业讲座，同步提供视力筛查、身高发育评估等科普义诊活动。", "source": "广州本地宝", "highlights": ["健康科普", "义诊", "儿童"], "type": "讲座"},
    {"name": "读懂广州科学家故事", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-19", "end_date": "2026-07-19", "fee": "免费", "description": "讲述张景中院士如何'把数学变得更容易'的故事，带领孩子们跳出传统课本学习模式，从基础面积公式入手趣味探究经典几何定理。", "source": "广州本地宝", "highlights": ["科学家", "数学", "讲座"], "type": "讲座"},
    {"name": "全球动物科普嘉年华", "venue": "广州长隆野生动物世界", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "收费", "description": "围绕科普开展十项活动，包括动物主题日（如老虎日、大象日等）、科普讲堂、便便工坊等，挖掘动物冷知识。", "source": "广州本地宝", "highlights": ["动物科普", "长隆", "嘉年华"], "type": "亲子活动"},
    {"name": "森巴酷爽嘉年华", "venue": "广州长隆欢乐世界", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "收费", "description": "围绕'玩水''亲子''森巴狂欢'主题展开，主要内容为'森巴酷爽玩水派对'，带动以中央广场为核心的餐商演一体化特别活动。", "source": "广州本地宝", "highlights": ["玩水", "森巴", "亲子"], "type": "演出"},
    {"name": "神奇兔妈儿童人偶剧", "venue": "从化荔枝球乐园", "city": "guangzhou", "district": "从化区", "start_date": "2026-07-19", "end_date": "2026-07-19", "fee": "收费", "description": "故事围绕亲子日常展开，用软萌人偶演绎细腻母爱，现场超多近距离互动，引导孩子理解妈妈藏在唠叨里的深爱。", "source": "广州本地宝", "highlights": ["人偶剧", "母爱", "亲子"], "type": "演出"},
    {"name": "青蛙王子儿童人偶剧", "venue": "从化荔枝球乐园", "city": "guangzhou", "district": "从化区", "start_date": "2026-08-02", "end_date": "2026-08-02", "fee": "收费", "description": "被魔法束缚的青蛙王子，等待真诚的友谊解除诅咒。华丽舞美搭配鲜活人偶角色，演员会走下舞台和小朋友互动。", "source": "广州本地宝", "highlights": ["人偶剧", "童话", "互动"], "type": "演出"},
    {"name": "三只小猪儿童人偶剧", "venue": "从化荔枝球乐园", "city": "guangzhou", "district": "从化区", "start_date": "2026-08-16", "end_date": "2026-08-16", "fee": "收费", "description": "家喻户晓的经典童话全新舞台改编！三只性格迥异的小猪，和大灰狼斗智斗勇，现场设置上台游戏、问答送礼、亲子互动环节。", "source": "广州本地宝", "highlights": ["人偶剧", "童话", "互动"], "type": "演出"},
    {"name": "5D沉浸式飞行电影", "venue": "从化荔枝球乐园", "city": "guangzhou", "district": "从化区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "整个7、8月工作日及无专场演出的周末，剧场每日循环放映两大5D动感影片，入园即可体验。", "source": "广州本地宝", "highlights": ["5D电影", "飞行体验", "亲子"], "type": "演出"},
    {"name": "即兴喜剧秀", "venue": "从化荔枝球乐园", "city": "guangzhou", "district": "从化区", "start_date": "2026-07-18", "end_date": "2026-08-08", "fee": "收费", "description": "广州老牌西瓜剧团即兴专场！没有固定剧本，现场根据观众随口给出的关键词即兴创作完整故事。", "source": "广州本地宝", "highlights": ["即兴喜剧", "亲子", "欢乐"], "type": "演出"},
    {"name": "合唱音乐会", "venue": "从化荔枝球乐园", "city": "guangzhou", "district": "从化区", "start_date": "2026-08-15", "end_date": "2026-08-15", "fee": "收费", "description": "纯净人声合唱专场，多声部天籁旋律萦绕剧场，柔和舒缓的乐曲抚平夏日浮躁。", "source": "广州本地宝", "highlights": ["合唱", "音乐会", "治愈"], "type": "演出"},
    {"name": "虫篆微观奇境", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "以昆虫为纽带，有机融合科普教育、艺术创作与互动体验，配套科普分享会等活动。", "source": "广州本地宝", "highlights": ["昆虫", "科普", "艺术"], "type": "展览"},
    {"name": "博物馆星空夜宿", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "十大研学课程之一，夜间在博物馆内露营，体验不一样的博物馆奇妙夜。", "source": "广州本地宝", "highlights": ["夜宿", "博物馆", "研学"], "type": "亲子活动"},
    {"name": "真化石清修师", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "十大研学课程之一，亲手体验化石清理修复工作，了解古生物化石的发掘过程。", "source": "广州本地宝", "highlights": ["化石", "考古", "研学"], "type": "亲子活动"},
    {"name": "文艺复兴大师作品展", "venue": "广东省博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "收费", "description": "格拉斯哥博物馆意大利艺术珍藏在中国的重要亮相，近70件（套）珍稀藏品，涵盖绘画、雕塑、陶器、玻璃、兵器与织物六大门类。", "source": "广州本地宝", "highlights": ["文艺复兴", "艺术", "展览"], "type": "展览"},
    {"name": "青州微笑佛造像展", "venue": "广州艺术博物院", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "华南地区首次大规模、高规格呈现古青州造像艺术，汇聚62件造像精品，其中一级文物达22件。", "source": "广州本地宝", "highlights": ["佛造像", "青州", "艺术"], "type": "展览"},
    {"name": "一念敦煌大展", "venue": "广州艺术博物院", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "敦煌艺术主题展览，呈现敦煌壁画、雕塑等珍贵文物的数字化复制品。", "source": "广州本地宝", "highlights": ["敦煌", "艺术", "展览"], "type": "展览"},
    {"name": "微观万相唐卡艺术展", "venue": "广州人民艺术中心", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "青海热贡地区唐卡艺术的经典之作与数字化创新成果，所有展品都可以扫码听数字语音讲解。", "source": "广州本地宝", "highlights": ["唐卡", "艺术", "数字"], "type": "展览"},
    {"name": "星火启程文物展", "venue": "农讲所纪念馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "集中呈现农讲所自2023年启动'历届教员学员足迹寻访项目'以来的成果，展出藏品118件（其中珍贵文物72件）。", "source": "广州本地宝", "highlights": ["红色文化", "农讲所", "展览"], "type": "展览"},
    {"name": "救民水火纪念展", "venue": "黄埔军校旧址纪念馆", "city": "guangzhou", "district": "黄埔区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "'救民水火——纪念国民革命军一百周年展'，展出著名的《北伐画史》等珍贵历史资料。", "source": "广州本地宝", "highlights": ["黄埔军校", "北伐", "展览"], "type": "展览"},
    {"name": "萧华长征记忆展", "venue": "广州起义纪念馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "结合萧华同志的珍贵文物和资料，深度解读《长征组歌》，通过主题油画、艺术场景、多媒体演绎等形式还原长征重大历史场景。", "source": "广州本地宝", "highlights": ["萧华", "长征", "展览"], "type": "展览"},
    {"name": "余广州平且康", "venue": "广州海事博物馆", "city": "guangzhou", "district": "南沙区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "魏晋南北朝时期的广州文物展览，展出中部非洲雕像等珍贵展品。", "source": "广州本地宝", "highlights": ["广州历史", "文物", "展览"], "type": "展览"},
    {"name": "广州图书馆暑期阅读季", "venue": "广州图书馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "开展少儿阅读、名家讲坛、古卷匠心、视听美育等四大板块文化活动。", "source": "广州本地宝", "highlights": ["阅读", "讲座", "暑期"], "type": "讲座"},
    {"name": "南越王博物院暑期活动", "venue": "南越王博物院", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "推出文物修复体验、南越文化小课堂等亲子研学活动。", "source": "广州本地宝", "highlights": ["南越王", "文物", "研学"], "type": "亲子活动"},
    {"name": "广州动物园奇妙夜", "venue": "广州动物园", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "夜间开放动物园，探秘夜间动物行为，体验不一样的动物世界。", "source": "广州本地宝", "highlights": ["动物园", "夜场", "亲子"], "type": "亲子活动"},
    {"name": "融创文旅城水世界", "venue": "广州融创文旅城", "city": "guangzhou", "district": "花都区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "大型室内水乐园，全年恒温，包含水上过山车、大喇叭、漂流河等刺激项目。", "source": "广州本地宝", "highlights": ["水乐园", "亲子", "游玩"], "type": "演出"},
    {"name": "永庆坊非遗体验", "venue": "永庆坊", "city": "guangzhou", "district": "荔湾区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "广彩、广绣、醒狮等非遗手作体验，感受岭南文化魅力。", "source": "广州本地宝", "highlights": ["非遗", "岭南文化", "体验"], "type": "亲子活动"},
    # ========== 上海活动 ==========
    {"name": "世界树之巅美洲古代文明大展", "venue": "上海博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-09", "end_date": "2027-11-14", "fee": "收费", "description": "上海博物馆继'金字塔之巅'之后又一重磅国际大展，联合墨西哥、秘鲁顶尖文博机构，汇聚近3000件精美文物，全景式勾勒古代中南美洲的文明长卷。", "source": "上海本地宝", "highlights": ["美洲文明", "大展", "文物"], "type": "展览"},
    {"name": "美洲古代文明夜场", "venue": "上海博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-09", "end_date": "2026-08-31", "fee": "收费", "description": "每周二至周五17:00-21:00开放夜场，让观众在凉爽的夜晚沉浸式感受古代美洲文明。", "source": "上海本地宝", "highlights": ["夜场", "展览", "美洲"], "type": "展览"},
    {"name": "动物奇妙夜", "venue": "上海博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-09", "end_date": "2026-08-31", "fee": "收费", "description": "每周六18:00-21:00举办'动物奇妙夜'主题活动，探索美洲古代文明中的动物元素。", "source": "上海本地宝", "highlights": ["动物", "夜场", "互动"], "type": "亲子活动"},
    {"name": "中共一大纪念馆夜间开放", "venue": "中共一大纪念馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-08-01", "fee": "免费", "description": "7月1日、7月25日、8月1日夜间开放至20:00，感悟初心，重温红色历史。", "source": "上海本地宝", "highlights": ["红色文化", "夜场", "免费"], "type": "展览"},
    {"name": "电影党课火种", "venue": "中共一大纪念馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-25", "end_date": "2026-07-25", "fee": "免费", "description": "7月25日17:00-20:00播放电影党课《火种》，学习革命历史。", "source": "上海本地宝", "highlights": ["电影", "党课", "红色"], "type": "演出"},
    {"name": "江河联山海无界结万象", "venue": "上海市历史博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-03", "end_date": "2026-08-29", "fee": "免费", "description": "博物馆奇妙夜系列活动，包括'小浪花'讲解团、苏州河夜游Citywalk、徽州非遗工坊等。", "source": "上海本地宝", "highlights": ["苏州河", "夜游", "非遗"], "type": "亲子活动"},
    {"name": "苏州河历史文化展", "venue": "上海市历史博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "从元代水闸到外白渡桥，展示苏州河的历史变迁。", "source": "上海本地宝", "highlights": ["苏州河", "历史", "展览"], "type": "展览"},
    {"name": "国采故宫藏清代帝后服饰展", "venue": "上海世博会博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-07", "end_date": "2026-10-07", "fee": "收费", "description": "世博会博物馆携手故宫博物院推出，展出康熙礼服褂、乾隆龙袍、嘉庆朝袍等珍贵服饰，九成从未出京。", "source": "上海本地宝", "highlights": ["故宫", "服饰", "展览"], "type": "展览"},
    {"name": "熔光凝形铸造玻璃艺术展", "venue": "上海琉璃艺术博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-18", "end_date": "2026-08-15", "fee": "收费", "description": "夜游看展，开放时间延长至20:00，欣赏铸造玻璃的艺术叙事。", "source": "上海本地宝", "highlights": ["玻璃艺术", "夜场", "展览"], "type": "展览"},
    {"name": "近代名人墨知识讲座", "venue": "上海周虎臣曹素功笔墨博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-10", "end_date": "2026-07-10", "fee": "免费", "description": "7月10日17:00-19:00举办《近代名人墨知识》讲座。", "source": "上海本地宝", "highlights": ["笔墨", "讲座", "文化"], "type": "讲座"},
    {"name": "乒乓体验营", "venue": "国际乒联博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-08", "end_date": "2026-07-30", "fee": "免费", "description": "7月8日、7月16日、7月30日举办乒乓体验营，适合中小学生参与。", "source": "上海本地宝", "highlights": ["乒乓球", "体验", "亲子"], "type": "亲子活动"},
    {"name": "史前星球恐龙篇", "venue": "西岸美术馆", "city": "shanghai", "district": "徐汇区", "start_date": "2026-07-01", "end_date": "2027-01-27", "fee": "收费", "description": "改编自广受赞誉的纪录片系列'Prehistoric Planet史前星球'，通过先进的360°沉浸式投影系统，与史前生物'同行'。", "source": "上海本地宝", "highlights": ["恐龙", "沉浸式", "纪录片"], "type": "展览"},
    {"name": "动物奇妙夜", "venue": "上海动物园", "city": "shanghai", "district": "长宁区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "探秘夜间动物园，增设夜猫子和森林课夜观活动，展示动物园内夜行性动物难得一见的自然行为。", "source": "上海本地宝", "highlights": ["动物园", "夜场", "动物"], "type": "亲子活动"},
    {"name": "虎鲸造浪节", "venue": "上海海昌海洋公园", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "连续66天夜场，围绕4大戏水、7大剧目升级、奥特曼60周年庆、烟花盛典等特色活动，7月11日-8月23日更有虎鲸造浪音乐节。", "source": "上海本地宝", "highlights": ["海洋公园", "造浪节", "烟花"], "type": "演出"},
    {"name": "泰浪狂欢节", "venue": "上海玛雅海滩水公园", "city": "shanghai", "district": "松江区", "start_date": "2026-07-05", "end_date": "2026-08-31", "fee": "收费", "description": "沪上首个'水上泼水音乐节'，包含泰浪超级水战、枪王之王争霸赛、撒泼大作战等主题活动，开放时间延长至22:00。", "source": "上海本地宝", "highlights": ["水公园", "泼水", "音乐节"], "type": "演出"},
    {"name": "千金之家马王堆汉墓展", "venue": "上海美术馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-03", "end_date": "2026-10-07", "fee": "收费", "description": "荟萃马王堆出土珍宝，数件限制出境国宝同台亮相，回溯辛追侯府日常起居，品鉴西汉世家独有的生活格调。", "source": "上海本地宝", "highlights": ["马王堆", "汉墓", "国宝"], "type": "展览"},
    {"name": "布里奇曼名画奇旅", "venue": "上海美术馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "收费", "description": "国内首个布里奇曼专属艺术空间展览，依托沉浸式光影场景、专业画作拆解、趣味艺术互动装置，帮助孩子轻松学习素描、构图等基础艺术知识。", "source": "上海本地宝", "highlights": ["艺术", "光影", "互动"], "type": "展览"},
    {"name": "艺起童年儿童美术展", "venue": "上海美术馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "中国儿童美术百年巡展，展出二百余件精品作品，涵盖原创书画、插画原稿、经典美术片影像等。", "source": "上海本地宝", "highlights": ["儿童美术", "百年", "展览"], "type": "展览"},
    {"name": "上海少儿优秀美术作品展", "venue": "马利美术馆", "city": "shanghai", "district": "静安区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "150件（组）少儿美术作品展出，适合带孩子来一场艺术启蒙。", "source": "上海本地宝", "highlights": ["少儿美术", "展览", "艺术"], "type": "展览"},
    {"name": "阅万象暑期阅读季", "venue": "上海图书馆", "city": "shanghai", "district": "徐汇区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "涵盖主题活动、故事剧场、少儿讲座、创艺工坊、展览展示、志愿活动等七大板块，共计推出1000余项阅读活动。", "source": "上海本地宝", "highlights": ["阅读", "暑期", "活动"], "type": "讲座"},
    {"name": "未来科技大奖文献展", "venue": "上海科技馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "全景呈现中国科学家世界级研究成果，首次展出珍贵手稿与实物展品，见证中国科学从追赶到引领的非凡历程。", "source": "上海本地宝", "highlights": ["科技", "大奖", "展览"], "type": "展览"},
    {"name": "China白主题临展", "venue": "上海世界技能博物馆", "city": "shanghai", "district": "杨浦区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "以五大主题展品矩阵为核心，融入捏、塑、雕、刻、彩绘等传统工艺技艺展示，结合AI+、艺术+互动体验。", "source": "上海本地宝", "highlights": ["技能", "工艺", "互动"], "type": "展览"},
    {"name": "博物馆奇妙夜", "venue": "上海自然博物馆", "city": "shanghai", "district": "静安区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "每周六延时开放至20:00，四维影院同步开放，体验夜间博物馆的独特魅力。", "source": "上海本地宝", "highlights": ["自然博物馆", "夜场", "四维影院"], "type": "亲子活动"},
    {"name": "上海天文馆奇妙夜", "venue": "上海天文馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-08", "end_date": "2026-08-31", "fee": "收费", "description": "每周六17:00-20:00开放夜场，球幕影院开放，科普集市、星光音乐会、天文桌游等精彩活动。", "source": "上海本地宝", "highlights": ["天文馆", "夜场", "星空"], "type": "亲子活动"},
    {"name": "烹饪宇宙科学桌游", "venue": "上海天文馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "通过打出手牌，收集'食材'，烹饪'星星'，一款寓教于乐的天文科普桌游。", "source": "上海本地宝", "highlights": ["桌游", "天文", "科普"], "type": "亲子活动"},
    {"name": "保利艺夏演出季", "venue": "上海保利大剧院", "city": "shanghai", "district": "嘉定区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "推出谍战话剧《夜行者》、'打开艺术之门'系列儿童剧目包括芭蕾、皮影、音乐会等贯穿整个暑假。", "source": "上海本地宝", "highlights": ["演出季", "儿童剧", "艺术"], "type": "演出"},
    {"name": "EV音乐乐园", "venue": "上海欢乐谷", "city": "shanghai", "district": "松江区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "主舞台'银河嗨唱中心'，每周六人气大咖空降开启音浪狂潮。", "source": "上海本地宝", "highlights": ["音乐", "乐园", "演出"], "type": "演出"},
    {"name": "非遗手作工坊", "venue": "上海博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "结合美洲古代文明大展，开设文物互动体验、创意手工创作等趣味亲子环节。", "source": "上海本地宝", "highlights": ["手工", "非遗", "亲子"], "type": "亲子活动"},
    # ========== 杭州活动 ==========
    {"name": "爱丽丝梦游仙境芭蕾舞剧", "venue": "杭州大剧院", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-15", "end_date": "2026-07-15", "fee": "需购票", "description": "俄罗斯国宝级芭蕾舞剧，150年风靡全球的经典IP，用芭蕾足尖重新书写奇幻！", "source": "杭州本地宝", "highlights": ["芭蕾舞", "爱丽丝", "奇幻"], "type": "演出"},
    {"name": "八十天环游地球舞台剧", "venue": "金沙湖大剧院", "city": "hangzhou", "district": "钱塘区", "start_date": "2026-07-18", "end_date": "2026-07-18", "fee": "需购票", "description": "改编自儒勒·凡尔纳同名科幻冒险小说，生动再现19世纪英国绅士菲利亚·福格挑战八十天环游地球的传奇故事。", "source": "杭州本地宝", "highlights": ["舞台剧", "环游地球", "冒险"], "type": "演出"},
    {"name": "柴可夫斯基钢琴独奏音乐会", "venue": "杭州临平大剧院", "city": "hangzhou", "district": "临平区", "start_date": "2026-07-24", "end_date": "2026-07-24", "fee": "需购票", "description": "鲁超老师带孩子走进柴可夫斯基的童话世界，以不同时期、不同风格的钢琴小品为媒介，传递地道的俄罗斯风情。", "source": "杭州本地宝", "highlights": ["钢琴", "柴可夫斯基", "音乐会"], "type": "演出"},
    {"name": "寻找声音的耳朵音乐剧", "venue": "小百花越剧场", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-25", "end_date": "2026-07-26", "fee": "需购票", "description": "男孩小聃带着'魔法'瓶子和一双纯真空灵的耳朵转学到市重点小学，经历竞争、攀比和环境反差的故事。", "source": "杭州本地宝", "highlights": ["音乐剧", "成长", "声音"], "type": "演出"},
    {"name": "海王星飞船儿童剧", "venue": "杭州临平大剧院", "city": "hangzhou", "district": "临平区", "start_date": "2026-08-06", "end_date": "2026-08-06", "fee": "需购票", "description": "帆船奥运冠军剧作指导国内首部帆船舞台剧演出，献给孩子们的第一堂海洋科普课。", "source": "杭州本地宝", "highlights": ["儿童剧", "帆船", "海洋"], "type": "演出"},
    {"name": "航天奇妙夜儿童剧", "venue": "杭州临平大剧院", "city": "hangzhou", "district": "临平区", "start_date": "2026-08-07", "end_date": "2026-08-07", "fee": "需购票", "description": "大型沉浸式实验科普剧，涵盖近百个航空航天知识点，通过寓教于乐的方式生动形象地科普航天知识。", "source": "杭州本地宝", "highlights": ["航天", "科普", "儿童剧"], "type": "演出"},
    {"name": "科学SHOW亲子科学剧", "venue": "杭州临平大剧院", "city": "hangzhou", "district": "临平区", "start_date": "2026-08-09", "end_date": "2026-08-09", "fee": "需购票", "description": "对于5-13岁小朋友学习科普知识，与家长共同体验互动的科学互动亲子剧。", "source": "杭州本地宝", "highlights": ["科学", "亲子", "互动"], "type": "演出"},
    {"name": "时光历险记音乐剧", "venue": "杭州临平大剧院", "city": "hangzhou", "district": "临平区", "start_date": "2026-08-11", "end_date": "2026-08-11", "fee": "需购票", "description": "聚焦时间、记忆与爱的主题，借兄妹冒险的奇幻经历，探讨与过往遗憾和解的命题。", "source": "杭州本地宝", "highlights": ["音乐剧", "时光", "冒险"], "type": "演出"},
    {"name": "小王子舞台剧", "venue": "杭州大剧院", "city": "hangzhou", "district": "上城区", "start_date": "2026-08-15", "end_date": "2026-08-15", "fee": "需购票", "description": "经典改编，小王子居住在B612小行星上，因为与玫瑰花的一次争吵，开始了穿越星际的冒险。", "source": "杭州本地宝", "highlights": ["小王子", "舞台剧", "童话"], "type": "演出"},
    {"name": "太平年天下同宁交互艺术展", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "融合实物文物、数字展陈与沉浸式演出，展现吴越文化的独特魅力。", "source": "杭州本地宝", "highlights": ["吴越", "数字展陈", "沉浸式"], "type": "展览"},
    {"name": "一剑千年吴越国纪录片特展", "venue": "钱王祠", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-10-08", "fee": "免费", "description": "展出影片海报、原创服饰道具手稿、书法篆刻作品等，展示吴越国历史文化。", "source": "杭州本地宝", "highlights": ["吴越国", "纪录片", "展览"], "type": "展览"},
    {"name": "钱氏今生实景音乐剧", "venue": "钱王祠", "city": "hangzhou", "district": "上城区", "start_date": "2026-06-24", "end_date": "2026-10-08", "fee": "收费", "description": "以钱王浚湖治水功绩、《钱氏家训》传承为双主线，依托古祠实景演绎吴越文化与家风内涵。", "source": "杭州本地宝", "highlights": ["实景演出", "吴越文化", "家训"], "type": "演出"},
    {"name": "湿地洞天沉浸式体验", "venue": "中国湿地博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "6米动态数字瀑布+32.5米180°巨幕，沉浸式穿梭湿地秘境，剪影大片随手拍。", "source": "杭州本地宝", "highlights": ["湿地", "沉浸式", "数字"], "type": "展览"},
    {"name": "湿地万象厅", "venue": "中国湿地博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "200余种湿地动植物标本，近距离认识麋鹿、丹顶鹤，还有趣味气味互动体验。", "source": "杭州本地宝", "highlights": ["湿地", "标本", "互动"], "type": "展览"},
    {"name": "只此西溪厅", "venue": "中国湿地博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "微缩西溪全景沙盘，复原西溪水乡生活，击鼓赛龙舟互动装置小朋友超爱。", "source": "杭州本地宝", "highlights": ["西溪", "沙盘", "互动"], "type": "展览"},
    {"name": "良渚玉琮王展览", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "五千年前国宝重磅亮相，良渚玉琮王、越王者旨於睗剑等珍贵文物展出。", "source": "杭州本地宝", "highlights": ["良渚", "玉琮", "国宝"], "type": "展览"},
    {"name": "万工轿展览", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "被誉为天下第一轿，朱金木雕繁复华丽，必打卡国宝。", "source": "杭州本地宝", "highlights": ["万工轿", "朱金木雕", "国宝"], "type": "展览"},
    {"name": "富春山居数字展厅", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "流动水墨长卷，窗边玻璃廊道观景绝佳，沉浸式体验富春山居图的意境。", "source": "杭州本地宝", "highlights": ["富春山居", "数字", "沉浸式"], "type": "展览"},
    {"name": "科技研学线路", "venue": "阿里巴巴全球总部", "city": "hangzhou", "district": "余杭区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "串联阿里巴巴全球总部、机器人小镇、梦想小镇等核心科创地标，覆盖人工智能、数字经济、航空航天、智能制造等热门领域。", "source": "杭州本地宝", "highlights": ["科技", "研学", "阿里"], "type": "亲子活动"},
    {"name": "宋韵非遗研学之旅", "venue": "上城坊巷", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "上城'宋韵非遗·上城坊巷'研学之旅，体验宋代文化与非遗技艺。", "source": "杭州本地宝", "highlights": ["宋韵", "非遗", "研学"], "type": "亲子活动"},
    {"name": "运河百艺研学之旅", "venue": "拱墅运河", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "拱墅'运河百艺·薪火传承'非遗研学之旅，感受运河文化与传统技艺。", "source": "杭州本地宝", "highlights": ["运河", "非遗", "研学"], "type": "亲子活动"},
    {"name": "杭图有约读书会", "venue": "杭州图书馆", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "定期举办'杭图有约'主题读书会，邀请名家学者分享阅读心得。", "source": "杭州本地宝", "highlights": ["阅读", "读书会", "名家"], "type": "讲座"},
    {"name": "小书虫漫游记", "venue": "杭州图书馆少儿分馆", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "联动全市400余家杭州书房，开展暑期阅读活动。", "source": "杭州本地宝", "highlights": ["阅读", "少儿", "书房"], "type": "亲子活动"},
    {"name": "第34届全国书博会", "venue": "杭州国际博览中心", "city": "hangzhou", "district": "萧山区", "start_date": "2026-07-24", "end_date": "2026-07-27", "fee": "免费", "description": "设有八大展厅、九大专题展览、十一项重点活动、发放300万元惠民购书券。", "source": "杭州本地宝", "highlights": ["书博会", "展览", "惠民"], "type": "展览"},
    {"name": "天目未来谷水世界", "venue": "临安天目未来谷", "city": "hangzhou", "district": "临安区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "131.4米长三角最高摩天轮为网红地标，搭配多款超长超高水滑道。", "source": "杭州本地宝", "highlights": ["水世界", "摩天轮", "亲子"], "type": "演出"},
    {"name": "平行世界水乐园", "venue": "临平平行世界", "city": "hangzhou", "district": "临平区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "超30000㎡室内外游玩空间，配备国内首创3D沉浸式造浪池、浙江首座水磁弹射过山车。", "source": "杭州本地宝", "highlights": ["水乐园", "3D造浪池", "过山车"], "type": "演出"},
    {"name": "开元森泊水世界", "venue": "桐庐开元森泊", "city": "hangzhou", "district": "桐庐县", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "9200㎡恒温室内区域，龙卷风组合滑道、激流河等项目人气火爆。", "source": "杭州本地宝", "highlights": ["水乐园", "恒温", "亲子"], "type": "演出"},
    {"name": "杭州奇妙夜", "venue": "天目里", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-03", "end_date": "2026-10-10", "fee": "免费", "description": "构建'3大夜主场+10大主题产品+全域联动营销'夜游格局，举办9场主题音乐会。", "source": "杭州本地宝", "highlights": ["奇妙夜", "音乐会", "夜游"], "type": "演出"},
    {"name": "非遗魔术秀", "venue": "浙江省非遗馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "6:30PM非遗魔术秀，感受非遗技艺的神奇魅力。", "source": "杭州本地宝", "highlights": ["非遗", "魔术", "夜场"], "type": "演出"},
    {"name": "皮影灯影秀", "venue": "浙江省非遗馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "7:00PM皮影灯影秀在3楼剧场舞台上演，体验传统皮影艺术。", "source": "杭州本地宝", "highlights": ["皮影", "灯影", "非遗"], "type": "演出"},
    {"name": "免费拓印体验", "venue": "浙江省非遗馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "负一楼手工区提供免费宣纸拓印和皮影戏体验。", "source": "杭州本地宝", "highlights": ["拓印", "皮影", "手工"], "type": "亲子活动"},
    {"name": "自然博物馆暑期活动", "venue": "浙江自然博物院", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "化石挖掘体验、火山爆发科学实验秀、AR恐龙互动、夜间科普课堂等十项研学课程。", "source": "杭州本地宝", "highlights": ["自然博物馆", "化石", "科普"], "type": "亲子活动"},
    {"name": "科技馆科学舞台剧", "venue": "浙江省科技馆", "city": "hangzhou", "district": "下城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "暑期每日定时有科学舞台剧，机器人表演、航天模拟器、水力实验、力学游戏等互动体验。", "source": "杭州本地宝", "highlights": ["科技馆", "科学剧", "互动"], "type": "演出"},
    # ========== 补充更多活动 ==========
    # 北京补充
    {"name": "北京天文馆暑期观测", "venue": "北京天文馆", "city": "beijing", "district": "西城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "暑期星空观测活动，通过专业天文望远镜观测太阳黑子、月球环形山等天体。", "source": "北京本地宝", "highlights": ["天文", "观测", "暑期"], "type": "亲子活动"},
    {"name": "北京自然博物馆夜宿", "venue": "北京自然博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "夜间在博物馆内露营，体验恐龙化石展厅的奇妙夜。", "source": "北京本地宝", "highlights": ["夜宿", "博物馆", "恐龙"], "type": "亲子活动"},
    {"name": "北京植物园自然课堂", "venue": "北京植物园", "city": "beijing", "district": "海淀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "每周六日举办自然课堂，植物识别、昆虫观察、生态保护等主题活动。", "source": "北京本地宝", "highlights": ["植物园", "自然课堂", "亲子"], "type": "亲子活动"},
    # 广州补充
    {"name": "广州科学中心科普日", "venue": "广州科学中心", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "暑期科普日活动，机器人表演、科学实验秀、互动体验等。", "source": "广州本地宝", "highlights": ["科学中心", "科普", "互动"], "type": "亲子活动"},
    {"name": "越秀公园亲子定向", "venue": "越秀公园", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "亲子定向越野活动，在公园内完成趣味任务。", "source": "广州本地宝", "highlights": ["定向", "公园", "亲子"], "type": "亲子活动"},
    # 上海补充
    {"name": "上海科技馆科学之夜", "venue": "上海科技馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "每周五晚开放至21:00，体验不一样的科技馆奇妙夜。", "source": "上海本地宝", "highlights": ["科技馆", "夜场", "科学"], "type": "亲子活动"},
    {"name": "上海野生动物园夜宿", "venue": "上海野生动物园", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "夜间在野生动物园内露营，近距离观察动物夜间行为。", "source": "上海本地宝", "highlights": ["动物园", "夜宿", "亲子"], "type": "亲子活动"},
    # 杭州补充
    {"name": "杭州动物园暑期活动", "venue": "杭州动物园", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "动物科普讲解、喂食体验、亲子互动等暑期活动。", "source": "杭州本地宝", "highlights": ["动物园", "科普", "亲子"], "type": "亲子活动"},
    {"name": "西溪湿地夏令营", "venue": "西溪国家湿地公园", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "湿地生态探索、动植物观察、自然笔记等夏令营活动。", "source": "杭州本地宝", "highlights": ["湿地", "夏令营", "生态"], "type": "亲子活动"},
]

if __name__ == '__main__':
    if not os.path.exists(DATA_FILE):
        print(f"文件 {DATA_FILE} 不存在！")
        exit(1)
    
    with open(DATA_FILE, 'r', encoding='utf-8') as f:
        exhibitions = json.load(f)
    
    existing_names = {e['name'] for e in exhibitions}
    added_count = 0
    
    for activity in new_activities:
        if activity['name'] not in existing_names:
            exhibitions.append(activity)
            print(f"添加: {activity['name']} ({activity['city']})")
            added_count += 1
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(exhibitions, f, ensure_ascii=False, indent=2)
    
    print(f"\n共添加 {added_count} 个活动")
    
    city_counts = {}
    for e in exhibitions:
        city_counts[e['city']] = city_counts.get(e['city'], 0) + 1
    print(f"\n各城市活动数量:")
    for city, count in city_counts.items():
        print(f"  {city}: {count}")