import json

new_venues = [
    {
        "name": "广州融创文旅城",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区花城大道",
        "transport": "公交",
        "fee": "收费",
        "description": "大型文旅综合体，有融创乐园、融创茂等设施。",
        "official_url": "",
        "highlights": ["融创乐园", "文旅"]
    },
    {
        "name": "广州花都融创乐园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区花城大道",
        "transport": "公交",
        "fee": "收费",
        "description": "大型主题乐园，有游乐设施和表演。",
        "official_url": "",
        "highlights": ["主题乐园", "游乐"]
    },
    {
        "name": "广州花都融创雪世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区花城大道",
        "transport": "公交",
        "fee": "收费",
        "description": "室内滑雪场，可体验滑雪和冰雪世界。",
        "official_url": "",
        "highlights": ["室内滑雪", "冰雪"]
    },
    {
        "name": "广州花都融创水世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区花城大道",
        "transport": "公交",
        "fee": "收费",
        "description": "室内水上乐园，有各种水上项目。",
        "official_url": "",
        "highlights": ["水上乐园", "室内"]
    },
    {
        "name": "广州花都融创体育世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "体育中心",
        "address": "花都区花城大道",
        "transport": "公交",
        "fee": "收费",
        "description": "体育娱乐综合体，有篮球、足球、卡丁车等项目。",
        "official_url": "",
        "highlights": ["体育", "卡丁车"]
    },
    {
        "name": "广州从化溪头村",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "从化区",
        "type": "公园",
        "address": "从化区良口镇",
        "transport": "自驾",
        "fee": "免费",
        "description": "广州最美乡村之一，有溪流和田园风光。",
        "official_url": "",
        "highlights": ["乡村", "溪流", "免费"]
    },
    {
        "name": "广州从化流溪河国家森林公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "从化区",
        "type": "公园",
        "address": "从化区良口镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "有森林、湖泊、瀑布的自然景区。",
        "official_url": "",
        "highlights": ["森林", "湖泊", "瀑布"]
    },
    {
        "name": "广州从化碧水湾温泉",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "从化区",
        "type": "公园",
        "address": "从化区良口镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "著名的温泉度假区，有各种温泉池。",
        "official_url": "",
        "highlights": ["温泉", "度假"]
    },
    {
        "name": "广州增城白水寨",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "增城区",
        "type": "公园",
        "address": "增城区派潭镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "有落差428.5米的白水仙瀑，是广东最大的瀑布。",
        "official_url": "",
        "highlights": ["瀑布", "登山"]
    },
    {
        "name": "广州增城正果老街",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "增城区",
        "type": "文化中心",
        "address": "增城区正果镇",
        "transport": "自驾",
        "fee": "免费",
        "description": "有古建筑和美食的老街，适合游玩和品尝。",
        "official_url": "",
        "highlights": ["老街", "美食", "免费"]
    },
    {
        "name": "广州南沙湿地公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "南沙区",
        "type": "公园",
        "address": "南沙区万顷沙镇",
        "transport": "公交",
        "fee": "收费",
        "description": "大型湿地公园，有红树林和候鸟栖息地。",
        "official_url": "",
        "highlights": ["湿地", "候鸟"]
    },
    {
        "name": "广州南沙天后宫",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "南沙区",
        "type": "文化中心",
        "address": "南沙区大角山",
        "transport": "公交",
        "fee": "收费",
        "description": "东南亚最大的妈祖庙，有古建筑和海景。",
        "official_url": "",
        "highlights": ["妈祖庙", "海景"]
    },
    {
        "name": "上海世纪公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区锦绣路1001号",
        "transport": "地铁2号线世纪公园站",
        "fee": "免费",
        "description": "上海大型城市公园，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "上海陆家嘴中心绿地",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区陆家嘴环路",
        "transport": "地铁2号线陆家嘴站",
        "fee": "免费",
        "description": "陆家嘴金融中心的绿地，有草坪和城市景观。",
        "official_url": "",
        "highlights": ["绿地", "城市景观", "免费"]
    },
    {
        "name": "上海滨江森林公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区高桥镇",
        "transport": "公交",
        "fee": "免费",
        "description": "位于长江口的森林公园，有森林和江景。",
        "official_url": "",
        "highlights": ["森林", "江景", "免费"]
    },
    {
        "name": "上海南汇嘴观海公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区南汇新城",
        "transport": "公交",
        "fee": "免费",
        "description": "位于东海之滨的公园，可观赏大海和日出。",
        "official_url": "",
        "highlights": ["观海", "日出", "免费"]
    },
    {
        "name": "上海滴水湖",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区南汇新城",
        "transport": "地铁16号线滴水湖站",
        "fee": "免费",
        "description": "大型人工湖，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "上海临港新城",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区南汇新城",
        "transport": "地铁16号线滴水湖站",
        "fee": "免费",
        "description": "上海的新兴城区，有现代化建筑和城市景观。",
        "official_url": "",
        "highlights": ["现代化", "城市景观", "免费"]
    },
    {
        "name": "上海海洋大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区沪城环路",
        "transport": "地铁16号线临港大道站",
        "fee": "免费",
        "description": "上海海洋大学临港校区，有海洋博物馆和校园风光。",
        "official_url": "",
        "highlights": ["海洋大学", "博物馆"]
    },
    {
        "name": "上海上海大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "宝山区",
        "type": "文化中心",
        "address": "宝山区上大路",
        "transport": "地铁7号线上海大学站",
        "fee": "免费",
        "description": "上海大学宝山校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "上海同济大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "杨浦区",
        "type": "文化中心",
        "address": "杨浦区四平路",
        "transport": "地铁10号线同济大学站",
        "fee": "免费",
        "description": "同济大学四平路校区，有樱花和校园风光。",
        "official_url": "",
        "highlights": ["大学", "樱花", "校园"]
    },
    {
        "name": "上海复旦大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "杨浦区",
        "type": "文化中心",
        "address": "杨浦区邯郸路",
        "transport": "地铁10号线国权路站",
        "fee": "免费",
        "description": "复旦大学邯郸校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "上海交通大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "文化中心",
        "address": "徐汇区华山路",
        "transport": "地铁10号线交通大学站",
        "fee": "免费",
        "description": "上海交通大学徐汇校区，有历史建筑和校园风光。",
        "official_url": "",
        "highlights": ["大学", "历史建筑", "校园"]
    },
    {
        "name": "上海华东师范大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "闵行区",
        "type": "文化中心",
        "address": "闵行区东川路",
        "transport": "地铁5号线东川路站",
        "fee": "免费",
        "description": "华东师范大学闵行校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "上海华东理工大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "文化中心",
        "address": "徐汇区梅陇路",
        "transport": "地铁15号线华东理工大学站",
        "fee": "免费",
        "description": "华东理工大学徐汇校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "上海上海师范大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "文化中心",
        "address": "徐汇区桂林路",
        "transport": "地铁9号线桂林路站",
        "fee": "免费",
        "description": "上海师范大学徐汇校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "上海上海理工大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "杨浦区",
        "type": "文化中心",
        "address": "杨浦区军工路",
        "transport": "公交",
        "fee": "免费",
        "description": "上海理工大学军工路校区，有历史建筑和校园风光。",
        "official_url": "",
        "highlights": ["大学", "历史建筑", "校园"]
    },
    {
        "name": "上海东华大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "文化中心",
        "address": "松江区人民北路",
        "transport": "地铁9号线松江大学城站",
        "fee": "免费",
        "description": "东华大学松江校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "上海上海工程技术大学",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "文化中心",
        "address": "松江区龙腾路",
        "transport": "地铁9号线松江大学城站",
        "fee": "免费",
        "description": "上海工程技术大学松江校区，有校园风光和文化设施。",
        "official_url": "",
        "highlights": ["大学", "校园", "文化"]
    },
    {
        "name": "杭州西湖音乐喷泉",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区湖滨",
        "transport": "地铁1号线龙翔桥站",
        "fee": "免费",
        "description": "西湖边的音乐喷泉，每晚有灯光和音乐表演。",
        "official_url": "",
        "highlights": ["音乐喷泉", "灯光表演", "免费"]
    },
    {
        "name": "杭州运河文化广场",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区金华路",
        "transport": "地铁5号线大运河站",
        "fee": "免费",
        "description": "运河边的文化广场，有博物馆和城市景观。",
        "official_url": "",
        "highlights": ["运河", "文化", "免费"]
    },
    {
        "name": "杭州运河夜游",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区运河",
        "transport": "地铁5号线大运河站",
        "fee": "收费",
        "description": "运河夜游，可观赏运河两岸夜景。",
        "official_url": "",
        "highlights": ["夜游", "运河", "夜景"]
    },
    {
        "name": "杭州运河游船",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区运河",
        "transport": "地铁5号线大运河站",
        "fee": "收费",
        "description": "运河游船，可游览运河两岸风光。",
        "official_url": "",
        "highlights": ["游船", "运河"]
    },
    {
        "name": "杭州西溪湿地摇橹船",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西溪湿地",
        "transport": "地铁3号线西溪湿地南站",
        "fee": "收费",
        "description": "西溪湿地摇橹船，可体验湿地风光。",
        "official_url": "",
        "highlights": ["摇橹船", "湿地"]
    },
    {
        "name": "杭州西溪湿地龙舟赛",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区西溪湿地",
        "transport": "地铁3号线西溪湿地南站",
        "fee": "免费",
        "description": "西溪湿地龙舟赛，每年端午节举办。",
        "official_url": "",
        "highlights": ["龙舟赛", "端午节", "免费"]
    },
    {
        "name": "杭州西溪湿地植物园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "科普馆",
        "address": "西湖区西溪湿地",
        "transport": "地铁3号线西溪湿地南站",
        "fee": "免费",
        "description": "西溪湿地内的植物园，展示各种湿地植物。",
        "official_url": "",
        "highlights": ["植物园", "湿地植物", "免费"]
    },
    {
        "name": "杭州西溪湿地博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区西溪湿地",
        "transport": "地铁3号线西溪湿地南站",
        "fee": "免费",
        "description": "展示西溪湿地历史和生态的博物馆。",
        "official_url": "",
        "highlights": ["博物馆", "湿地", "免费"]
    },
    {
        "name": "杭州湘湖游船",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "公园",
        "address": "萧山区湘湖",
        "transport": "地铁1号线湘湖站",
        "fee": "收费",
        "description": "湘湖游船，可游览湘湖风光。",
        "official_url": "",
        "highlights": ["游船", "湘湖"]
    },
    {
        "name": "杭州湘湖音乐喷泉",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "文化中心",
        "address": "萧山区湘湖",
        "transport": "地铁1号线湘湖站",
        "fee": "免费",
        "description": "湘湖的音乐喷泉，有灯光和音乐表演。",
        "official_url": "",
        "highlights": ["音乐喷泉", "灯光", "免费"]
    },
    {
        "name": "杭州极地海洋世界海豚表演",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "科普馆",
        "address": "萧山区湘湖路",
        "transport": "地铁1号线湘湖站",
        "fee": "收费",
        "description": "极地海洋世界的海豚表演，精彩有趣。",
        "official_url": "",
        "highlights": ["海豚表演", "精彩"]
    },
    {
        "name": "杭州极地海洋世界白鲸表演",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "科普馆",
        "address": "萧山区湘湖路",
        "transport": "地铁1号线湘湖站",
        "fee": "收费",
        "description": "极地海洋世界的白鲸表演，温馨感人。",
        "official_url": "",
        "highlights": ["白鲸表演", "温馨"]
    },
    {
        "name": "杭州奥体中心体育场",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "体育中心",
        "address": "滨江区江南大道",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "杭州奥体中心的主体育场，举办大型体育赛事和演唱会。",
        "official_url": "",
        "highlights": ["体育赛事", "演唱会"]
    },
    {
        "name": "杭州奥体中心游泳馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "体育中心",
        "address": "滨江区江南大道",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "杭州奥体中心的游泳馆，有游泳比赛和培训。",
        "official_url": "",
        "highlights": ["游泳", "比赛"]
    },
    {
        "name": "杭州奥体中心网球中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "体育中心",
        "address": "滨江区江南大道",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "杭州奥体中心的网球中心，举办网球比赛和培训。",
        "official_url": "",
        "highlights": ["网球", "比赛"]
    },
    {
        "name": "杭州梦想小镇创业大街",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "文化中心",
        "address": "余杭区文一西路",
        "transport": "地铁5号线良睦路站",
        "fee": "免费",
        "description": "梦想小镇的创业大街，有创业咖啡馆和展示中心。",
        "official_url": "",
        "highlights": ["创业", "咖啡馆", "免费"]
    },
    {
        "name": "杭州未来科技城梦想小镇",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "文化中心",
        "address": "余杭区文一西路",
        "transport": "地铁5号线良睦路站",
        "fee": "免费",
        "description": "未来科技城的梦想小镇，有创业孵化和文化设施。",
        "official_url": "",
        "highlights": ["创业", "科技", "免费"]
    },
    {
        "name": "杭州未来科技城学术交流中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "会展中心",
        "address": "余杭区文一西路",
        "transport": "地铁5号线良睦路站",
        "fee": "收费",
        "description": "未来科技城的学术交流中心，举办学术会议和展览。",
        "official_url": "",
        "highlights": ["学术会议", "展览"]
    },
    {
        "name": "杭州未来科技城海创园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "文化中心",
        "address": "余杭区文一西路",
        "transport": "地铁5号线良睦路站",
        "fee": "免费",
        "description": "未来科技城的海创园，有创业孵化和科技展示。",
        "official_url": "",
        "highlights": ["创业", "科技", "免费"]
    },
    {
        "name": "杭州未来科技城人才公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "公园",
        "address": "余杭区文一西路",
        "transport": "地铁5号线良睦路站",
        "fee": "免费",
        "description": "未来科技城的人才公园，有休闲设施和景观。",
        "official_url": "",
        "highlights": ["公园", "休闲", "免费"]
    },
    {
        "name": "杭州临平新城体育公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "临平区",
        "type": "公园",
        "address": "临平区",
        "transport": "地铁9号线临平站",
        "fee": "免费",
        "description": "临平新城的体育公园，有运动设施和休闲空间。",
        "official_url": "",
        "highlights": ["体育", "休闲", "免费"]
    },
    {
        "name": "杭州临平新城文化艺术中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "临平区",
        "type": "文化中心",
        "address": "临平区",
        "transport": "地铁9号线临平站",
        "fee": "免费",
        "description": "临平新城的文化艺术中心，有展览和演出。",
        "official_url": "",
        "highlights": ["文化艺术", "展览", "免费"]
    },
    {
        "name": "杭州临平新城市民广场",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "临平区",
        "type": "文化中心",
        "address": "临平区",
        "transport": "地铁9号线临平站",
        "fee": "免费",
        "description": "临平新城的市民广场，有休闲设施和城市景观。",
        "official_url": "",
        "highlights": ["广场", "休闲", "免费"]
    },
    {
        "name": "杭州九堡大桥公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "公园",
        "address": "江干区九堡大桥",
        "transport": "公交",
        "fee": "免费",
        "description": "九堡大桥附近的公园，有江景和休闲设施。",
        "official_url": "",
        "highlights": ["江景", "休闲", "免费"]
    },
    {
        "name": "杭州钱江新城灯光秀",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "文化中心",
        "address": "江干区钱江新城",
        "transport": "地铁4号线市民中心站",
        "fee": "免费",
        "description": "钱江新城的灯光秀，每晚有灯光表演。",
        "official_url": "",
        "highlights": ["灯光秀", "夜景", "免费"]
    },
    {
        "name": "杭州城市阳台灯光秀",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "文化中心",
        "address": "江干区城市阳台",
        "transport": "地铁4号线市民中心站",
        "fee": "免费",
        "description": "城市阳台的灯光秀，可观赏钱江新城夜景。",
        "official_url": "",
        "highlights": ["灯光秀", "夜景", "免费"]
    },
    {
        "name": "杭州大剧院歌剧厅",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "演出场馆",
        "address": "江干区新业路",
        "transport": "地铁4号线市民中心站",
        "fee": "收费",
        "description": "杭州大剧院的歌剧厅，举办歌剧和音乐会。",
        "official_url": "",
        "highlights": ["歌剧", "音乐会"]
    },
    {
        "name": "杭州大剧院音乐厅",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "演出场馆",
        "address": "江干区新业路",
        "transport": "地铁4号线市民中心站",
        "fee": "收费",
        "description": "杭州大剧院的音乐厅，举办交响乐和室内乐音乐会。",
        "official_url": "",
        "highlights": ["交响乐", "室内乐"]
    },
    {
        "name": "杭州国际会议中心大剧场",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "演出场馆",
        "address": "江干区新业路",
        "transport": "地铁4号线市民中心站",
        "fee": "收费",
        "description": "杭州国际会议中心的大剧场，举办大型演出和会议。",
        "official_url": "",
        "highlights": ["演出", "会议"]
    },
    {
        "name": "杭州奥体博览城网球中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "体育中心",
        "address": "滨江区江南大道",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "奥体博览城的网球中心，举办网球比赛和培训。",
        "official_url": "",
        "highlights": ["网球", "比赛"]
    },
    {
        "name": "杭州奥体博览城游泳馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "体育中心",
        "address": "滨江区江南大道",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "奥体博览城的游泳馆，有游泳比赛和培训。",
        "official_url": "",
        "highlights": ["游泳", "比赛"]
    },
    {
        "name": "杭州白马湖国际会展中心展览厅",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "会展中心",
        "address": "滨江区长江南路",
        "transport": "公交",
        "fee": "收费",
        "description": "白马湖国际会展中心的展览厅，举办各种展览。",
        "official_url": "",
        "highlights": ["展览", "会展"]
    },
    {
        "name": "杭州之江文化中心图书馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "图书馆",
        "address": "西湖区之江路",
        "transport": "公交",
        "fee": "免费",
        "description": "之江文化中心的图书馆，有丰富的馆藏和阅读空间。",
        "official_url": "",
        "highlights": ["图书馆", "阅读", "免费"]
    },
    {
        "name": "杭州之江文化中心博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区之江路",
        "transport": "公交",
        "fee": "免费",
        "description": "之江文化中心的博物馆，展示各种文物和艺术品。",
        "official_url": "",
        "highlights": ["博物馆", "文物", "免费"]
    },
    {
        "name": "杭州之江文化中心美术馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "美术馆",
        "address": "西湖区之江路",
        "transport": "公交",
        "fee": "免费",
        "description": "之江文化中心的美术馆，展示各种美术作品。",
        "official_url": "",
        "highlights": ["美术馆", "美术作品", "免费"]
    },
    {
        "name": "杭州之江文化中心科技馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "科技馆",
        "address": "西湖区之江路",
        "transport": "公交",
        "fee": "免费",
        "description": "之江文化中心的科技馆，有互动体验和科普展览。",
        "official_url": "",
        "highlights": ["科技馆", "互动体验", "免费"]
    },
    {
        "name": "杭州文学馆展览厅",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区",
        "transport": "公交",
        "fee": "免费",
        "description": "杭州文学馆的展览厅，展示杭州文学历史和作品。",
        "official_url": "",
        "highlights": ["文学", "展览", "免费"]
    },
    {
        "name": "杭州文学馆阅读室",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "图书馆",
        "address": "西湖区",
        "transport": "公交",
        "fee": "免费",
        "description": "杭州文学馆的阅读室，有丰富的文学书籍和阅读空间。",
        "official_url": "",
        "highlights": ["阅读", "文学", "免费"]
    },
    {
        "name": "北京延庆奥林匹克园区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "延庆区",
        "type": "体育中心",
        "address": "延庆区",
        "transport": "公交",
        "fee": "收费",
        "description": "2022年冬奥会举办地，有滑雪和冰雪项目。",
        "official_url": "",
        "highlights": ["冬奥会", "滑雪", "冰雪"]
    },
    {
        "name": "北京世园公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "延庆区",
        "type": "公园",
        "address": "延庆区",
        "transport": "公交",
        "fee": "收费",
        "description": "2019年世界园艺博览会举办地，有各种花卉和景观。",
        "official_url": "",
        "highlights": ["园艺", "花卉", "景观"]
    },
    {
        "name": "北京八达岭国家森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "延庆区",
        "type": "公园",
        "address": "延庆区八达岭",
        "transport": "公交",
        "fee": "收费",
        "description": "位于八达岭长城附近的森林公园，有森林和自然景观。",
        "official_url": "",
        "highlights": ["森林", "长城", "自然"]
    },
    {
        "name": "北京野鸭湖国家湿地公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "延庆区",
        "type": "公园",
        "address": "延庆区康庄镇",
        "transport": "公交",
        "fee": "收费",
        "description": "大型湿地公园，有湿地景观和候鸟栖息地。",
        "official_url": "",
        "highlights": ["湿地", "候鸟", "自然"]
    },
    {
        "name": "北京龙庆峡景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "延庆区",
        "type": "公园",
        "address": "延庆区龙庆峡",
        "transport": "公交",
        "fee": "收费",
        "description": "有峡谷、瀑布和湖景的自然景区。",
        "official_url": "",
        "highlights": ["峡谷", "瀑布", "湖景"]
    },
    {
        "name": "北京云居寺",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "文化中心",
        "address": "房山区张坊镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有千年古刹和石经的佛教寺庙。",
        "official_url": "",
        "highlights": ["古刹", "石经", "佛教"]
    },
    {
        "name": "北京十渡景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区十渡镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有山、水、峡谷的自然景区，适合户外和漂流。",
        "official_url": "",
        "highlights": ["山水", "峡谷", "漂流"]
    },
    {
        "name": "北京房山世界地质公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区",
        "transport": "公交",
        "fee": "收费",
        "description": "世界地质公园，展示各种地质景观和化石。",
        "official_url": "",
        "highlights": ["地质公园", "化石", "自然"]
    },
    {
        "name": "北京上方山国家森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区韩村河镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有森林、溶洞和寺庙的自然景区。",
        "official_url": "",
        "highlights": ["森林", "溶洞", "寺庙"]
    },
    {
        "name": "北京石花洞景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区河北镇",
        "transport": "公交",
        "fee": "收费",
        "description": "大型溶洞景区，展示各种钟乳石和石笋。",
        "official_url": "",
        "highlights": ["溶洞", "钟乳石", "石笋"]
    },
    {
        "name": "北京银狐洞景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区佛子庄乡",
        "transport": "公交",
        "fee": "收费",
        "description": "有银狐形状钟乳石的溶洞景区。",
        "official_url": "",
        "highlights": ["溶洞", "银狐", "钟乳石"]
    },
    {
        "name": "北京百花山景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区百花山镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有高山、草甸、森林的自然景区。",
        "official_url": "",
        "highlights": ["高山", "草甸", "森林"]
    },
    {
        "name": "北京圣莲山景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区史家营乡",
        "transport": "公交",
        "fee": "收费",
        "description": "有山景和寺庙的自然景区，适合登山和祈福。",
        "official_url": "",
        "highlights": ["山景", "寺庙", "登山"]
    },
    {
        "name": "北京青龙湖公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区青龙湖镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有湖景和休闲设施的公园，适合划船和露营。",
        "official_url": "",
        "highlights": ["湖景", "划船", "露营"]
    },
    {
        "name": "北京蒲洼乡花台景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区蒲洼乡",
        "transport": "公交",
        "fee": "免费",
        "description": "有高山草甸和花海的自然景区。",
        "official_url": "",
        "highlights": ["草甸", "花海", "免费"]
    },
    {
        "name": "北京霞云岭国家森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "房山区",
        "type": "公园",
        "address": "房山区霞云岭乡",
        "transport": "公交",
        "fee": "收费",
        "description": "有森林和自然景观的景区，适合徒步和露营。",
        "official_url": "",
        "highlights": ["森林", "徒步", "露营"]
    }
]

with open('venue_info.json', 'r', encoding='utf-8') as f:
    venues = json.load(f)

existing_names = {v['name'] for v in venues}
added_count = 0

for venue in new_venues:
    if venue['name'] not in existing_names:
        venues.append(venue)
        print(f"添加: {venue['name']} ({venue['city']})")
        added_count += 1

with open('venue_info.json', 'w', encoding='utf-8') as f:
    json.dump(venues, f, ensure_ascii=False, indent=2)

print(f"\n共添加 {added_count} 个场馆")