import json

new_venues = [
    {
        "name": "北京城市图书馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "图书馆",
        "address": "通州区新华东街",
        "transport": "地铁6号线北运河西站",
        "fee": "免费",
        "description": "北京城市副中心的大型图书馆，建筑设计独特，有丰富的阅读空间。",
        "official_url": "",
        "highlights": ["阅读空间", "建筑设计", "免费"]
    },
    {
        "name": "北京环球度假区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区环球大道",
        "transport": "地铁7号线环球度假区站",
        "fee": "收费",
        "description": "大型主题度假区，有哈利波特、变形金刚、小黄人等主题园区。",
        "official_url": "",
        "highlights": ["哈利波特", "变形金刚", "主题乐园"]
    },
    {
        "name": "北京运河奥体公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区运河奥体公园",
        "transport": "地铁6号线北运河西站",
        "fee": "免费",
        "description": "位于通州区的运河公园，有运河景观和体育设施。",
        "official_url": "",
        "highlights": ["运河", "体育设施", "免费"]
    },
    {
        "name": "北京西海子公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区新华北路",
        "transport": "地铁6号线通州北关站",
        "fee": "免费",
        "description": "通州区的城市公园，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "北京运河森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区运河西大街",
        "transport": "地铁6号线通州北关站",
        "fee": "免费",
        "description": "大型森林公园，有运河绿道和自然景观。",
        "official_url": "",
        "highlights": ["森林", "绿道", "自然", "免费"]
    },
    {
        "name": "北京东郊湿地公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区宋庄镇",
        "transport": "公交",
        "fee": "免费",
        "description": "大型湿地公园，有湿地景观和自然生态。",
        "official_url": "",
        "highlights": ["湿地", "自然生态", "免费"]
    },
    {
        "name": "北京张家湾公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区张家湾镇",
        "transport": "公交",
        "fee": "免费",
        "description": "位于张家湾镇的公园，有运河景观和休闲设施。",
        "official_url": "",
        "highlights": ["运河", "休闲", "免费"]
    },
    {
        "name": "北京台湖公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区台湖镇",
        "transport": "地铁7号线台湖站",
        "fee": "免费",
        "description": "位于台湖镇的公园，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "北京月亮河公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "公园",
        "address": "通州区月亮河河滨路",
        "transport": "地铁6号线北运河东站",
        "fee": "免费",
        "description": "运河畔的公园，有河景和休闲设施。",
        "official_url": "",
        "highlights": ["河景", "休闲", "免费"]
    },
    {
        "name": "北京路县故城遗址",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "博物馆",
        "address": "通州区潞城镇",
        "transport": "地铁6号线潞城站",
        "fee": "免费",
        "description": "汉代路县故城遗址，展示北京城市历史。",
        "official_url": "",
        "highlights": ["汉代遗址", "历史", "免费"]
    },
    {
        "name": "北京通州博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "通州区",
        "type": "博物馆",
        "address": "通州区西大街",
        "transport": "地铁6号线通州西站",
        "fee": "免费",
        "description": "展示通州历史文化和文物。",
        "official_url": "",
        "highlights": ["通州历史", "文物", "免费"]
    },
    {
        "name": "北京汉石桥湿地",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "顺义区",
        "type": "公园",
        "address": "顺义区杨镇",
        "transport": "公交",
        "fee": "免费",
        "description": "北京最大的湿地自然保护区，有芦苇荡和候鸟栖息地。",
        "official_url": "",
        "highlights": ["湿地", "候鸟", "自然", "免费"]
    },
    {
        "name": "北京奥林匹克水上公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "顺义区",
        "type": "体育中心",
        "address": "顺义区白马路",
        "transport": "公交",
        "fee": "收费",
        "description": "2008年奥运会水上项目举办地，有水上运动和休闲设施。",
        "official_url": "",
        "highlights": ["水上运动", "奥运会", "休闲"]
    },
    {
        "name": "北京顺义公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "顺义区",
        "type": "公园",
        "address": "顺义区光明南街",
        "transport": "公交",
        "fee": "免费",
        "description": "顺义区的城市公园，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "北京顺义新城滨河森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "顺义区",
        "type": "公园",
        "address": "顺义区潮白河",
        "transport": "公交",
        "fee": "免费",
        "description": "沿潮白河的森林公园，有绿道和自然景观。",
        "official_url": "",
        "highlights": ["森林", "绿道", "自然", "免费"]
    },
    {
        "name": "北京国际鲜花港",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "顺义区",
        "type": "公园",
        "address": "顺义区杨镇",
        "transport": "公交",
        "fee": "收费",
        "description": "大型花卉展览园区，四季有不同花卉展示。",
        "official_url": "",
        "highlights": ["花卉", "展览", "四季"]
    },
    {
        "name": "北京张裕爱斐堡国际酒庄",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "密云区",
        "type": "文化中心",
        "address": "密云区巨各庄镇",
        "transport": "公交",
        "fee": "收费",
        "description": "欧式风格的酒庄，有葡萄酒文化体验和城堡建筑。",
        "official_url": "",
        "highlights": ["酒庄", "葡萄酒", "欧式建筑"]
    },
    {
        "name": "北京古北水镇",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "密云区",
        "type": "文化中心",
        "address": "密云区古北口镇",
        "transport": "公交",
        "fee": "收费",
        "description": "北方水乡古镇，有古建筑、温泉、夜景等。",
        "official_url": "",
        "highlights": ["水乡古镇", "温泉", "夜景"]
    },
    {
        "name": "北京司马台长城",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "密云区",
        "type": "文化中心",
        "address": "密云区古北口镇",
        "transport": "公交",
        "fee": "收费",
        "description": "中国唯一保留明代原貌的长城，以险峻著称。",
        "official_url": "",
        "highlights": ["长城", "险峻", "明代"]
    },
    {
        "name": "北京黑龙潭景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "密云区",
        "type": "公园",
        "address": "密云区石城镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有瀑布和潭水的自然景区，适合避暑。",
        "official_url": "",
        "highlights": ["瀑布", "潭水", "避暑"]
    },
    {
        "name": "北京云蒙山景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "密云区",
        "type": "公园",
        "address": "密云区石城镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有高山、森林、瀑布的自然景区，适合登山。",
        "official_url": "",
        "highlights": ["高山", "森林", "登山"]
    },
    {
        "name": "北京雾灵山景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "密云区",
        "type": "公园",
        "address": "密云区新城子镇",
        "transport": "公交",
        "fee": "收费",
        "description": "北京最高峰，有森林、云海、日出等景观。",
        "official_url": "",
        "highlights": ["最高峰", "森林", "云海"]
    },
    {
        "name": "北京金海湖景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "平谷区",
        "type": "公园",
        "address": "平谷区金海湖镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有湖景和水上运动的景区，适合度假。",
        "official_url": "",
        "highlights": ["湖景", "水上运动", "度假"]
    },
    {
        "name": "北京京东大峡谷",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "平谷区",
        "type": "公园",
        "address": "平谷区山东庄镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有峡谷、瀑布、潭水的自然景区。",
        "official_url": "",
        "highlights": ["峡谷", "瀑布", "自然"]
    },
    {
        "name": "北京石林峡景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "平谷区",
        "type": "公园",
        "address": "平谷区黄松峪乡",
        "transport": "公交",
        "fee": "收费",
        "description": "以石林和峡谷为特色的自然景区。",
        "official_url": "",
        "highlights": ["石林", "峡谷", "自然"]
    },
    {
        "name": "广州北京路天河城",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "文化中心",
        "address": "越秀区北京路",
        "transport": "地铁1号线公园前站",
        "fee": "免费",
        "description": "北京路商圈的购物中心，有购物、餐饮等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮", "北京路"]
    },
    {
        "name": "广州天河城百货",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区天河路208号",
        "transport": "地铁3号线体育西路站",
        "fee": "免费",
        "description": "天河区的大型百货商场，有购物、餐饮等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮"]
    },
    {
        "name": "广州太古汇商场",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区天河路383号",
        "transport": "地铁3号线石牌桥站",
        "fee": "免费",
        "description": "高端购物中心，有奢侈品品牌和特色餐饮。",
        "official_url": "",
        "highlights": ["高端购物", "奢侈品"]
    },
    {
        "name": "广州维多利广场",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区体育西路103号",
        "transport": "地铁3号线体育西路站",
        "fee": "免费",
        "description": "天河商圈的购物中心，有购物、餐饮等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮"]
    },
    {
        "name": "广州天河体育中心",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "体育中心",
        "address": "天河区天河路299号",
        "transport": "地铁1号线体育西路站",
        "fee": "收费",
        "description": "广州大型体育中心，有体育场、体育馆、游泳馆等设施。",
        "official_url": "",
        "highlights": ["体育赛事", "游泳", "场馆"]
    },
    {
        "name": "广州珠江新城",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区珠江新城",
        "transport": "地铁3号线珠江新城站",
        "fee": "免费",
        "description": "广州的新城区，有现代化建筑和城市景观。",
        "official_url": "",
        "highlights": ["现代化", "城市景观", "免费"]
    },
    {
        "name": "广州花城广场",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区珠江新城",
        "transport": "地铁3号线珠江新城站",
        "fee": "免费",
        "description": "广州的城市广场，有音乐喷泉和城市景观。",
        "official_url": "",
        "highlights": ["音乐喷泉", "城市景观", "免费"]
    },
    {
        "name": "广州海心沙",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区珠江新城",
        "transport": "地铁APM线海心沙站",
        "fee": "免费",
        "description": "珠江中的小岛，有亚运会开闭幕式场地和城市景观。",
        "official_url": "",
        "highlights": ["亚运会", "城市景观", "免费"]
    },
    {
        "name": "广州琶洲会展中心",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "会展中心",
        "address": "海珠区阅江中路",
        "transport": "地铁8号线琶洲站",
        "fee": "收费",
        "description": "广州大型会展中心，举办广交会等大型展览。",
        "official_url": "",
        "highlights": ["广交会", "展览"]
    },
    {
        "name": "广州塔摩天轮",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "文化中心",
        "address": "海珠区阅江西路222号广州塔",
        "transport": "地铁3号线广州塔站",
        "fee": "收费",
        "description": "广州塔顶部的摩天轮，可俯瞰广州全景。",
        "official_url": "",
        "highlights": ["摩天轮", "俯瞰广州"]
    },
    {
        "name": "广州塔极速云霄",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "文化中心",
        "address": "海珠区阅江西路222号广州塔",
        "transport": "地铁3号线广州塔站",
        "fee": "收费",
        "description": "广州塔顶部的极速云霄项目，体验高空速降。",
        "official_url": "",
        "highlights": ["极速云霄", "高空体验"]
    },
    {
        "name": "广州塔户外观景平台",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "文化中心",
        "address": "海珠区阅江西路222号广州塔",
        "transport": "地铁3号线广州塔站",
        "fee": "收费",
        "description": "广州塔户外观景平台，可俯瞰广州全景和珠江。",
        "official_url": "",
        "highlights": ["观景", "俯瞰广州", "珠江"]
    },
    {
        "name": "广州海心桥",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区珠江新城",
        "transport": "地铁APM线海心沙站",
        "fee": "免费",
        "description": "横跨珠江的步行桥，连接广州塔和海心沙。",
        "official_url": "",
        "highlights": ["步行桥", "珠江", "免费"]
    },
    {
        "name": "广州滨江公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "公园",
        "address": "海珠区滨江东路",
        "transport": "地铁8号线晓港站",
        "fee": "免费",
        "description": "沿珠江的公园，有江景和绿道，适合散步和骑行。",
        "official_url": "",
        "highlights": ["江景", "绿道", "骑行", "免费"]
    },
    {
        "name": "广州二沙岛体育公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区二沙岛",
        "transport": "地铁6号线东湖站",
        "fee": "免费",
        "description": "二沙岛上的体育公园，有运动设施和江景。",
        "official_url": "",
        "highlights": ["体育", "江景", "免费"]
    },
    {
        "name": "广州二沙岛艺术公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区二沙岛",
        "transport": "地铁6号线东湖站",
        "fee": "免费",
        "description": "二沙岛上的艺术公园，有雕塑和艺术装置。",
        "official_url": "",
        "highlights": ["艺术", "雕塑", "免费"]
    },
    {
        "name": "广州海印公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "公园",
        "address": "海珠区滨江东路",
        "transport": "地铁8号线晓港站",
        "fee": "免费",
        "description": "位于珠江畔的公园，有江景和休闲设施。",
        "official_url": "",
        "highlights": ["江景", "休闲", "免费"]
    },
    {
        "name": "广州晓港公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "公园",
        "address": "海珠区前进路",
        "transport": "地铁8号线晓港站",
        "fee": "免费",
        "description": "有湖景和竹林的公园，环境清幽。",
        "official_url": "",
        "highlights": ["湖景", "竹林", "清幽", "免费"]
    },
    {
        "name": "广州黄埔公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "公园",
        "address": "黄埔区黄埔东路",
        "transport": "地铁5号线大沙东站",
        "fee": "免费",
        "description": "黄埔区的城市公园，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "广州南海神庙",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "文化中心",
        "address": "黄埔区庙头村",
        "transport": "地铁13号线夏园站",
        "fee": "收费",
        "description": "中国古代海上丝绸之路的起点，有古建筑和庙会活动。",
        "official_url": "",
        "highlights": ["海上丝绸之路", "古建筑", "庙会"]
    },
    {
        "name": "广州萝岗香雪公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "公园",
        "address": "黄埔区萝岗街道",
        "transport": "地铁6号线香雪站",
        "fee": "免费",
        "description": "以梅花闻名的公园，冬季梅花盛开时很美。",
        "official_url": "",
        "highlights": ["梅花", "冬季", "免费"]
    },
    {
        "name": "广州天鹿湖森林公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "公园",
        "address": "黄埔区联和街道",
        "transport": "公交",
        "fee": "收费",
        "description": "有森林、湖泊、瀑布的自然景区，适合徒步。",
        "official_url": "",
        "highlights": ["森林", "湖泊", "徒步"]
    },
    {
        "name": "广州九龙湖度假区",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区花东镇",
        "transport": "公交",
        "fee": "收费",
        "description": "大型度假区，有湖景、高尔夫、酒店等设施。",
        "official_url": "",
        "highlights": ["湖景", "高尔夫", "度假"]
    },
    {
        "name": "广州花都石头记矿物园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "博物馆",
        "address": "花都区珠宝城",
        "transport": "公交",
        "fee": "收费",
        "description": "展示各种矿物和宝石的博物馆，有水晶、玉石等展品。",
        "official_url": "",
        "highlights": ["矿物", "宝石", "水晶"]
    },
    {
        "name": "广州芙蓉嶂风景区",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区狮岭镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有山、水、森林的自然景区，适合休闲度假。",
        "official_url": "",
        "highlights": ["山水", "森林", "度假"]
    },
    {
        "name": "广州九龙潭森林公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区北兴镇",
        "transport": "公交",
        "fee": "收费",
        "description": "有森林、湖泊的自然景区，适合露营和休闲。",
        "official_url": "",
        "highlights": ["森林", "湖泊", "露营"]
    },
    {
        "name": "上海科技馆主馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "科技馆",
        "address": "浦东新区世纪大道2000号",
        "transport": "地铁2号线上海科技馆站",
        "fee": "收费",
        "description": "上海科技馆主馆，有多个主题展厅和互动体验。",
        "official_url": "",
        "highlights": ["互动体验", "科普", "主题展厅"]
    },
    {
        "name": "上海东方明珠太空舱",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区世纪大道1号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "东方明珠塔的太空舱，可俯瞰上海全景。",
        "official_url": "",
        "highlights": ["太空舱", "俯瞰上海"]
    },
    {
        "name": "上海东方明珠悬空观光廊",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区世纪大道1号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "东方明珠塔的悬空观光廊，体验高空玻璃栈道。",
        "official_url": "",
        "highlights": ["悬空廊", "玻璃栈道", "高空"]
    },
    {
        "name": "上海中心大厦观光厅",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区陆家嘴环路1000号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "上海中心大厦118层观光厅，可俯瞰上海全貌。",
        "official_url": "",
        "highlights": ["118层", "俯瞰上海", "最高建筑"]
    },
    {
        "name": "上海金茂大厦观光厅",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区世纪大道88号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "金茂大厦88层观光厅，可俯瞰上海全景。",
        "official_url": "",
        "highlights": ["88层", "俯瞰上海"]
    },
    {
        "name": "上海环球金融中心观光厅",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区世纪大道100号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "环球金融中心观光厅，可俯瞰上海全景。",
        "official_url": "",
        "highlights": ["观光", "俯瞰上海"]
    },
    {
        "name": "上海海洋水族馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "科普馆",
        "address": "浦东新区陆家嘴环路1388号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "展示各种海洋生物，有海底隧道和鲨鱼馆。",
        "official_url": "",
        "highlights": ["海洋生物", "海底隧道", "鲨鱼"]
    },
    {
        "name": "上海长风海洋世界",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "普陀区",
        "type": "科普馆",
        "address": "普陀区大渡河路451号",
        "transport": "地铁15号线长风公园站",
        "fee": "收费",
        "description": "长风公园内的海洋世界，有白鲸表演和海底隧道。",
        "official_url": "",
        "highlights": ["白鲸表演", "海底隧道"]
    },
    {
        "name": "上海野生动物园车行区",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区南六公路178号",
        "transport": "地铁16号线野生动物园站",
        "fee": "收费",
        "description": "上海野生动物园的车行区，可自驾或坐观光车游览猛兽区。",
        "official_url": "",
        "highlights": ["猛兽区", "自驾", "观光车"]
    },
    {
        "name": "上海野生动物园步行区",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区南六公路178号",
        "transport": "地铁16号线野生动物园站",
        "fee": "收费",
        "description": "上海野生动物园的步行区，可步行观赏和投喂动物。",
        "official_url": "",
        "highlights": ["步行观赏", "投喂动物"]
    },
    {
        "name": "上海海昌海洋公园虎鲸馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "科普馆",
        "address": "浦东新区银飞路166号",
        "transport": "地铁16号线临港大道站",
        "fee": "收费",
        "description": "海昌海洋公园的虎鲸馆，有虎鲸表演和科普展示。",
        "official_url": "",
        "highlights": ["虎鲸表演", "科普"]
    },
    {
        "name": "上海海昌海洋公园北极熊馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "科普馆",
        "address": "浦东新区银飞路166号",
        "transport": "地铁16号线临港大道站",
        "fee": "收费",
        "description": "海昌海洋公园的北极熊馆，有北极熊和北极动物展示。",
        "official_url": "",
        "highlights": ["北极熊", "北极动物"]
    },
    {
        "name": "上海迪士尼乐园城堡",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "上海迪士尼乐园的标志性城堡，有灯光秀和烟花表演。",
        "official_url": "",
        "highlights": ["城堡", "灯光秀", "烟花"]
    },
    {
        "name": "上海迪士尼乐园明日世界",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "迪士尼乐园的明日世界园区，有创极速光轮等刺激项目。",
        "official_url": "",
        "highlights": ["创极速光轮", "刺激项目"]
    },
    {
        "name": "上海迪士尼乐园梦幻世界",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "迪士尼乐园的梦幻世界园区，有小熊维尼、小飞侠等亲子项目。",
        "official_url": "",
        "highlights": ["小熊维尼", "小飞侠", "亲子"]
    },
    {
        "name": "上海迪士尼乐园宝藏湾",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "迪士尼乐园的宝藏湾园区，有加勒比海盗等项目。",
        "official_url": "",
        "highlights": ["加勒比海盗", "宝藏"]
    },
    {
        "name": "上海迪士尼乐园奇想花园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "迪士尼乐园的奇想花园园区，有米奇大街和城堡。",
        "official_url": "",
        "highlights": ["米奇大街", "城堡"]
    },
    {
        "name": "上海迪士尼乐园探险岛",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "迪士尼乐园的探险岛园区，有雷鸣山漂流等项目。",
        "official_url": "",
        "highlights": ["雷鸣山漂流", "探险"]
    },
    {
        "name": "上海迪士尼乐园皮克斯玩具总动员",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "迪士尼乐园的皮克斯玩具总动员园区，有胡迪牛仔嘉年华等项目。",
        "official_url": "",
        "highlights": ["皮克斯", "玩具总动员", "胡迪"]
    },
    {
        "name": "上海乐高乐园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "金山区",
        "type": "公园",
        "address": "金山区",
        "transport": "自驾",
        "fee": "收费",
        "description": "大型乐高主题乐园，有乐高积木搭建的建筑和游乐设施。",
        "official_url": "",
        "highlights": ["乐高", "积木", "主题乐园"]
    },
    {
        "name": "上海欢乐谷谷木游龙",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区林湖路888号",
        "transport": "地铁9号线佘山站",
        "fee": "收费",
        "description": "欢乐谷的木质过山车，是上海著名的刺激项目。",
        "official_url": "",
        "highlights": ["过山车", "刺激"]
    },
    {
        "name": "上海欢乐谷玛雅海滩水公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区林湖路888号",
        "transport": "地铁9号线佘山站",
        "fee": "收费",
        "description": "欢乐谷的水上乐园，有各种水上项目和造浪池。",
        "official_url": "",
        "highlights": ["水上乐园", "造浪池"]
    },
    {
        "name": "上海辰山植物园温室",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "科普馆",
        "address": "松江区辰花公路3888号",
        "transport": "地铁9号线洞泾站",
        "fee": "收费",
        "description": "辰山植物园的大型温室，展示热带和亚热带植物。",
        "official_url": "",
        "highlights": ["温室", "热带植物"]
    },
    {
        "name": "上海辰山植物园矿坑花园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区辰花公路3888号",
        "transport": "地铁9号线洞泾站",
        "fee": "收费",
        "description": "辰山植物园的矿坑花园，有瀑布和景观。",
        "official_url": "",
        "highlights": ["矿坑", "瀑布", "景观"]
    },
    {
        "name": "上海松江大学城",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "文化中心",
        "address": "松江区大学城",
        "transport": "地铁9号线松江大学城站",
        "fee": "免费",
        "description": "集中了多所大学的区域，有青春气息和文化设施。",
        "official_url": "",
        "highlights": ["大学", "青春", "文化"]
    },
    {
        "name": "上海松江方塔园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区中山东路",
        "transport": "公交",
        "fee": "收费",
        "description": "有古塔和古典园林的公园，展示松江历史文化。",
        "official_url": "",
        "highlights": ["古塔", "古典园林", "历史"]
    },
    {
        "name": "上海松江醉白池",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区人民南路",
        "transport": "公交",
        "fee": "收费",
        "description": "松江著名的古典园林，有亭台楼阁和池塘。",
        "official_url": "",
        "highlights": ["古典园林", "亭台楼阁"]
    },
    {
        "name": "上海泰晤士小镇",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "文化中心",
        "address": "松江区三新北路",
        "transport": "公交",
        "fee": "免费",
        "description": "英式风格的小镇，有教堂、广场和商业设施。",
        "official_url": "",
        "highlights": ["英式风格", "教堂", "拍照"]
    },
    {
        "name": "上海欢乐谷魔幻城堡",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区林湖路888号",
        "transport": "地铁9号线佘山站",
        "fee": "收费",
        "description": "欢乐谷的魔幻城堡区，适合儿童游玩。",
        "official_url": "",
        "highlights": ["魔幻城堡", "儿童区"]
    },
    {
        "name": "杭州西湖音乐喷泉",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区湖滨",
        "transport": "地铁1号线龙翔桥站",
        "fee": "免费",
        "description": "西湖边的音乐喷泉，每晚有灯光和音乐表演。",
        "official_url": "",
        "highlights": ["音乐喷泉", "灯光表演", "免费"]
    },
    {
        "name": "杭州西湖游船",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西湖",
        "transport": "地铁1号线龙翔桥站",
        "fee": "收费",
        "description": "西湖游船，可游览西湖十景。",
        "official_url": "",
        "highlights": ["游船", "西湖十景"]
    },
    {
        "name": "杭州西湖三潭印月",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西湖",
        "transport": "游船",
        "fee": "收费",
        "description": "西湖十景之一，有三座石塔，是西湖的标志性景点。",
        "official_url": "",
        "highlights": ["三潭印月", "西湖十景", "标志性"]
    },
    {
        "name": "杭州西湖湖心亭",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西湖",
        "transport": "游船",
        "fee": "收费",
        "description": "西湖中的小岛，有湖心亭和古建筑。",
        "official_url": "",
        "highlights": ["湖心亭", "小岛", "古建筑"]
    },
    {
        "name": "杭州西湖阮公墩",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西湖",
        "transport": "游船",
        "fee": "收费",
        "description": "西湖中的小岛，有自然景观和休闲设施。",
        "official_url": "",
        "highlights": ["小岛", "自然景观"]
    },
    {
        "name": "杭州西湖杨公堤",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区杨公堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖的长堤，有苏堤春晓和曲院风荷等景点。",
        "official_url": "",
        "highlights": ["长堤", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖苏堤春晓",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区苏堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，春季苏堤上柳树发芽，景色优美。",
        "official_url": "",
        "highlights": ["春季", "柳树", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖断桥残雪",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区白堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，冬季断桥上积雪，景色如画。",
        "official_url": "",
        "highlights": ["冬季", "雪景", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖雷峰夕照",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区雷峰塔",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "西湖十景之一，傍晚雷峰塔夕阳映照，景色优美。",
        "official_url": "",
        "highlights": ["夕阳", "雷峰塔", "西湖十景"]
    },
    {
        "name": "杭州西湖南屏晚钟",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区南屏山",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "西湖十景之一，南屏山净慈寺的钟声。",
        "official_url": "",
        "highlights": ["钟声", "净慈寺", "西湖十景"]
    },
    {
        "name": "杭州西湖曲院风荷",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区北山路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，夏季荷花盛开，景色优美。",
        "official_url": "",
        "highlights": ["荷花", "夏季", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖花港观鱼",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区杨公堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，有红鱼池和牡丹园。",
        "official_url": "",
        "highlights": ["红鱼池", "牡丹园", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖柳浪闻莺",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区南山路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，有柳树和草坪，适合休闲散步。",
        "official_url": "",
        "highlights": ["柳树", "草坪", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖双峰插云",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区灵隐路",
        "transport": "公交7路",
        "fee": "免费",
        "description": "西湖十景之一，以南高峰和北高峰闻名。",
        "official_url": "",
        "highlights": ["南北高峰", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖平湖秋月",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区白堤西端",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，秋季赏月的好去处。",
        "official_url": "",
        "highlights": ["赏月", "秋季", "西湖十景", "免费"]
    },
    {
        "name": "杭州西湖吴山天风",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "公园",
        "address": "上城区吴山路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，位于吴山，可登高远眺西湖。",
        "official_url": "",
        "highlights": ["吴山", "登高", "西湖十景", "免费"]
    }
]

with open('venue_info.json', 'r', encoding='utf-8') as f:
    venues = json.load(f)

existing_names = {v['name'] for v in venues}
added_count = 0

for venue in new_venues:
    if venue['name'] not in existing_names:
        venues.append(venue)
        print(f"添加: {venue['name']} ({venue['city']})")
        added_count += 1

with open('venue_info.json', 'w', encoding='utf-8') as f:
    json.dump(venues, f, ensure_ascii=False, indent=2)

print(f"\n共添加 {added_count} 个场馆")