import json
import os

DATA_FILE = 'output/exhibitions.json'
OUTPUT_FILE = 'output/exhibitions.json'

new_activities = [
    # ========== 北京补充活动（第三批）==========
    {"name": "墨拓千年币修课传拓研学", "venue": "万寿寺博物馆", "city": "beijing", "district": "海淀区", "start_date": "2026-07-11", "end_date": "2026-08-30", "fee": "收费", "description": "学习古老的传拓技艺，亲手触摸古代铜钱，把藏着古代故事和艺术的铜钱变到纸上。", "source": "北京文博", "highlights": ["传拓", "非遗", "钱币"], "type": "亲子活动"},
    {"name": "寻迹非遗暑期传统工艺研学营", "venue": "万寿寺博物馆", "city": "beijing", "district": "海淀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "包含大漆挂饰、洪福齐天泥板壁画、解暑合香、金榜题名宋锦礼盒制作等非遗课程。", "source": "北京文博", "highlights": ["非遗", "研学", "传统工艺"], "type": "亲子活动"},
    {"name": "大美星空四季星空认星课堂", "venue": "北京天文馆", "city": "beijing", "district": "西城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "沉浸式体验全国各地壮美星空，天文科普专家现场带你认识四季星空。", "source": "北京天文馆", "highlights": ["天文", "星空", "科普"], "type": "讲座"},
    {"name": "钢铁巨兽奇遇记铁道博物馆一日营", "venue": "中国铁道博物馆东郊展馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-18", "end_date": "2026-08-15", "fee": "收费", "description": "跨越300年动力科技大冒险，参观蒸汽机车与复兴号模型，动手搭建列车模型。", "source": "中国铁道博物馆", "highlights": ["火车", "科技", "一日营"], "type": "亲子活动"},
    {"name": "童学赶考周末研学活动", "venue": "香山革命纪念馆", "city": "beijing", "district": "海淀区", "start_date": "2026-07-04", "end_date": "2026-07-18", "fee": "免费", "description": "宣教员带领同学和家长利用教育读本，在基本陈列中身临其境感悟香山红色文化。", "source": "北京市文物局", "highlights": ["红色研学", "周末", "亲子"], "type": "亲子活动"},
    {"name": "奇妙动物探索夏令营", "venue": "中国农业博物馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-13", "end_date": "2026-07-17", "fee": "收费", "description": "课程根据昆虫→鱼类→两栖类→爬行类→鸟类循序渐进解锁动物知识。", "source": "北京市文物局", "highlights": ["动物", "夏令营", "科普"], "type": "亲子活动"},
    {"name": "寻迹茅盾数字游园", "venue": "中国现代文学馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-04", "end_date": "2026-08-31", "fee": "免费", "description": "在场馆内进行趣味答题与打卡，完成任务可领取子夜手稿参观纪念票。", "source": "北京市文物局", "highlights": ["茅盾", "数字游园", "文学"], "type": "亲子活动"},
    {"name": "园丁养成记花园共建", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-07-25", "fee": "免费", "description": "志愿者走进秘密花园，与科普老师一同参与花园共建，学习园林生态知识与劳动技能。", "source": "北京市文物局", "highlights": ["花园", "共建", "生态"], "type": "亲子活动"},
    {"name": "自然笔记创作体验", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-04", "end_date": "2026-07-26", "fee": "免费", "description": "科普老师带领游客对园林景观进行观察学习，用绘画搭配文字记录创作自然笔记。", "source": "北京市文物局", "highlights": ["自然笔记", "绘画", "科普"], "type": "亲子活动"},
    {"name": "像素花园拼豆艺术创作", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "园林邂逅缤纷拼豆，创意与自然科普碰撞，拼出独属园林的自然美学。", "source": "北京市文物局", "highlights": ["拼豆", "艺术", "创意"], "type": "亲子活动"},
    {"name": "非遗掐丝珐琅体验", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "传统园林艺术与珐琅、铜板等非遗手工艺结合，感悟非遗技艺的精湛绝伦。", "source": "北京市文物局", "highlights": ["掐丝珐琅", "非遗", "手工艺"], "type": "亲子活动"},
    {"name": "红楼探园十二讲园林文化讲座", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-18", "end_date": "2026-07-18", "fee": "免费", "description": "特邀专家开展今天我们为什么还要读红楼梦专题讲座，品读红楼经典。", "source": "北京市文物局", "highlights": ["红楼梦", "讲座", "园林"], "type": "讲座"},
    {"name": "园林听书袁派红楼梦评书", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-18", "end_date": "2026-07-19", "fee": "免费", "description": "袁派红楼梦评书搬进亭台叠石间，暑期夜场同步上线，吹着园林晚风解锁红楼世界。", "source": "北京文博", "highlights": ["评书", "红楼梦", "夜场"], "type": "演出"},
    {"name": "我的机器人朋友探索展", "venue": "北京汽车博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-04", "end_date": "2026-10-11", "fee": "收费", "description": "北京首次在文博场馆内推出的大型综合具身机器人科普特展，集结多款行业前沿机器人。", "source": "首都教育", "highlights": ["机器人", "科技", "展览"], "type": "展览"},
    {"name": "南天门计划科幻科普主题展", "venue": "中华世纪坛", "city": "beijing", "district": "海淀区", "start_date": "2026-07-08", "end_date": "2026-10-11", "fee": "收费", "description": "以科幻筑梦航空报国为核心，串联神话想象、当下航空工业、未来空天蓝图。", "source": "首都教育", "highlights": ["科幻", "航空", "沉浸式"], "type": "展览"},
    {"name": "战国秦汉时期的云南文物展", "venue": "北京大运河博物馆", "city": "beijing", "district": "通州区", "start_date": "2026-05-15", "end_date": "2026-10-07", "fee": "免费", "description": "系统呈现古滇国为代表的西南夷各族青铜文化，三大篇章讲述西南边疆融入华夏的历史进程。", "source": "文旅通州", "highlights": ["云南", "青铜", "文物"], "type": "展览"},
    {"name": "鄂尔多斯青铜文化展", "venue": "北京大运河博物馆", "city": "beijing", "district": "通州区", "start_date": "2026-06-16", "end_date": "2026-09-13", "fee": "免费", "description": "340余件鄂尔多斯式青铜器首次在京集中展出，讲述北方草原青铜文化发展历程。", "source": "文旅通州", "highlights": ["鄂尔多斯", "青铜", "草原文化"], "type": "展览"},
    {"name": "故宫藏古代颜色釉瓷器展", "venue": "北京大运河博物馆", "city": "beijing", "district": "通州区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "112件中国古代颜色釉瓷器精品，青红黄白黑五大色釉体系全面展示。", "source": "文旅通州", "highlights": ["故宫", "瓷器", "颜色釉"], "type": "展览"},
    {"name": "不止运河沉浸式体验展", "venue": "北京大运河博物馆", "city": "beijing", "district": "通州区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "光影互动空间，动态呈现大运河两岸繁盛景象，让历史文化变得鲜活可感。", "source": "文旅通州", "highlights": ["沉浸式", "运河", "光影"], "type": "展览"},
    {"name": "荣光之路建党文物史料展", "venue": "中国共产党早期革命活动纪念馆", "city": "beijing", "district": "西城区", "start_date": "2026-06-25", "end_date": "2026-12-31", "fee": "免费", "description": "105件套珍贵革命文物串联起北京孕育、上海制造、南湖启航的建党完整历程。", "source": "首都教育", "highlights": ["建党", "文物", "红色"], "type": "展览"},
    {"name": "周恩来邓颖超与孩子们专题展", "venue": "中国妇女儿童博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-05-26", "end_date": "2026-12-31", "fee": "免费", "description": "大量历史图片生动讲述周恩来邓颖超与孩子们之间的感人故事。", "source": "首都教育", "highlights": ["周恩来", "儿童", "专题展"], "type": "展览"},
    {"name": "茅盾诞辰130周年特展", "venue": "中国现代文学馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-04", "end_date": "2027-07-04", "fee": "免费", "description": "纪念茅盾先生诞辰130周年特展，深切缅怀茅盾先生的卓越功勋与文学精神。", "source": "首都教育", "highlights": ["茅盾", "文学", "特展"], "type": "展览"},
    {"name": "百合千年雅韵主题展", "venue": "中国农业博物馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-06-19", "end_date": "2026-07-31", "fee": "免费", "description": "系统梳理百合从野生植物到全球重要花卉的发展历程。", "source": "首都教育", "highlights": ["百合", "花卉", "农业"], "type": "展览"},
    {"name": "壁彩京华壁画彩塑数字光影展", "venue": "中国工艺美术馆", "city": "beijing", "district": "朝阳区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "收费", "description": "首都壁画彩塑数字光影艺术巡展，数字化呈现古代壁画彩塑艺术。", "source": "首都教育", "highlights": ["壁画", "数字光影", "非遗"], "type": "展览"},
    {"name": "汪菊渊学术思想展", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-06-22", "end_date": "2026-12-31", "fee": "免费", "description": "300余件展品展示汪菊渊先生生平成就与园林学科发展历程。", "source": "首都教育", "highlights": ["汪菊渊", "园林", "学术"], "type": "展览"},
    {"name": "红色经典影片展映", "venue": "香山革命纪念馆", "city": "beijing", "district": "海淀区", "start_date": "2026-07-08", "end_date": "2026-08-31", "fee": "免费", "description": "纪念馆一层报告厅每日14:30播放红色经典影片，免预约观看。", "source": "香山革命纪念馆", "highlights": ["红色电影", "暑期", "免费"], "type": "演出"},
    {"name": "园博读书慧", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "每周六围绕园林文化、古籍文献、造园技艺等主题开展晚间读书分享活动。", "source": "北京市文物局", "highlights": ["读书", "园林", "夜场"], "type": "讲座"},
    {"name": "竹外茶社文化雅集", "venue": "中国园林博物馆", "city": "beijing", "district": "丰台区", "start_date": "2026-07-15", "end_date": "2026-07-25", "fee": "免费", "description": "围绕园林物候特征与节气节俗，通过夏日手工与艺术体验开启沉浸式文化雅集。", "source": "北京市文物局", "highlights": ["雅集", "茶社", "手工"], "type": "亲子活动"},
    {"name": "赶考讲堂系列讲座", "venue": "香山革命纪念馆", "city": "beijing", "district": "海淀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "7-8月每周1场，邀请知名专家学者进行香山革命历史和文物保护专题授课。", "source": "香山革命纪念馆", "highlights": ["讲座", "党史", "专家"], "type": "讲座"},

    # ========== 广州补充活动（第三批）==========
    {"name": "万物皆数数学嘉年华", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-11", "end_date": "2026-07-19", "fee": "免费", "description": "联动东莞松山湖数学探索馆打造数学思维游乐场，七大板块50余种互动体验项目。", "source": "科普广州", "highlights": ["数学", "嘉年华", "互动"], "type": "亲子活动"},
    {"name": "玩转奇妙自然科技嘉年华", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-11", "end_date": "2026-07-11", "fee": "免费", "description": "掌上火焰、液氮速冻、焰色反应、等离子炮等震撼实验轮番登场。", "source": "科普广州", "highlights": ["科学秀", "实验", "科技"], "type": "演出"},
    {"name": "小小净水工程师实验室", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-12", "end_date": "2026-07-12", "fee": "免费", "description": "利用砂石、活性炭、滤纸搭建简易净水装置，动手实操沉淀过滤吸附流程。", "source": "科普广州", "highlights": ["净水", "实验", "环保"], "type": "亲子活动"},
    {"name": "多元创客互动体验", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-14", "end_date": "2026-07-17", "fee": "免费", "description": "VEX机器人、足球无人机、AI智能小车、3D建模打印、下棋AI等七大互动项目开放。", "source": "科普广州", "highlights": ["创客", "机器人", "AI"], "type": "亲子活动"},
    {"name": "科学家奋斗故事展教小课堂", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-11", "end_date": "2026-07-19", "fee": "免费", "description": "打卡广州科学家故事展，完成沉浸式闯关任务：勇闯迷宫、搭建地标、导电实验等。", "source": "科普广州", "highlights": ["科学家", "小课堂", "闯关"], "type": "讲座"},
    {"name": "肠道小宇宙互动体验科学展", "venue": "广东科学中心", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2027-02-28", "fee": "收费", "description": "法国国家科技总馆出品，7部影像装置、9处经典互动实验，亲手拉出7米肠道模型。", "source": "广东科学中心", "highlights": ["肠道", "人体科学", "沉浸式"], "type": "展览"},
    {"name": "假日科学派十大主题活动", "venue": "广东科学中心", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "科学挑战赛、科普摊位、创意工坊、科普表演秀等十大主题互动项目。", "source": "广东科学中心", "highlights": ["科学派", "互动", "暑期"], "type": "亲子活动"},
    {"name": "感官大作战欢乐科学课", "venue": "广东科学中心", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "趣味小游戏与互动实验，引导观众认识身体的感知奥秘。", "source": "广东科学中心", "highlights": ["感官", "科学课", "互动"], "type": "讲座"},
    {"name": "纸是那么酷欢乐科学课", "venue": "广东科学中心", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "感受一张纸带来的无限科学可能，解锁纸的各种奇妙玩法。", "source": "广东科学中心", "highlights": ["纸", "科学课", "创意"], "type": "讲座"},
    {"name": "航海密码解密活动", "venue": "广东科学中心", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-11", "end_date": "2026-07-11", "fee": "收费", "description": "结合中国航海日推出趣味科普活动，解锁跨越千年的航海密码。", "source": "广东科学中心", "highlights": ["航海", "解密", "科普"], "type": "亲子活动"},
    {"name": "天空之城动漫钢琴音乐会", "venue": "广东科学中心巨幕影院", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "宫崎骏久石让经典动漫钢琴五重奏音乐会，在巨幕影院呈现视听盛宴。", "source": "广东科学中心", "highlights": ["音乐会", "动漫", "宫崎骏"], "type": "演出"},
    {"name": "经典动画视界亲子音乐会", "venue": "广东科学中心巨幕影院", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "经典动画主题亲子科技音乐会，将乐曲与动画美学结合。", "source": "广东科学中心", "highlights": ["动画", "音乐会", "亲子"], "type": "演出"},
    {"name": "海洋魔法幻城", "venue": "正佳极地海洋世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "大湾区首个海洋魔法幻城，16个魔幻小剧场，近百场近景魔术互动。", "source": "南方网", "highlights": ["海洋", "魔术", "暑期"], "type": "演出"},
    {"name": "G-Fest动漫狂欢节", "venue": "正佳广场", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "免费", "description": "第四届正佳星球动漫狂欢节，百大IP、千场演出，华南地区规模领先的全民动漫盛宴。", "source": "南方网", "highlights": ["动漫", "狂欢节", "IP"], "type": "演出"},
    {"name": "大圣闹海水下大秀", "venue": "正佳极地海洋世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "全新水下主题大秀，水下演绎齐天大圣闹海传奇故事。", "source": "南方网", "highlights": ["水下表演", "大圣", "海洋"], "type": "演出"},
    {"name": "敦煌飞天水下大秀", "venue": "正佳极地海洋世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "水下演绎敦煌飞天经典，呈现东方美学与海洋的完美融合。", "source": "南方网", "highlights": ["敦煌", "水下表演", "飞天"], "type": "演出"},
    {"name": "青白缘起水下大秀", "venue": "正佳极地海洋世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "青白蛇传经典故事水下新编，演绎千年传说的浪漫。", "source": "南方网", "highlights": ["白蛇传", "水下表演", "传说"], "type": "演出"},
    {"name": "鲛人魅影水下大秀", "venue": "正佳极地海洋世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "神秘鲛人传说水下演绎，梦幻光影与深海奇观交织。", "source": "南方网", "highlights": ["鲛人", "水下表演", "梦幻"], "type": "演出"},
    {"name": "逃脱巨齿鲨水下大秀", "venue": "正佳极地海洋世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "惊险刺激的巨齿鲨主题水下表演，带来震撼视觉体验。", "source": "南方网", "highlights": ["巨齿鲨", "水下表演", "惊险"], "type": "演出"},
    {"name": "企鹅萌动巡游", "venue": "正佳企鹅冰雪世界", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "全新升级企鹅冰雪世界，企鹅萌动巡游，200米长冰滑梯畅玩。", "source": "南方网", "highlights": ["企鹅", "冰雪", "巡游"], "type": "亲子活动"},
    {"name": "甲虫科普专题展", "venue": "正佳雨林生态植物园", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "珍稀甲虫科普展，每天三十余场亲子科普体验活动。", "source": "南方网", "highlights": ["甲虫", "科普", "雨林"], "type": "展览"},
    {"name": "珍稀蕨类植物展", "venue": "正佳雨林生态植物园", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "珍稀蕨类植物专题展，了解植物活化石的生命奥秘。", "source": "南方网", "highlights": ["蕨类", "植物", "科普"], "type": "展览"},
    {"name": "蜘蛛侠联动特展", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "收费", "description": "与蜘蛛侠崭新之日IP联动，搭配真实巴西所罗门捕鸟蛛，虚拟与现实奇妙碰撞。", "source": "南方网", "highlights": ["蜘蛛侠", "漫威", "联动"], "type": "展览"},
    {"name": "越王者旨於睗剑青铜展", "venue": "正佳中华文明探索馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "收费", "description": "青铜重器越王者旨於睗剑重磅展出，全场景覆盖亲子科普。", "source": "南方网", "highlights": ["青铜剑", "文物", "越王者旨於睗"], "type": "展览"},
    {"name": "夜间科学奇妙夜", "venue": "正佳科学馆天文馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "持续推出科普剧与夜间科学奇妙夜活动，解锁夜间科学新体验。", "source": "南方网", "highlights": ["科学奇妙夜", "夜场", "科普剧"], "type": "亲子活动"},
    {"name": "AYOR TOYS奇幻森林广州首展", "venue": "正佳广场", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "免费", "description": "AYOR TOYS奇幻森林广州首展，打造奇幻森林主题场景。", "source": "南方网", "highlights": ["潮玩", "首展", "奇幻森林"], "type": "展览"},
    {"name": "JOJO的奇妙冒险主题快闪", "venue": "正佳广场", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "免费", "description": "JOJO的奇妙冒险主题快闪店，经典动漫IP限时亮相。", "source": "南方网", "highlights": ["JOJO", "快闪", "动漫"], "type": "展览"},
    {"name": "数码宝贝期间限定店", "venue": "正佳广场", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-10", "end_date": "2026-08-31", "fee": "免费", "description": "数码宝贝期间限定店，重温经典数码宝贝世界。", "source": "南方网", "highlights": ["数码宝贝", "限定店", "动漫"], "type": "展览"},
    {"name": "科普基地联合科普专场", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-14", "end_date": "2026-07-17", "fee": "免费", "description": "多家科普基地轮番驻馆，开设专题展览、互动讲座与动手体验活动。", "source": "科普广州", "highlights": ["科普基地", "联合", "专场"], "type": "亲子活动"},

    # ========== 上海补充活动（第三批）==========
    {"name": "世界树之巅美洲古代文明大展", "venue": "上海博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-09", "end_date": "2027-11-14", "fee": "收费", "description": "联合墨西哥秘鲁顶尖文博机构，1129组近3000件精美文物，全球最大规模美洲古代文明展。", "source": "上海旅游节", "highlights": ["美洲文明", "文物", "大展"], "type": "展览"},
    {"name": "马王堆汉墓生活美学国宝展", "venue": "上海美术馆中华艺术宫", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-03", "end_date": "2026-10-07", "fee": "收费", "description": "马王堆考古史上最大规模省外展出，汉代生活极致风雅，重现千金之家盛世风华。", "source": "上海旅游节", "highlights": ["马王堆", "汉代", "国宝"], "type": "展览"},
    {"name": "国采故宫藏清代帝后服饰展", "venue": "上海世博会博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-07", "end_date": "2026-10-07", "fee": "收费", "description": "康熙礼服褂、乾隆龙袍等九成从未出京，超三成首次面世，宫廷服饰华贵大气。", "source": "上海文旅局", "highlights": ["故宫", "服饰", "清代"], "type": "展览"},
    {"name": "宝硕流光乾隆时期文物特展", "venue": "奉贤博物馆", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-30", "fee": "免费", "description": "故宫馆藏121件套珍贵文物，乾隆朝服像、古稀天子之宝印等重磅亮相。", "source": "新闻晨报", "highlights": ["乾隆", "故宫文物", "特展"], "type": "展览"},
    {"name": "奉贤博物馆奇妙夜", "venue": "奉贤博物馆", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-30", "fee": "免费", "description": "暑期夜游延长开放，专家夜间导赏、朕的一日沉浸式互动、七夕国风集市。", "source": "新闻晨报", "highlights": ["博物馆奇妙夜", "夜游", "乾隆"], "type": "亲子活动"},
    {"name": "虎鲸造浪节", "venue": "上海海昌海洋公园", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "连续66天夜场开放至21点，四大戏水派对、6大夜秀、10大明星剧目升级。", "source": "上海本地宝", "highlights": ["虎鲸", "造浪节", "夜场"], "type": "亲子活动"},
    {"name": "史前星球恐龙篇沉浸式巨幕体验", "venue": "西岸美术馆", "city": "shanghai", "district": "徐汇区", "start_date": "2026-07-01", "end_date": "2027-01-27", "fee": "收费", "description": "360度沉浸式投影系统，与史前生物同行，真实感受它们的尺度与生存环境。", "source": "上海旅游节", "highlights": ["恐龙", "沉浸式", "巨幕"], "type": "展览"},
    {"name": "动物奇妙夜", "venue": "上海动物园", "city": "shanghai", "district": "长宁区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "探秘夜间动物园，夜猫子和森林课夜观活动，展示夜行性动物自然行为。", "source": "上海旅游节", "highlights": ["动物园", "夜场", "奇妙夜"], "type": "亲子活动"},
    {"name": "布里奇曼名画奇旅全球首展", "venue": "上海美术馆中华艺术宫", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2027-06-30", "fee": "收费", "description": "67家世界顶级文博机构、近70位中外艺术巨匠、跨越1800年近200幅正版高清名作。", "source": "上海本地宝", "highlights": ["名画", "沉浸式", "全球首展"], "type": "展览"},
    {"name": "肇兴中国秦大一统之路文物展", "venue": "上海博物馆东馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-09-07", "fee": "收费", "description": "14家考古文博机构510件文物，全景展示秦统一中国的历史进程。", "source": "上海文旅局", "highlights": ["秦朝", "大一统", "文物"], "type": "展览"},
    {"name": "苏州河历史文化展", "venue": "上海市历史博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-03", "end_date": "2026-08-29", "fee": "免费", "description": "从元代水闸到外白渡桥，苏州河百年历史文化展，夜间开放至20:00。", "source": "上海文旅局", "highlights": ["苏州河", "历史", "夜场"], "type": "展览"},
    {"name": "徽州文化艺术展", "venue": "上海市历史博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "只在山林与泉曲——徽州文化艺术展，徽派建筑与艺术之美。", "source": "上海文旅局", "highlights": ["徽州", "文化", "艺术"], "type": "展览"},
    {"name": "上历博博物馆奇妙夜", "venue": "上海市历史博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-03", "end_date": "2026-08-29", "fee": "免费", "description": "小浪花讲解团童声讲述苏州河故事，苏州河夜游Citywalk，徽州非遗工坊研学。", "source": "上海文旅局", "highlights": ["博物馆奇妙夜", "苏州河", "非遗"], "type": "亲子活动"},
    {"name": "上海地铁博物馆焕新开放", "venue": "上海地铁博物馆", "city": "shanghai", "district": "闵行区", "start_date": "2026-07-15", "end_date": "2026-12-31", "fee": "免费", "description": "焕新归来，22号线紫金战车模型、AI互动体验区、VR互动、应急避险实训舱。", "source": "上海本地宝", "highlights": ["地铁", "焕新", "AI互动"], "type": "展览"},
    {"name": "花样年华音乐电影场", "venue": "西岸梦中心水岸剧场", "city": "shanghai", "district": "徐汇区", "start_date": "2026-07-15", "end_date": "2026-07-15", "fee": "免费", "description": "上海RJ爵士大乐团现场演奏电影主题曲，再看一场浪漫电影花样年华。", "source": "上海本地宝", "highlights": ["电影", "音乐会", "浪漫"], "type": "演出"},
    {"name": "申园纳夏凉园林消夏录", "venue": "世博文化公园申园", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "市区江南古典园林，满池荷花盛放，汉服租赁游园、古法消夏手作、夜间园林雅集。", "source": "上海本地宝", "highlights": ["申园", "荷花", "汉服"], "type": "亲子活动"},
    {"name": "世界树之境美洲植物大展", "venue": "上海温室花园", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-11-14", "fee": "收费", "description": "凤梨羊驼、300多种美洲植物、30种龙舌兰，与上博美洲文明大展深度联动。", "source": "上海本地宝", "highlights": ["植物", "美洲", "凤梨羊驼"], "type": "展览"},
    {"name": "古猗园荷花睡莲展", "venue": "古猗园", "city": "shanghai", "district": "嘉定区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "第十三届荷花睡莲展，上百种珍稀荷花品种集中盛放，非遗荷文化研学。", "source": "上海本地宝", "highlights": ["荷花", "古猗园", "非遗"], "type": "展览"},
    {"name": "虎鲸造浪音乐节", "venue": "上海海昌海洋公园", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-11", "end_date": "2026-08-23", "fee": "收费", "description": "14位人气大咖助阵，虎鲸造浪音乐节嗨翻全场，暑期夜游必打卡。", "source": "上海旅游节", "highlights": ["音乐节", "虎鲸", "夜游"], "type": "演出"},
    {"name": "上海汽车博物馆奇妙夜", "venue": "上海汽车博物馆", "city": "shanghai", "district": "嘉定区", "start_date": "2026-07-18", "end_date": "2026-08-01", "fee": "收费", "description": "夜场延至19:30，世界汽车百年发展史公益讲解、避障小车与声控小车手作坊。", "source": "新闻晨报", "highlights": ["汽车博物馆", "奇妙夜", "手作"], "type": "亲子活动"},
    {"name": "中国汽车拓疆者饶斌特展", "venue": "上海汽车博物馆", "city": "shanghai", "district": "嘉定区", "start_date": "2026-07-25", "end_date": "2026-07-25", "fee": "收费", "description": "饶斌特展公益讲解，了解中国汽车工业拓荒者的故事。", "source": "新闻晨报", "highlights": ["饶斌", "汽车工业", "特展"], "type": "展览"},
    {"name": "真静传统木作博物馆夜游", "venue": "上海真静传统木作博物馆", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-25", "end_date": "2026-08-01", "fee": "免费", "description": "夜间展厅免费参观，体验木作工具，木作制作课筷子手镯书签鲁班锁。", "source": "新闻晨报", "highlights": ["木作", "博物馆奇妙夜", "非遗"], "type": "亲子活动"},
    {"name": "琉璃艺术博物馆夜游", "venue": "上海琉璃艺术博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-18", "end_date": "2026-08-15", "fee": "收费", "description": "熔光凝形铸造玻璃艺术展，周六夜间开放延长至20:00。", "source": "上海文旅局", "highlights": ["琉璃", "艺术", "夜游"], "type": "展览"},
    {"name": "中共一大纪念馆奇妙夜", "venue": "中共一大纪念馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-01", "end_date": "2026-08-01", "fee": "免费", "description": "会址正门夜间开放、电影党课火种、微讲座新四军臂章等红色主题夜活动。", "source": "上海文旅局", "highlights": ["一大", "红色", "奇妙夜"], "type": "讲座"},
    {"name": "乒乓体验营", "venue": "国际乒联博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-08", "end_date": "2026-07-30", "fee": "免费", "description": "中小学生乒乓体验营，了解乒乓球历史，体验国球魅力。", "source": "上海文旅局", "highlights": ["乒乓球", "体验营", "体育"], "type": "亲子活动"},
    {"name": "墨海楼藏近代名人墨展", "venue": "周虎臣曹素功笔墨博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-10", "end_date": "2026-08-28", "fee": "免费", "description": "近代名人墨知识讲座、墨锭鉴赏交流、夜间开放参观。", "source": "上海文旅局", "highlights": ["墨", "文房四宝", "讲座"], "type": "展览"},
    {"name": "世博会博物馆奇妙夜", "venue": "上海世博会博物馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-11", "end_date": "2026-08-29", "fee": "免费", "description": "周六延时开放至20:00，故宫帝后服饰展夜场、4D电影体验。", "source": "上海文旅局", "highlights": ["世博会", "奇妙夜", "故宫服饰"], "type": "亲子活动"},
    {"name": "苏河乘风凉夏季主题航班", "venue": "苏州河游船", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-08", "end_date": "2026-08-31", "fee": "收费", "description": "萌宠游船、星空晚宴、音乐Live、雅韵茶旅四大特色航线。", "source": "上海文旅局", "highlights": ["苏州河", "游船", "夜航"], "type": "亲子活动"},
    {"name": "城市草坪音乐会夏之魅", "venue": "上海城市草坪音乐广场", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-08", "end_date": "2026-08-31", "fee": "免费", "description": "连演7场的城市草坪音乐会夏之魅，夏日户外音乐盛宴。", "source": "上海文旅局", "highlights": ["音乐会", "草坪", "户外"], "type": "演出"},

    # ========== 杭州补充活动（第三批）==========
    {"name": "太平年天下同宁交互艺术大展", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-10-08", "fee": "收费", "description": "融合实物文物、数字展陈与沉浸式演出的吴越主题交互艺术大展。", "source": "杭州文广旅游局", "highlights": ["吴越", "交互艺术", "沉浸式"], "type": "展览"},
    {"name": "一剑千年吴越国纪录片特展", "venue": "钱王祠", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-10-08", "fee": "免费", "description": "展出影片海报、原创服饰道具手稿、书法篆刻作品，了解吴越国历史。", "source": "杭州文广旅游局", "highlights": ["吴越国", "纪录片", "特展"], "type": "展览"},
    {"name": "钱氏今生实景音乐剧", "venue": "钱王祠", "city": "hangzhou", "district": "西湖区", "start_date": "2026-06-24", "end_date": "2026-10-08", "fee": "收费", "description": "实景沉浸式音乐剧，以钱王浚湖治水功绩、钱氏家训传承为双主线。", "source": "杭州文广旅游局", "highlights": ["音乐剧", "钱王", "实景"], "type": "演出"},
    {"name": "临安天目未来谷水世界", "venue": "临安天目未来谷", "city": "hangzhou", "district": "临安区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "131.4米长三角最高摩天轮为网红地标，搭配多款超长超高水滑道。", "source": "杭州文广旅游局", "highlights": ["水世界", "摩天轮", "暑期"], "type": "亲子活动"},
    {"name": "临平平行世界水乐园", "venue": "临平平行世界", "city": "hangzhou", "district": "临平区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "超30000㎡室内外游玩空间，国内首创3D沉浸式造浪池、浙江首座水磁弹射过山车。", "source": "杭州文广旅游局", "highlights": ["水乐园", "造浪池", "过山车"], "type": "亲子活动"},
    {"name": "桐庐开元森泊水世界", "venue": "桐庐开元森泊", "city": "hangzhou", "district": "桐庐县", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "9200㎡恒温室内区域，龙卷风组合滑道、激流河等项目人气火爆。", "source": "杭州文广旅游局", "highlights": ["水世界", "恒温", "森泊"], "type": "亲子活动"},
    {"name": "桐庐虎啸峡漂流", "venue": "虎啸峡漂流", "city": "hangzhou", "district": "桐庐县", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "峡谷漂流全面升级，惊险刺激的夏日清凉体验。", "source": "杭州文广旅游局", "highlights": ["漂流", "峡谷", "清凉"], "type": "亲子活动"},
    {"name": "建德卧龙胜境漂流", "venue": "建德卧龙胜境", "city": "hangzhou", "district": "建德市", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "峡谷漂流全新升级，自然山水间的夏日激情体验。", "source": "杭州文广旅游局", "highlights": ["漂流", "建德", "山水"], "type": "亲子活动"},
    {"name": "灵山幻境溶洞纳凉", "venue": "灵山幻境", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "恒温溶洞纳凉点位，避暑胜地，欣赏喀斯特地貌奇观。", "source": "杭州文广旅游局", "highlights": ["溶洞", "避暑", "恒温"], "type": "亲子活动"},
    {"name": "建德灵栖洞溶洞", "venue": "建德灵栖洞", "city": "hangzhou", "district": "建德市", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "恒温溶洞纳凉，地下河泛舟，欣赏钟乳石奇观。", "source": "杭州文广旅游局", "highlights": ["溶洞", "建德", "地下河"], "type": "亲子活动"},
    {"name": "桐庐垂云通天河", "venue": "垂云通天河", "city": "hangzhou", "district": "桐庐县", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "地下河溶洞漂流，恒温清凉，欣赏亿万年形成的钟乳石。", "source": "杭州文广旅游局", "highlights": ["溶洞", "地下河", "桐庐"], "type": "亲子活动"},
    {"name": "杭州奇妙夜天目里主场", "venue": "天目里", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "7月奇妙夜主场，集聚夜游科技、吴越文博、国潮市集、剧本游等业态。", "source": "杭州文广旅游局", "highlights": ["奇妙夜", "天目里", "夜游"], "type": "演出"},
    {"name": "百日星悦游活动", "venue": "杭州全域", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-03", "end_date": "2026-10-10", "fee": "免费", "description": "为期100天的百日星悦游，覆盖暑假中秋国庆，激活夜间文旅消费。", "source": "杭州文广旅游局", "highlights": ["夜游", "百日", "全域"], "type": "演出"},
    {"name": "大英图书馆奇喵史展", "venue": "浙江图书馆之江馆区", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-04", "end_date": "2026-10-08", "fee": "收费", "description": "超多互动小游戏，适合亲子情侣打卡，氛围温柔治愈。", "source": "七月看展指南", "highlights": ["大英图书馆", "亲子", "互动"], "type": "展览"},
    {"name": "秉灯照麒麟盗墓笔记大展", "venue": "西泠印社美术馆", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-08", "end_date": "2026-10-08", "fee": "免费", "description": "盗墓笔记官方大展，四大沉浸剧情展区，情怀与仪式感交织。", "source": "七月看展指南", "highlights": ["盗墓笔记", "沉浸式", "IP"], "type": "展览"},
    {"name": "古希腊的旅程文物展", "venue": "良渚博物院", "city": "hangzhou", "district": "余杭区", "start_date": "2026-01-30", "end_date": "2026-07-31", "fee": "免费", "description": "31家机构163件精品文物与复制品，从基克拉迪抱臂人像到桃金娘金冠。", "source": "七月看展指南", "highlights": ["古希腊", "文物", "良渚"], "type": "展览"},
    {"name": "纸见吴越非遗剪纸展", "venue": "临安博物馆", "city": "hangzhou", "district": "临安区", "start_date": "2026-06-18", "end_date": "2026-10-07", "fee": "免费", "description": "全国非遗剪纸优秀作品展，四个单元展现吴越文化与剪纸艺术。", "source": "杭州文广旅游局", "highlights": ["剪纸", "非遗", "吴越"], "type": "展览"},
    {"name": "大道匠行浙江工艺美术展", "venue": "杭州工艺美术博物馆", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-06-26", "end_date": "2026-10-12", "fee": "免费", "description": "龙泉青瓷、东阳木雕、青田石雕、杭州扇艺等浙江百工技艺集中展示。", "source": "杭州文广旅游局", "highlights": ["工艺美术", "浙江", "非遗"], "type": "展览"},
    {"name": "印说中国故事大运河篆刻展", "venue": "中国刀剪剑博物馆", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-06-22", "end_date": "2026-07-21", "fee": "免费", "description": "大运河主题篆刻艺术巡回邀请展，3200公里大运河浓缩于方寸印章。", "source": "杭州文广旅游局", "highlights": ["篆刻", "大运河", "印章"], "type": "展览"},
    {"name": "月照银山丝路文明展", "venue": "中国丝绸博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-06-24", "end_date": "2026-09-21", "fee": "免费", "description": "展出200余件藏品，串联丝路文明精彩，展现中华文明多元一体。", "source": "七月看展指南", "highlights": ["丝路", "丝绸", "文明"], "type": "展览"},
    {"name": "窑火瓷韵陶瓷展", "venue": "浙江大学艺术与考古博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-05-15", "end_date": "2026-09-15", "fee": "免费", "description": "陶瓷艺术专题展，欣赏历代瓷器精品与窑火传承。", "source": "七月看展指南", "highlights": ["陶瓷", "浙大", "考古"], "type": "展览"},
    {"name": "拓印体验课印纹硬陶", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-16", "end_date": "2026-07-16", "fee": "免费", "description": "从印纹硬陶出发，了解纹饰流行趋势，拓印独一无二的作品。", "source": "浙江省博物馆", "highlights": ["拓印", "印纹硬陶", "手工"], "type": "亲子活动"},
    {"name": "线装书制作体验", "venue": "浙江省博物馆孤山馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-18", "end_date": "2026-07-18", "fee": "免费", "description": "亲手制作专属于自己的线装书，感受古法书籍装帧的文澜雅韵。", "source": "浙江省博物馆", "highlights": ["线装书", "古籍", "手工"], "type": "亲子活动"},
    {"name": "夏日手作小集", "venue": "浙江省博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "DIY扇子、夏日印章限时登场，方寸之间文脉流转，一拓一印清凉自来。", "source": "浙江省博物馆", "highlights": ["手作", "扇子", "集章"], "type": "亲子活动"},
    {"name": "敦煌壁画彩绘课程", "venue": "浙江省博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "跟随常书鸿的脚步，在古法纸上勾勒填彩壁画图样，感受敦煌传统美学。", "source": "浙江省博物馆", "highlights": ["敦煌", "壁画", "彩绘"], "type": "亲子活动"},
    {"name": "瓦当拓印课程", "venue": "浙江省博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "宋六陵遗址出土瓦当拓印体验，感受瓦当纹样的精巧艺术智慧。", "source": "浙江省博物馆", "highlights": ["瓦当", "拓印", "宋六陵"], "type": "亲子活动"},
    {"name": "浙博寻宝未成年研学", "venue": "浙江省博物馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "暑期持续开展浙博寻宝研学，精心设计研学手册，逛展厅赏文物学知识。", "source": "浙江省博物馆", "highlights": ["寻宝", "研学", "博物馆"], "type": "亲子活动"},
    {"name": "古琴雅会", "venue": "浙江省博物馆之江馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "古琴馆文人琴房古琴展演，听杳杳琴音品千年雅韵，沉浸式音乐体验。", "source": "浙江省博物馆", "highlights": ["古琴", "雅集", "音乐"], "type": "演出"},
    {"name": "盖派英姿张大根绘画展", "venue": "盖叫天故居", "city": "hangzhou", "district": "西湖区", "start_date": "2026-06-23", "end_date": "2026-07-19", "fee": "免费", "description": "京剧非遗与水墨艺术融合，盖派艺术从唱念做打到丹青绘意的跨界传承。", "source": "杭州文广旅游局", "highlights": ["盖叫天", "绘画", "京剧"], "type": "展览"},
]

if __name__ == '__main__':
    if not os.path.exists(DATA_FILE):
        print(f"文件 {DATA_FILE} 不存在！")
        exit(1)
    
    with open(DATA_FILE, 'r', encoding='utf-8') as f:
        exhibitions = json.load(f)
    
    existing_names = {e['name'] for e in exhibitions}
    added_count = 0
    
    for activity in new_activities:
        if activity['name'] not in existing_names:
            exhibitions.append(activity)
            print(f"添加: {activity['name']} ({activity['city']})")
            added_count += 1
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(exhibitions, f, ensure_ascii=False, indent=2)
    
    print(f"\n共添加 {added_count} 个活动")
    
    city_counts = {}
    for e in exhibitions:
        city_counts[e['city']] = city_counts.get(e['city'], 0) + 1
    print(f"\n各城市活动数量:")
    for city, count in sorted(city_counts.items()):
        print(f"  {city}: {count}")
