import json

new_venues = [
    {
        "name": "北京植物园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区香山路",
        "transport": "地铁西郊线植物园站",
        "fee": "收费",
        "description": "北京最大的植物园，有温室展览区、樱桃沟、曹雪芹纪念馆等，适合亲子自然探索。",
        "official_url": "",
        "highlights": ["温室", "樱桃沟", "自然探索"]
    },
    {
        "name": "颐和园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区新建宫门路19号",
        "transport": "地铁4号线北宫门站",
        "fee": "收费",
        "description": "中国现存规模最大、保存最完整的皇家园林，昆明湖、长廊、佛香阁等景点闻名。",
        "official_url": "",
        "highlights": ["皇家园林", "昆明湖", "长廊"]
    },
    {
        "name": "天坛公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "公园",
        "address": "东城区天坛东路甲1号",
        "transport": "地铁5号线天坛东门站",
        "fee": "收费",
        "description": "明清两代皇帝祭天祈谷的场所，祈年殿、皇穹宇、圜丘等建筑宏伟壮观。",
        "official_url": "",
        "highlights": ["祈年殿", "祭天", "古建筑"]
    },
    {
        "name": "地坛公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "公园",
        "address": "东城区安定门外大街",
        "transport": "地铁2号线安定门站",
        "fee": "收费",
        "description": "明清两代皇帝祭地的场所，有方泽坛、皇祇室等建筑，园内有书市和庙会。",
        "official_url": "",
        "highlights": ["方泽坛", "祭地", "书市"]
    },
    {
        "name": "北海公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "公园",
        "address": "西城区文津街1号",
        "transport": "地铁6号线北海北站",
        "fee": "收费",
        "description": "中国现存最古老、最完整、最具综合性和代表性的皇家园林之一，白塔、九龙壁闻名。",
        "official_url": "",
        "highlights": ["白塔", "九龙壁", "皇家园林"]
    },
    {
        "name": "景山公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "公园",
        "address": "西城区景山西街44号",
        "transport": "地铁1号线神武门站",
        "fee": "收费",
        "description": "位于故宫北侧，登上万春亭可俯瞰故宫全景和北京中轴线。",
        "official_url": "",
        "highlights": ["万春亭", "俯瞰故宫", "中轴线"]
    },
    {
        "name": "中山公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "公园",
        "address": "西城区西长安街2号",
        "transport": "地铁1号线天安门西站",
        "fee": "收费",
        "description": "位于天安门西侧，有社稷坛、中山堂等景点，是市民休闲好去处。",
        "official_url": "",
        "highlights": ["社稷坛", "中山堂", "休闲"]
    },
    {
        "name": "劳动人民文化宫",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "文化中心",
        "address": "东城区太庙路",
        "transport": "地铁1号线天安门东站",
        "fee": "免费",
        "description": "位于天安门东侧，原为太庙，现为文化活动场所，有展览和演出。",
        "official_url": "",
        "highlights": ["太庙", "展览", "文化活动"]
    },
    {
        "name": "北京天文馆A馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科普馆",
        "address": "西城区西直门外大街138号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "北京天文馆A馆，设有天象厅、展览厅，球幕电影体验震撼。",
        "official_url": "",
        "highlights": ["天象厅", "球幕电影"]
    },
    {
        "name": "北京天文馆B馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科普馆",
        "address": "西城区西直门外大街138号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "北京天文馆B馆，有太阳观测、陨石展览、互动体验区。",
        "official_url": "",
        "highlights": ["太阳观测", "陨石", "互动体验"]
    },
    {
        "name": "北京展览馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "会展中心",
        "address": "西城区西直门外大街135号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "大型展览馆，举办各类展览和活动，建筑风格独特。",
        "official_url": "",
        "highlights": ["展览", "建筑风格"]
    },
    {
        "name": "中国美术馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "美术馆",
        "address": "东城区五四大街1号",
        "transport": "地铁8号线中国美术馆站",
        "fee": "免费",
        "description": "中国国家级美术馆，收藏和展示国内外优秀美术作品。",
        "official_url": "",
        "highlights": ["美术展览", "国家级", "免费"]
    },
    {
        "name": "北京音乐厅",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "演出场馆",
        "address": "西城区北新华街1号",
        "transport": "地铁1号线西单站",
        "fee": "收费",
        "description": "北京知名音乐厅，举办交响乐、室内乐等音乐会。",
        "official_url": "",
        "highlights": ["交响乐", "音乐会"]
    },
    {
        "name": "国家大剧院",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "演出场馆",
        "address": "西城区西长安街2号",
        "transport": "地铁1号线天安门西站",
        "fee": "收费",
        "description": "中国国家表演艺术中心，有歌剧院、音乐厅、戏剧场等，建筑造型独特。",
        "official_url": "",
        "highlights": ["歌剧院", "建筑造型", "表演艺术"]
    },
    {
        "name": "梅兰芳大剧院",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "演出场馆",
        "address": "西城区平安里西大街32号",
        "transport": "地铁4号线平安里站",
        "fee": "收费",
        "description": "以京剧大师梅兰芳命名的剧院，演出京剧、戏曲等。",
        "official_url": "",
        "highlights": ["京剧", "戏曲"]
    },
    {
        "name": "长安大戏院",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "演出场馆",
        "address": "东城区建国门内大街7号",
        "transport": "地铁1号线建国门站",
        "fee": "收费",
        "description": "北京老字号戏院，演出京剧、曲艺等传统戏曲。",
        "official_url": "",
        "highlights": ["京剧", "传统戏曲", "老字号"]
    },
    {
        "name": "北京儿艺剧场",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "演出场馆",
        "address": "东城区交道口东大街85号",
        "transport": "地铁5号线北新桥站",
        "fee": "收费",
        "description": "北京儿童艺术剧院，演出儿童剧、亲子剧等。",
        "official_url": "",
        "highlights": ["儿童剧", "亲子剧"]
    },
    {
        "name": "北京展览馆剧场",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "演出场馆",
        "address": "西城区西直门外大街135号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "北京展览馆内的剧场，举办演唱会、话剧等演出。",
        "official_url": "",
        "highlights": ["演唱会", "话剧"]
    },
    {
        "name": "北京工人体育馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "体育中心",
        "address": "朝阳区三里屯路11号",
        "transport": "地铁10号线团结湖站",
        "fee": "收费",
        "description": "大型体育场馆，举办体育赛事和演唱会。",
        "official_url": "",
        "highlights": ["体育赛事", "演唱会"]
    },
    {
        "name": "北京工人体育场",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "体育中心",
        "address": "朝阳区工人体育场北路",
        "transport": "地铁2号线东四十条站",
        "fee": "收费",
        "description": "大型足球场，举办足球比赛和大型活动。",
        "official_url": "",
        "highlights": ["足球", "体育赛事"]
    },
    {
        "name": "五棵松体育馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "体育中心",
        "address": "海淀区复兴路69号",
        "transport": "地铁1号线五棵松站",
        "fee": "收费",
        "description": "大型室内体育馆，举办篮球比赛和演唱会。",
        "official_url": "",
        "highlights": ["篮球", "演唱会"]
    },
    {
        "name": "奥林匹克森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区科荟路33号",
        "transport": "地铁8号线奥林匹克公园站",
        "fee": "免费",
        "description": "北京奥林匹克公园内的大型森林公园，有南园、北园，适合散步、跑步、骑行。",
        "official_url": "",
        "highlights": ["森林公园", "散步", "骑行", "免费"]
    },
    {
        "name": "元大都城垣遗址公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区安定路",
        "transport": "地铁5号线惠新西街北口站",
        "fee": "免费",
        "description": "元大都城墙遗址公园，有海棠花溪等景点，春季海棠盛开时很美。",
        "official_url": "",
        "highlights": ["城墙遗址", "海棠花溪", "免费"]
    },
    {
        "name": "奥林匹克公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区国家体育场南路",
        "transport": "地铁8号线奥林匹克公园站",
        "fee": "免费",
        "description": "包含鸟巢、水立方等奥运场馆，是市民休闲和旅游的好去处。",
        "official_url": "",
        "highlights": ["鸟巢", "水立方", "奥运场馆", "免费"]
    },
    {
        "name": "朝阳公园海洋沙滩狂欢节",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区朝阳公园南路1号",
        "transport": "地铁14号线朝阳公园站",
        "fee": "收费",
        "description": "夏季举办的大型水上活动，有沙滩、泳池、表演等。",
        "official_url": "",
        "highlights": ["沙滩", "水上活动", "夏季"]
    },
    {
        "name": "蟹岛度假村",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区蟹岛路1号",
        "transport": "公交641路",
        "fee": "收费",
        "description": "综合性度假村，有温泉、水上乐园、采摘园等，适合亲子度假。",
        "official_url": "",
        "highlights": ["温泉", "水上乐园", "采摘"]
    },
    {
        "name": "南宫旅游景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "公园",
        "address": "丰台区王佐镇",
        "transport": "公交321路",
        "fee": "收费",
        "description": "集温泉、公园、动物园于一体的旅游景区，适合亲子游玩。",
        "official_url": "",
        "highlights": ["温泉", "动物园", "亲子"]
    },
    {
        "name": "北京莲花池公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "公园",
        "address": "丰台区广安门外大街",
        "transport": "地铁9号线北京西站",
        "fee": "免费",
        "description": "古老的莲花池遗址公园，夏季荷花盛开，景色优美。",
        "official_url": "",
        "highlights": ["荷花", "遗址公园", "免费"]
    },
    {
        "name": "北京世界花卉大观园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "公园",
        "address": "丰台区南四环中路235号",
        "transport": "地铁8号线德茂庄站",
        "fee": "收费",
        "description": "大型花卉博览园，有多个温室展馆，展示各种花卉植物。",
        "official_url": "",
        "highlights": ["花卉", "温室", "博览园"]
    },
    {
        "name": "北京园博园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "公园",
        "address": "丰台区射击场路15号",
        "transport": "地铁14号线园博园站",
        "fee": "收费",
        "description": "第九届中国国际园林博览会举办地，有多个展园和园林景观。",
        "official_url": "",
        "highlights": ["园林景观", "展园", "园博会"]
    },
    {
        "name": "北京石景山游乐园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "石景山区",
        "type": "公园",
        "address": "石景山区石景山路25号",
        "transport": "地铁1号线八角游乐园站",
        "fee": "收费",
        "description": "北京老牌游乐园，有摩天轮、过山车等游乐设施。",
        "official_url": "",
        "highlights": ["摩天轮", "过山车", "游乐园"]
    },
    {
        "name": "八大处公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "石景山区",
        "type": "公园",
        "address": "石景山区八大处路3号",
        "transport": "公交347路",
        "fee": "收费",
        "description": "位于西山风景区，有八座古刹，景色秀丽，适合登山祈福。",
        "official_url": "",
        "highlights": ["古刹", "登山", "祈福"]
    },
    {
        "name": "法海寺",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "石景山区",
        "type": "博物馆",
        "address": "石景山区模式口大街",
        "transport": "公交336路",
        "fee": "收费",
        "description": "明代古寺，以精美的壁画闻名，是全国重点文物保护单位。",
        "official_url": "",
        "highlights": ["壁画", "古寺", "文物"]
    },
    {
        "name": "首钢园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "石景山区",
        "type": "文化中心",
        "address": "石景山区首钢大街",
        "transport": "地铁11号线新首钢站",
        "fee": "免费",
        "description": "首钢工业遗址改造的文化创意园区，有冬奥会相关设施和展览。",
        "official_url": "",
        "highlights": ["工业遗址", "冬奥会", "文创", "免费"]
    },
    {
        "name": "北京国际雕塑公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "石景山区",
        "type": "公园",
        "address": "石景山区石景山路2号",
        "transport": "地铁1号线玉泉路站",
        "fee": "免费",
        "description": "以雕塑为主题的公园，有国内外雕塑作品展示。",
        "official_url": "",
        "highlights": ["雕塑", "艺术", "免费"]
    },
    {
        "name": "百望山森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区黑山扈北口19号",
        "transport": "公交330路",
        "fee": "收费",
        "description": "北京西北郊的森林公园，适合登山远眺，秋季红叶很美。",
        "official_url": "",
        "highlights": ["登山", "红叶", "远眺"]
    },
    {
        "name": "凤凰岭自然风景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区苏家坨镇",
        "transport": "公交346路",
        "fee": "收费",
        "description": "北京西山风景区，有山、水、林、寺等景观，适合户外徒步。",
        "official_url": "",
        "highlights": ["徒步", "自然风光", "寺庙"]
    },
    {
        "name": "鹫峰国家森林公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区苏家坨镇",
        "transport": "公交346路",
        "fee": "收费",
        "description": "以鹫峰为中心的森林公园，有登山步道和自然风光。",
        "official_url": "",
        "highlights": ["登山", "森林", "自然风光"]
    },
    {
        "name": "阳台山自然风景区",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区苏家坨镇",
        "transport": "公交346路",
        "fee": "收费",
        "description": "北京西山风景区，有古香道、金山寺等景点，适合登山。",
        "official_url": "",
        "highlights": ["古香道", "金山寺", "登山"]
    },
    {
        "name": "香山公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区买卖街40号",
        "transport": "地铁西郊线香山站",
        "fee": "收费",
        "description": "北京著名的森林公园，秋季红叶闻名，有碧云寺、琉璃塔等景点。",
        "official_url": "",
        "highlights": ["红叶", "碧云寺", "登山"]
    },
    {
        "name": "北京植物园樱桃沟",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "公园",
        "address": "海淀区香山路北京植物园内",
        "transport": "地铁西郊线植物园站",
        "fee": "收费",
        "description": "樱桃沟景区，有木栈道、水杉林、喷雾景观等，夏季凉爽宜人。",
        "official_url": "",
        "highlights": ["水杉林", "喷雾", "凉爽"]
    },
    {
        "name": "北京植物园温室",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "科普馆",
        "address": "海淀区香山路北京植物园内",
        "transport": "地铁西郊线植物园站",
        "fee": "收费",
        "description": "大型温室展览区，展示热带、亚热带植物，适合亲子自然教育。",
        "official_url": "",
        "highlights": ["热带植物", "温室", "自然教育"]
    },
    {
        "name": "北京天文馆天象厅",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科普馆",
        "address": "西城区西直门外大街138号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "北京天文馆A馆天象厅，球幕电影体验震撼，展示宇宙星空。",
        "official_url": "",
        "highlights": ["球幕电影", "宇宙星空"]
    },
    {
        "name": "中国科学技术馆儿童科学乐园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "科技馆",
        "address": "朝阳区北辰东路5号",
        "transport": "地铁8号线奥林匹克公园站",
        "fee": "收费",
        "description": "专为3-8岁儿童设计的科学乐园，互动性强，寓教于乐。",
        "official_url": "",
        "highlights": ["3-8岁", "互动体验", "科学启蒙"]
    },
    {
        "name": "广州图书馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "图书馆",
        "address": "天河区珠江东路4号",
        "transport": "地铁3号线大剧院站",
        "fee": "免费",
        "description": "广州大型公共图书馆，有丰富的馆藏资源和阅读空间。",
        "official_url": "",
        "highlights": ["阅读", "馆藏丰富", "免费"]
    },
    {
        "name": "广州大剧院",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "演出场馆",
        "address": "天河区珠江新城珠江西路1号",
        "transport": "地铁3号线大剧院站",
        "fee": "收费",
        "description": "广州标志性建筑，举办歌剧、音乐剧、音乐会等演出。",
        "official_url": "",
        "highlights": ["建筑设计", "歌剧", "音乐会"]
    },
    {
        "name": "广州塔",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "文化中心",
        "address": "海珠区阅江西路222号",
        "transport": "地铁3号线广州塔站",
        "fee": "收费",
        "description": "广州地标性建筑，可登塔俯瞰广州全景，有摩天轮、极速云霄等项目。",
        "official_url": "",
        "highlights": ["登高观光", "摩天轮", "地标"]
    },
    {
        "name": "广州国际金融城",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区黄埔大道",
        "transport": "地铁5号线科韵路站",
        "fee": "免费",
        "description": "广州新城区，有现代化建筑和城市景观，适合拍照打卡。",
        "official_url": "",
        "highlights": ["现代化", "城市景观", "拍照"]
    },
    {
        "name": "广州北京路步行街",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "文化中心",
        "address": "越秀区北京路",
        "transport": "地铁1号线公园前站",
        "fee": "免费",
        "description": "广州著名的商业步行街，有历史文化景点和购物美食。",
        "official_url": "",
        "highlights": ["购物", "美食", "历史文化"]
    },
    {
        "name": "广州上下九步行街",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "荔湾区",
        "type": "文化中心",
        "address": "荔湾区上下九路",
        "transport": "地铁1号线长寿路站",
        "fee": "免费",
        "description": "广州传统商业步行街，有西关风情和特色小吃。",
        "official_url": "",
        "highlights": ["西关风情", "特色小吃", "购物"]
    },
    {
        "name": "广州天河城",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区天河路208号",
        "transport": "地铁3号线体育西路站",
        "fee": "免费",
        "description": "广州大型购物中心，有购物、餐饮、娱乐等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮", "娱乐"]
    },
    {
        "name": "广州太古汇",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区天河路383号",
        "transport": "地铁3号线石牌桥站",
        "fee": "免费",
        "description": "高端购物中心，有奢侈品品牌和特色餐饮。",
        "official_url": "",
        "highlights": ["高端购物", "奢侈品", "餐饮"]
    },
    {
        "name": "广州正佳广场",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区天河路228号",
        "transport": "地铁3号线体育西路站",
        "fee": "免费",
        "description": "大型商业综合体，有海洋世界、雨林植物园、自然科学博物馆等。",
        "official_url": "",
        "highlights": ["商业综合体", "海洋世界", "博物馆"]
    },
    {
        "name": "广州万菱汇",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "文化中心",
        "address": "天河区天河路230号",
        "transport": "地铁3号线石牌桥站",
        "fee": "免费",
        "description": "购物中心，有时尚品牌和特色餐饮。",
        "official_url": "",
        "highlights": ["时尚购物", "餐饮"]
    },
    {
        "name": "广州凯德广场",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "白云区",
        "type": "文化中心",
        "address": "白云区云城西路890号",
        "transport": "地铁2号线白云公园站",
        "fee": "免费",
        "description": "白云区大型购物中心，有购物、餐饮、娱乐等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮", "白云区"]
    },
    {
        "name": "广州白云万达广场",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "白云区",
        "type": "文化中心",
        "address": "白云区云城东路501号",
        "transport": "地铁2号线飞翔公园站",
        "fee": "免费",
        "description": "大型商业综合体，有购物、餐饮、影院等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮", "影院"]
    },
    {
        "name": "广州越秀公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区解放北路960号",
        "transport": "地铁2号线越秀公园站",
        "fee": "免费",
        "description": "广州最大的综合性公园，有五羊雕像、镇海楼、金印游乐场等景点。",
        "official_url": "",
        "highlights": ["五羊雕像", "镇海楼", "金印游乐场", "免费"]
    },
    {
        "name": "广州流花湖公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区流花路100号",
        "transport": "地铁2号线越秀公园站",
        "fee": "免费",
        "description": "以湖景为特色的公园，有流花湖、玫瑰园等景点，环境优美。",
        "official_url": "",
        "highlights": ["湖景", "玫瑰园", "环境优美", "免费"]
    },
    {
        "name": "广州荔湾湖公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "荔湾区",
        "type": "公园",
        "address": "荔湾区龙津西路155号",
        "transport": "地铁1号线长寿路站",
        "fee": "免费",
        "description": "位于荔湾区的公园，有湖景和西关风情，周边有泮塘美食。",
        "official_url": "",
        "highlights": ["湖景", "西关风情", "美食", "免费"]
    },
    {
        "name": "广州海珠湖公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "公园",
        "address": "海珠区新滘中路",
        "transport": "地铁3号线大塘站",
        "fee": "免费",
        "description": "海珠湿地公园内的湖景公园，有环湖步道和自然景观。",
        "official_url": "",
        "highlights": ["湖景", "环湖步道", "自然", "免费"]
    },
    {
        "name": "广州天河公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "公园",
        "address": "天河区中山大道西270号",
        "transport": "地铁21号线天河公园站",
        "fee": "免费",
        "description": "天河区大型公园，有湖景、草坪、游乐设施，适合亲子游玩。",
        "official_url": "",
        "highlights": ["湖景", "草坪", "游乐设施", "免费"]
    },
    {
        "name": "广州珠江公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "公园",
        "address": "天河区金穗路",
        "transport": "地铁3号线体育西路站",
        "fee": "免费",
        "description": "珠江新城内的公园，有草坪、水景、雕塑，环境优美。",
        "official_url": "",
        "highlights": ["草坪", "水景", "环境优美", "免费"]
    },
    {
        "name": "广州麓湖公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区麓湖路11号",
        "transport": "公交10路",
        "fee": "免费",
        "description": "位于白云山脚下的公园，有湖景和自然景观，环境清幽。",
        "official_url": "",
        "highlights": ["湖景", "白云山", "清幽", "免费"]
    },
    {
        "name": "广州东山湖公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区东湖路123号",
        "transport": "地铁6号线东湖站",
        "fee": "免费",
        "description": "位于东山的公园，有湖景和亭台楼阁，适合休闲散步。",
        "official_url": "",
        "highlights": ["湖景", "亭台楼阁", "休闲", "免费"]
    },
    {
        "name": "广州二沙岛",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区二沙岛",
        "transport": "地铁6号线东湖站",
        "fee": "免费",
        "description": "珠江中的小岛，有大草坪、艺术公园、体育公园等，是广州塔最佳拍摄点。",
        "official_url": "",
        "highlights": ["大草坪", "广州塔拍摄", "艺术公园", "免费"]
    },
    {
        "name": "广州沙面岛",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "荔湾区",
        "type": "文化中心",
        "address": "荔湾区沙面南街",
        "transport": "地铁1号线黄沙站",
        "fee": "免费",
        "description": "珠江中的小岛，有欧式建筑和领事馆旧址，适合拍照打卡。",
        "official_url": "",
        "highlights": ["欧式建筑", "领事馆", "拍照", "免费"]
    },
    {
        "name": "广州长隆野生动物世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区大石镇",
        "transport": "地铁3号线汉溪长隆站",
        "fee": "收费",
        "description": "全球最大的动物园区之一，可以乘坐小火车或自驾游，近距离观赏野生动物。",
        "official_url": "",
        "highlights": ["野生动物", "小火车", "自驾"]
    },
    {
        "name": "广州长隆欢乐世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区大石镇",
        "transport": "地铁3号线汉溪长隆站",
        "fee": "收费",
        "description": "大型主题乐园，有刺激项目和儿童区，适合全年龄段游玩。",
        "official_url": "",
        "highlights": ["主题乐园", "刺激项目", "儿童区"]
    },
    {
        "name": "广州长隆水上乐园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区大石镇",
        "transport": "地铁3号线汉溪长隆站",
        "fee": "收费",
        "description": "大型水上乐园，有各种滑道、造浪池、漂流河等，夏季玩水好去处。",
        "official_url": "",
        "highlights": ["水上乐园", "滑道", "造浪池"]
    },
    {
        "name": "广州长隆飞鸟乐园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区大石镇",
        "transport": "地铁3号线汉溪长隆站",
        "fee": "收费",
        "description": "以鸟类为主题的乐园，有各种珍稀鸟类和表演。",
        "official_url": "",
        "highlights": ["鸟类", "表演", "珍稀动物"]
    },
    {
        "name": "广州融创雪世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区凤凰北路78号",
        "transport": "地铁9号线花城路站",
        "fee": "收费",
        "description": "华南地区最大的室内滑雪场，一年四季都可以滑雪。",
        "official_url": "",
        "highlights": ["室内滑雪", "四季滑雪"]
    },
    {
        "name": "广州融创水世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区凤凰北路78号",
        "transport": "地铁9号线花城路站",
        "fee": "收费",
        "description": "四季恒温的室内水世界，有各种水上项目和儿童戏水区。",
        "official_url": "",
        "highlights": ["室内水世界", "四季恒温", "儿童戏水"]
    },
    {
        "name": "广州融创体育世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区凤凰北路78号",
        "transport": "地铁9号线花城路站",
        "fee": "收费",
        "description": "大型室内体育乐园，有各种运动项目和娱乐设施。",
        "official_url": "",
        "highlights": ["体育乐园", "运动项目"]
    },
    {
        "name": "广州花都湖公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区商业大道",
        "transport": "地铁9号线花果山公园站",
        "fee": "免费",
        "description": "花都区大型公园，有湖景和绿道，适合骑行和散步。",
        "official_url": "",
        "highlights": ["湖景", "绿道", "骑行", "免费"]
    },
    {
        "name": "广州增城白水寨",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "增城区",
        "type": "公园",
        "address": "增城区派潭镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "有落差428.5米的白水仙瀑，是广东最大的瀑布，适合登山观景。",
        "official_url": "",
        "highlights": ["瀑布", "登山", "观景"]
    },
    {
        "name": "广州从化温泉",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "从化区",
        "type": "公园",
        "address": "从化区温泉镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "著名的温泉度假区，有各种温泉酒店和度假村。",
        "official_url": "",
        "highlights": ["温泉", "度假"]
    },
    {
        "name": "广州从化溪头村",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "从化区",
        "type": "公园",
        "address": "从化区良口镇",
        "transport": "自驾",
        "fee": "免费",
        "description": "广州最美乡村之一，有溪流、竹林、田园风光，适合亲子游。",
        "official_url": "",
        "highlights": ["乡村", "溪流", "田园风光", "免费"]
    },
    {
        "name": "广州南沙湿地公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "南沙区",
        "type": "公园",
        "address": "南沙区万顷沙镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "大型湿地公园，有红树林、芦苇荡、候鸟栖息地，适合观鸟。",
        "official_url": "",
        "highlights": ["湿地", "红树林", "观鸟"]
    },
    {
        "name": "广州南沙天后宫",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "南沙区",
        "type": "文化中心",
        "address": "南沙区大角山东南麓",
        "transport": "自驾",
        "fee": "收费",
        "description": "东南亚最大的妈祖庙，有古建筑和海景，适合祈福和观光。",
        "official_url": "",
        "highlights": ["妈祖庙", "古建筑", "海景"]
    },
    {
        "name": "广州黄埔军校旧址",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "博物馆",
        "address": "黄埔区长洲岛",
        "transport": "公交383路",
        "fee": "免费",
        "description": "中国近代著名军事院校旧址，展示军校历史和文物。",
        "official_url": "",
        "highlights": ["军校历史", "文物", "红色旅游", "免费"]
    },
    {
        "name": "广州南海神庙",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "文化中心",
        "address": "黄埔区庙头村",
        "transport": "地铁13号线夏园站",
        "fee": "收费",
        "description": "中国古代海上丝绸之路的起点，有古建筑和庙会活动。",
        "official_url": "",
        "highlights": ["海上丝绸之路", "古建筑", "庙会"]
    },
    {
        "name": "广州艺术博物院",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "美术馆",
        "address": "越秀区麓湖路13号",
        "transport": "地铁5号线小北站",
        "fee": "免费",
        "description": "展示古今中外艺术作品，有岭南画派作品、历代书画等展览。",
        "official_url": "",
        "highlights": ["艺术展览", "岭南画派", "免费"]
    },
    {
        "name": "广州南越王宫博物馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区中山四路316号",
        "transport": "地铁1号线农讲所站",
        "fee": "免费",
        "description": "展示南越王宫遗址和文物，了解南越国历史。",
        "official_url": "",
        "highlights": ["王宫遗址", "南越国", "文物", "免费"]
    },
    {
        "name": "广州北京路千年古道遗址",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区北京路",
        "transport": "地铁1号线公园前站",
        "fee": "免费",
        "description": "北京路地下的千年古道遗址，展示广州历史变迁。",
        "official_url": "",
        "highlights": ["古道遗址", "历史变迁", "免费"]
    },
    {
        "name": "广州粤剧艺术博物馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "荔湾区",
        "type": "博物馆",
        "address": "荔湾区恩宁路127号",
        "transport": "地铁1号线黄沙站",
        "fee": "免费",
        "description": "展示粤剧艺术和历史，有粤剧表演和展览。",
        "official_url": "",
        "highlights": ["粤剧", "表演", "历史", "免费"]
    },
    {
        "name": "广州三二九起义指挥部旧址",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区越华路116号",
        "transport": "地铁1号线公园前站",
        "fee": "免费",
        "description": "辛亥革命重要历史遗址，展示起义历史和文物。",
        "official_url": "",
        "highlights": ["辛亥革命", "历史遗址", "免费"]
    },
    {
        "name": "广州起义烈士陵园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区中山三路",
        "transport": "地铁1号线烈士陵园站",
        "fee": "免费",
        "description": "纪念广州起义的烈士陵园，有纪念碑、纪念馆等。",
        "official_url": "",
        "highlights": ["烈士陵园", "纪念", "红色旅游", "免费"]
    },
    {
        "name": "广州鲁迅纪念馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区文明路215号",
        "transport": "地铁1号线农讲所站",
        "fee": "免费",
        "description": "展示鲁迅先生在广州的生活和工作，有文物和文献。",
        "official_url": "",
        "highlights": ["鲁迅", "文物", "文献", "免费"]
    },
    {
        "name": "广州近代史博物馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区陵园西路2号",
        "transport": "地铁1号线烈士陵园站",
        "fee": "免费",
        "description": "展示广州近代史，有文物和历史资料。",
        "official_url": "",
        "highlights": ["近代史", "文物", "历史资料", "免费"]
    },
    {
        "name": "广州农民运动讲习所旧址",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区中山四路42号",
        "transport": "地铁1号线农讲所站",
        "fee": "免费",
        "description": "第一次国内革命战争时期培养农民运动干部的学校旧址。",
        "official_url": "",
        "highlights": ["农民运动", "革命历史", "免费"]
    },
    {
        "name": "广州南越王墓博物馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区解放北路867号",
        "transport": "地铁2号线越秀公园站",
        "fee": "免费",
        "description": "展示南越王墓出土文物，包括金缕玉衣等珍贵文物。",
        "official_url": "",
        "highlights": ["南越王墓", "金缕玉衣", "文物", "免费"]
    },
    {
        "name": "上海图书馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "图书馆",
        "address": "徐汇区淮海中路1555号",
        "transport": "地铁10号线上海图书馆站",
        "fee": "免费",
        "description": "上海大型公共图书馆，有丰富的馆藏资源和阅读空间。",
        "official_url": "",
        "highlights": ["阅读", "馆藏丰富", "免费"]
    },
    {
        "name": "上海美术馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "美术馆",
        "address": "浦东新区上南路205号",
        "transport": "地铁8号线中华艺术宫站",
        "fee": "免费",
        "description": "中华艺术宫内的美术馆，展示国内外优秀美术作品。",
        "official_url": "",
        "highlights": ["美术展览", "中华艺术宫", "免费"]
    },
    {
        "name": "上海大剧院",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "演出场馆",
        "address": "黄浦区人民大道300号",
        "transport": "地铁1号线人民广场站",
        "fee": "收费",
        "description": "上海标志性剧院，举办歌剧、音乐剧、音乐会等演出。",
        "official_url": "",
        "highlights": ["歌剧", "音乐剧", "建筑设计"]
    },
    {
        "name": "上海音乐厅",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "演出场馆",
        "address": "黄浦区延安东路523号",
        "transport": "地铁1号线人民广场站",
        "fee": "收费",
        "description": "上海知名音乐厅，举办交响乐、室内乐等音乐会。",
        "official_url": "",
        "highlights": ["交响乐", "音乐会"]
    },
    {
        "name": "上海马戏城",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "静安区",
        "type": "演出场馆",
        "address": "静安区共和新路2266号",
        "transport": "地铁1号线上海马戏城站",
        "fee": "收费",
        "description": "上海大型马戏表演场馆，有精彩的马戏和杂技表演。",
        "official_url": "",
        "highlights": ["马戏", "杂技", "表演"]
    },
    {
        "name": "上海儿童艺术剧场",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "演出场馆",
        "address": "黄浦区苗江路800号",
        "transport": "地铁4号线南浦大桥站",
        "fee": "收费",
        "description": "专为儿童设计的剧场，演出儿童剧、亲子剧等。",
        "official_url": "",
        "highlights": ["儿童剧", "亲子剧"]
    },
    {
        "name": "上海东方艺术中心",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "演出场馆",
        "address": "浦东新区丁香路425号",
        "transport": "地铁2号线上海科技馆站",
        "fee": "收费",
        "description": "上海大型艺术中心，有音乐厅、歌剧院、美术馆等。",
        "official_url": "",
        "highlights": ["音乐厅", "歌剧院", "艺术"]
    },
    {
        "name": "上海梅赛德斯奔驰文化中心",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "演出场馆",
        "address": "浦东新区世博大道1200号",
        "transport": "地铁8号线中华艺术宫站",
        "fee": "收费",
        "description": "大型演艺场馆，举办演唱会、体育赛事等活动。",
        "official_url": "",
        "highlights": ["演唱会", "体育赛事"]
    },
    {
        "name": "上海八万人体育场",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "体育中心",
        "address": "徐汇区漕溪北路1111号",
        "transport": "地铁1号线上海体育馆站",
        "fee": "收费",
        "description": "上海大型体育场，举办足球比赛和大型活动。",
        "official_url": "",
        "highlights": ["足球", "体育赛事"]
    },
    {
        "name": "上海体育馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "体育中心",
        "address": "徐汇区漕溪北路1111号",
        "transport": "地铁1号线上海体育馆站",
        "fee": "收费",
        "description": "大型室内体育馆，举办篮球比赛和演唱会。",
        "official_url": "",
        "highlights": ["篮球", "演唱会"]
    },
    {
        "name": "上海源深体育中心",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "体育中心",
        "address": "浦东新区源深路655号",
        "transport": "地铁6号线源深体育中心站",
        "fee": "收费",
        "description": "浦东新区大型体育中心，有体育馆、游泳馆等设施。",
        "official_url": "",
        "highlights": ["体育", "游泳", "场馆"]
    },
    {
        "name": "上海浦东游泳馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "体育中心",
        "address": "浦东新区浦东南路3669号",
        "transport": "地铁7号线云台路站",
        "fee": "收费",
        "description": "浦东新区大型游泳馆，有游泳培训和休闲设施。",
        "official_url": "",
        "highlights": ["游泳", "培训"]
    },
    {
        "name": "上海静安体育中心",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "静安区",
        "type": "体育中心",
        "address": "静安区汶水路116号",
        "transport": "地铁1号线汶水路站",
        "fee": "收费",
        "description": "静安区大型体育中心，有体育馆、游泳馆等设施。",
        "official_url": "",
        "highlights": ["体育", "游泳", "场馆"]
    },
    {
        "name": "上海长风公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "普陀区",
        "type": "公园",
        "address": "普陀区大渡河路189号",
        "transport": "地铁15号线长风公园站",
        "fee": "免费",
        "description": "大型城市公园，有银锄湖、铁臂山，还有长风海洋世界。",
        "official_url": "",
        "highlights": ["湖景", "海洋世界", "免费"]
    },
    {
        "name": "上海中山公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "长宁区",
        "type": "公园",
        "address": "长宁区长宁路780号",
        "transport": "地铁2/3/4号线中山公园站",
        "fee": "免费",
        "description": "上海著名的城市公园，有草坪、湖景、游乐场等。",
        "official_url": "",
        "highlights": ["草坪", "湖景", "游乐场", "免费"]
    },
    {
        "name": "上海人民公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "公园",
        "address": "黄浦区南京西路231号",
        "transport": "地铁1号线人民广场站",
        "fee": "免费",
        "description": "位于人民广场的公园，有草坪、湖景、相亲角等。",
        "official_url": "",
        "highlights": ["草坪", "湖景", "相亲角", "免费"]
    },
    {
        "name": "上海外滩",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "公园",
        "address": "黄浦区中山东一路",
        "transport": "地铁10号线南京东路站",
        "fee": "免费",
        "description": "上海标志性景点，有万国建筑博览群和黄浦江景。",
        "official_url": "",
        "highlights": ["万国建筑", "黄浦江", "夜景", "免费"]
    },
    {
        "name": "上海陆家嘴",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区陆家嘴",
        "transport": "地铁2号线陆家嘴站",
        "fee": "免费",
        "description": "上海金融中心，有东方明珠、上海中心、金茂大厦等建筑。",
        "official_url": "",
        "highlights": ["金融中心", "地标建筑", "免费"]
    },
    {
        "name": "上海南京东路步行街",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "文化中心",
        "address": "黄浦区南京东路",
        "transport": "地铁1/2/8号线人民广场站",
        "fee": "免费",
        "description": "上海著名的商业步行街，有购物、餐饮、娱乐等。",
        "official_url": "",
        "highlights": ["购物", "餐饮", "商业"]
    },
    {
        "name": "上海淮海中路",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "文化中心",
        "address": "黄浦区淮海中路",
        "transport": "地铁10号线陕西南路站",
        "fee": "免费",
        "description": "上海著名的商业街，有高端购物和特色建筑。",
        "official_url": "",
        "highlights": ["高端购物", "特色建筑"]
    },
    {
        "name": "上海徐家汇商圈",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "文化中心",
        "address": "徐汇区徐家汇",
        "transport": "地铁1/9/11号线徐家汇站",
        "fee": "免费",
        "description": "上海重要的商业中心，有多个商场和文化设施。",
        "official_url": "",
        "highlights": ["商业中心", "购物", "文化"]
    },
    {
        "name": "上海静安寺",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "静安区",
        "type": "文化中心",
        "address": "静安区静安寺",
        "transport": "地铁2/7号线静安寺站",
        "fee": "收费",
        "description": "上海著名的佛教寺庙，有古建筑和宗教活动。",
        "official_url": "",
        "highlights": ["佛教寺庙", "古建筑", "宗教"]
    },
    {
        "name": "上海城隍庙",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "文化中心",
        "address": "黄浦区方浜中路249号",
        "transport": "地铁10号线豫园站",
        "fee": "收费",
        "description": "上海著名的道教寺庙，有古建筑和传统商业街。",
        "official_url": "",
        "highlights": ["道教寺庙", "古建筑", "商业街"]
    },
    {
        "name": "上海豫园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "公园",
        "address": "黄浦区豫园路100号",
        "transport": "地铁10号线豫园站",
        "fee": "收费",
        "description": "上海著名的古典园林，有亭台楼阁和假山流水。",
        "official_url": "",
        "highlights": ["古典园林", "亭台楼阁", "假山"]
    },
    {
        "name": "上海古猗园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "嘉定区",
        "type": "公园",
        "address": "嘉定区南翔镇",
        "transport": "地铁11号线南翔站",
        "fee": "收费",
        "description": "上海著名的古典园林，以猗猗绿竹闻名。",
        "official_url": "",
        "highlights": ["古典园林", "竹子", "南翔"]
    },
    {
        "name": "上海大观园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "青浦区",
        "type": "公园",
        "address": "青浦区金商公路701号",
        "transport": "自驾",
        "fee": "收费",
        "description": "以红楼梦为主题的古典园林，有大观园景区和淀山湖。",
        "official_url": "",
        "highlights": ["红楼梦", "古典园林", "淀山湖"]
    },
    {
        "name": "上海朱家角古镇",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "青浦区",
        "type": "文化中心",
        "address": "青浦区朱家角镇",
        "transport": "地铁17号线朱家角站",
        "fee": "免费",
        "description": "上海著名的水乡古镇，有小桥流水和传统建筑。",
        "official_url": "",
        "highlights": ["水乡古镇", "小桥流水", "免费"]
    },
    {
        "name": "上海枫泾古镇",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "金山区",
        "type": "文化中心",
        "address": "金山区枫泾镇",
        "transport": "自驾",
        "fee": "收费",
        "description": "上海著名的水乡古镇，有传统建筑和特色美食。",
        "official_url": "",
        "highlights": ["水乡古镇", "传统建筑", "美食"]
    },
    {
        "name": "上海七宝古镇",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "闵行区",
        "type": "文化中心",
        "address": "闵行区七宝镇",
        "transport": "地铁9号线七宝站",
        "fee": "免费",
        "description": "上海著名的古镇，有传统建筑和特色小吃。",
        "official_url": "",
        "highlights": ["古镇", "传统建筑", "小吃", "免费"]
    },
    {
        "name": "上海田子坊",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "文化中心",
        "address": "黄浦区泰康路210弄",
        "transport": "地铁9号线打浦桥站",
        "fee": "免费",
        "description": "上海文艺创意街区，有画廊、工作室、特色小店等。",
        "official_url": "",
        "highlights": ["文艺创意", "画廊", "特色小店", "免费"]
    },
    {
        "name": "上海新天地",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "黄浦区",
        "type": "文化中心",
        "address": "黄浦区太仓路181弄",
        "transport": "地铁10号线新天地站",
        "fee": "免费",
        "description": "上海著名的休闲街区，有石库门建筑和现代商业。",
        "official_url": "",
        "highlights": ["石库门", "休闲", "商业", "免费"]
    },
    {
        "name": "杭州西湖",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西湖街道",
        "transport": "地铁1号线龙翔桥站",
        "fee": "免费",
        "description": "杭州标志性景点，西湖十景闻名天下，可游船、散步、参观周边景点。",
        "official_url": "",
        "highlights": ["西湖十景", "游船", "白堤苏堤", "免费"]
    },
    {
        "name": "杭州灵隐寺",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区灵隐路法云弄1号",
        "transport": "公交7路",
        "fee": "收费",
        "description": "杭州著名的佛教寺庙，有古建筑和自然风光。",
        "official_url": "",
        "highlights": ["佛教寺庙", "古建筑", "自然风光"]
    },
    {
        "name": "杭州雷峰塔",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区南山路15号",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "杭州著名的古塔，登上塔顶可俯瞰西湖全景。",
        "official_url": "",
        "highlights": ["古塔", "俯瞰西湖"]
    },
    {
        "name": "杭州岳庙",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区北山路80号",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "纪念民族英雄岳飞的庙宇，展示岳飞生平事迹。",
        "official_url": "",
        "highlights": ["岳飞", "民族英雄", "历史"]
    },
    {
        "name": "杭州六和塔",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区之江路16号",
        "transport": "公交308路",
        "fee": "收费",
        "description": "杭州著名的古塔，位于钱塘江畔，可登高望远。",
        "official_url": "",
        "highlights": ["古塔", "钱塘江", "登高"]
    },
    {
        "name": "杭州虎跑公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区虎跑路39号",
        "transport": "公交4路",
        "fee": "收费",
        "description": "以虎跑泉闻名的公园，有泉水、茶园、自然风光。",
        "official_url": "",
        "highlights": ["虎跑泉", "茶园", "自然风光"]
    },
    {
        "name": "杭州九溪烟树",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区九溪路",
        "transport": "公交308路",
        "fee": "免费",
        "description": "杭州著名的自然景区，有溪流、茶园、瀑布，适合徒步。",
        "official_url": "",
        "highlights": ["溪流", "茶园", "瀑布", "徒步", "免费"]
    },
    {
        "name": "杭州云栖竹径",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区梅灵南路8号",
        "transport": "公交324路",
        "fee": "收费",
        "description": "以竹林为特色的景区，有石板路、溪流、竹林，环境清幽。",
        "official_url": "",
        "highlights": ["竹林", "清幽", "自然风光"]
    },
    {
        "name": "杭州龙井村",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区龙井路",
        "transport": "公交27路",
        "fee": "免费",
        "description": "杭州著名的龙井茶产地，有茶园、农家、茶文化体验。",
        "official_url": "",
        "highlights": ["龙井茶", "茶园", "茶文化", "免费"]
    },
    {
        "name": "杭州满陇桂雨",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区满觉陇路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "以桂花闻名的景区，秋季桂花盛开时香气扑鼻。",
        "official_url": "",
        "highlights": ["桂花", "秋季", "免费"]
    },
    {
        "name": "杭州太子湾公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区南山路5-1号",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "杭州著名的赏花公园，春季樱花和郁金香盛开。",
        "official_url": "",
        "highlights": ["樱花", "郁金香", "赏花", "免费"]
    },
    {
        "name": "杭州花港观鱼",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区杨公堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，有牡丹园、红鱼池等景点。",
        "official_url": "",
        "highlights": ["红鱼池", "牡丹园", "西湖十景", "免费"]
    },
    {
        "name": "杭州苏堤",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区苏堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，苏轼修建的长堤，适合散步和观赏西湖美景。",
        "official_url": "",
        "highlights": ["苏堤春晓", "散步", "西湖美景", "免费"]
    },
    {
        "name": "杭州白堤",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区白堤",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，白居易修建的长堤，有断桥残雪等景点。",
        "official_url": "",
        "highlights": ["断桥残雪", "散步", "西湖美景", "免费"]
    },
    {
        "name": "杭州曲院风荷",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区北山路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，夏季荷花盛开，景色优美。",
        "official_url": "",
        "highlights": ["荷花", "夏季", "西湖十景", "免费"]
    },
    {
        "name": "杭州平湖秋月",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区白堤西端",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，秋季赏月的好去处。",
        "official_url": "",
        "highlights": ["赏月", "秋季", "西湖十景", "免费"]
    },
    {
        "name": "杭州柳浪闻莺",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区南山路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，有柳树和草坪，适合休闲散步。",
        "official_url": "",
        "highlights": ["柳树", "草坪", "西湖十景", "免费"]
    },
    {
        "name": "杭州南屏晚钟",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区南山路",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "西湖十景之一，以南屏山和净慈寺钟声闻名。",
        "official_url": "",
        "highlights": ["净慈寺", "钟声", "西湖十景"]
    },
    {
        "name": "杭州双峰插云",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区灵隐路",
        "transport": "公交7路",
        "fee": "免费",
        "description": "西湖十景之一，以南高峰和北高峰闻名。",
        "official_url": "",
        "highlights": ["南北高峰", "西湖十景", "免费"]
    },
    {
        "name": "杭州吴山天风",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "公园",
        "address": "上城区吴山路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "西湖十景之一，位于吴山，可登高远眺西湖。",
        "official_url": "",
        "highlights": ["吴山", "登高", "西湖十景", "免费"]
    },
    {
        "name": "杭州涌金公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "公园",
        "address": "上城区涌金路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "位于西湖边的公园，有湖景和休闲设施。",
        "official_url": "",
        "highlights": ["湖景", "休闲", "免费"]
    },
    {
        "name": "杭州钱王祠",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "博物馆",
        "address": "上城区钱王祠路",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "纪念吴越国王钱镠的祠堂，展示吴越历史文化。",
        "official_url": "",
        "highlights": ["吴越历史", "钱镠", "文化"]
    },
    {
        "name": "杭州鼓楼",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "文化中心",
        "address": "上城区中山南路200号",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "杭州古城的南门城楼，有鼓楼和历史展览。",
        "official_url": "",
        "highlights": ["古城楼", "历史展览", "免费"]
    },
    {
        "name": "杭州河坊街",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "文化中心",
        "address": "上城区河坊街",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "杭州著名的历史街区，有传统店铺、特色小吃和老字号。",
        "official_url": "",
        "highlights": ["历史街区", "特色小吃", "老字号", "免费"]
    },
    {
        "name": "杭州南宋御街",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "文化中心",
        "address": "上城区中山中路",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "南宋时期的皇家御街，有历史建筑和现代商业。",
        "official_url": "",
        "highlights": ["南宋历史", "历史建筑", "商业", "免费"]
    },
    {
        "name": "杭州湖滨银泰",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "文化中心",
        "address": "上城区延安路",
        "transport": "地铁1号线龙翔桥站",
        "fee": "免费",
        "description": "西湖边的大型购物中心，有购物、餐饮、娱乐等设施。",
        "official_url": "",
        "highlights": ["购物", "餐饮", "西湖边"]
    },
    {
        "name": "杭州武林广场",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区武林广场",
        "transport": "地铁1号线武林广场站",
        "fee": "免费",
        "description": "杭州的商业中心，有大型商场和文化设施。",
        "official_url": "",
        "highlights": ["商业中心", "购物", "文化"]
    },
    {
        "name": "杭州运河广场",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区金华路",
        "transport": "地铁5号线大运河站",
        "fee": "免费",
        "description": "位于京杭大运河畔的广场，有运河博物馆和文化设施。",
        "official_url": "",
        "highlights": ["大运河", "运河博物馆", "免费"]
    },
    {
        "name": "杭州小河直街",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区小河直街",
        "transport": "公交151路",
        "fee": "免费",
        "description": "京杭大运河畔的历史街区，有传统建筑和特色小店。",
        "official_url": "",
        "highlights": ["历史街区", "运河", "特色小店", "免费"]
    },
    {
        "name": "杭州桥西直街",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区桥西直街",
        "transport": "公交151路",
        "fee": "免费",
        "description": "京杭大运河畔的历史街区，有博物馆和文创店铺。",
        "official_url": "",
        "highlights": ["历史街区", "运河", "博物馆", "免费"]
    },
    {
        "name": "杭州拱宸桥",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "文化中心",
        "address": "拱墅区桥弄街",
        "transport": "公交151路",
        "fee": "免费",
        "description": "京杭大运河上的古桥，是杭州的标志性建筑之一。",
        "official_url": "",
        "highlights": ["古桥", "大运河", "地标", "免费"]
    },
    {
        "name": "杭州西溪湿地东区",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区天目山路518号",
        "transport": "地铁3号线西溪湿地南站",
        "fee": "收费",
        "description": "西溪国家湿地公园的东区，有湿地景观和文化景点。",
        "official_url": "",
        "highlights": ["湿地", "自然景观", "文化"]
    },
    {
        "name": "杭州西溪湿地西区",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区文二西路",
        "transport": "地铁3号线西溪湿地北站",
        "fee": "收费",
        "description": "西溪国家湿地公园的西区，有湿地景观和自然生态。",
        "official_url": "",
        "highlights": ["湿地", "自然生态", "景观"]
    },
    {
        "name": "杭州湘湖",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "公园",
        "address": "萧山区湘湖路",
        "transport": "地铁1号线湘湖站",
        "fee": "免费",
        "description": "杭州的姊妹湖，有湖景和历史文化景点，适合休闲游玩。",
        "official_url": "",
        "highlights": ["湖景", "历史文化", "休闲", "免费"]
    },
    {
        "name": "杭州极地海洋世界",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "科普馆",
        "address": "萧山区湘湖路777号",
        "transport": "地铁1号线湘湖站",
        "fee": "收费",
        "description": "大型海洋主题公园，有极地动物、海洋生物和表演。",
        "official_url": "",
        "highlights": ["极地动物", "海洋生物", "表演"]
    },
    {
        "name": "杭州跨湖桥遗址博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "博物馆",
        "address": "萧山区湘湖路978号",
        "transport": "地铁1号线湘湖站",
        "fee": "免费",
        "description": "展示跨湖桥遗址文物，包括8000年前的独木舟。",
        "official_url": "",
        "highlights": ["独木舟", "8000年历史", "文物", "免费"]
    },
    {
        "name": "杭州奥体中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "体育中心",
        "address": "滨江区奥体街",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "杭州2022年亚运会主会场，有体育场、体育馆等设施。",
        "official_url": "",
        "highlights": ["亚运会", "体育场", "地标"]
    },
    {
        "name": "杭州滨江公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "公园",
        "address": "滨江区闻涛路",
        "transport": "地铁6号线江汉路站",
        "fee": "免费",
        "description": "位于钱塘江畔的公园，有江景和绿道，适合骑行和散步。",
        "official_url": "",
        "highlights": ["江景", "绿道", "骑行", "免费"]
    },
    {
        "name": "杭州梦想小镇",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "文化中心",
        "address": "余杭区仓前街道",
        "transport": "地铁5号线良睦路站",
        "fee": "免费",
        "description": "杭州的创业创新小镇，有创业孵化和文化设施。",
        "official_url": "",
        "highlights": ["创业创新", "文化", "免费"]
    },
    {
        "name": "杭州未来科技城",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "文化中心",
        "address": "余杭区文一西路",
        "transport": "地铁5号线良睦路站",
        "fee": "免费",
        "description": "杭州的科技新城，有现代化建筑和科技企业。",
        "official_url": "",
        "highlights": ["科技", "现代化", "免费"]
    },
    {
        "name": "杭州临平新城",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "临平区",
        "type": "文化中心",
        "address": "临平区迎宾路",
        "transport": "地铁9号线临平站",
        "fee": "免费",
        "description": "杭州临平区的新城，有商业和文化设施。",
        "official_url": "",
        "highlights": ["商业", "文化", "免费"]
    },
    {
        "name": "杭州九堡大桥",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "文化中心",
        "address": "江干区九堡",
        "transport": "地铁1号线九堡站",
        "fee": "免费",
        "description": "横跨钱塘江的大桥，适合观赏江景。",
        "official_url": "",
        "highlights": ["大桥", "江景", "免费"]
    },
    {
        "name": "杭州钱江新城",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "文化中心",
        "address": "江干区富春路",
        "transport": "地铁4号线市民中心站",
        "fee": "免费",
        "description": "杭州的新城区，有现代化建筑和城市景观。",
        "official_url": "",
        "highlights": ["现代化", "城市景观", "免费"]
    },
    {
        "name": "杭州城市阳台",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "文化中心",
        "address": "江干区富春路",
        "transport": "地铁4号线市民中心站",
        "fee": "免费",
        "description": "位于钱塘江畔的观景平台，可观赏江景和城市天际线。",
        "official_url": "",
        "highlights": ["江景", "城市天际线", "观景", "免费"]
    },
    {
        "name": "杭州大剧院",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "演出场馆",
        "address": "江干区新业路39号",
        "transport": "地铁4号线市民中心站",
        "fee": "收费",
        "description": "杭州标志性剧院，举办歌剧、音乐剧、音乐会等演出。",
        "official_url": "",
        "highlights": ["歌剧", "音乐剧", "建筑设计"]
    },
    {
        "name": "杭州国际会议中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "会展中心",
        "address": "江干区富春路",
        "transport": "地铁4号线市民中心站",
        "fee": "收费",
        "description": "杭州大型会议中心，举办各类会议和展览。",
        "official_url": "",
        "highlights": ["会议", "展览"]
    },
    {
        "name": "杭州奥体博览城",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "会展中心",
        "address": "滨江区江南大道",
        "transport": "地铁6号线奥体中心站",
        "fee": "收费",
        "description": "集体育、会展、文化于一体的大型综合体。",
        "official_url": "",
        "highlights": ["体育", "会展", "文化"]
    },
    {
        "name": "杭州白马湖国际会展中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "会展中心",
        "address": "滨江区长江南路",
        "transport": "公交137路",
        "fee": "收费",
        "description": "举办各类展览和活动，包括动漫节等。",
        "official_url": "",
        "highlights": ["展览", "动漫节"]
    },
    {
        "name": "杭州之江文化中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "文化中心",
        "address": "西湖区江涵路300号",
        "transport": "地铁6号线枫桦西路站",
        "fee": "免费",
        "description": "集博物馆、图书馆、美术馆、非遗馆于一体的文化综合体。",
        "official_url": "",
        "highlights": ["文化综合体", "博物馆", "图书馆", "免费"]
    },
    {
        "name": "杭州文学馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区江涵路300号之江文化中心",
        "transport": "地铁6号线枫桦西路站",
        "fee": "免费",
        "description": "展示浙江文学历史和作品，有文学展览和活动。",
        "official_url": "",
        "highlights": ["文学", "展览", "免费"]
    }
]

with open('venue_info.json', 'r', encoding='utf-8') as f:
    venues = json.load(f)

existing_names = {v['name'] for v in venues}
added_count = 0

for venue in new_venues:
    if venue['name'] not in existing_names:
        venues.append(venue)
        print(f"添加: {venue['name']} ({venue['city']})")
        added_count += 1

with open('venue_info.json', 'w', encoding='utf-8') as f:
    json.dump(venues, f, ensure_ascii=False, indent=2)

print(f"\n共添加 {added_count} 个场馆")