import json

new_venues = [
    {
        "name": "中国科学技术馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "科技馆",
        "address": "朝阳区北辰东路5号",
        "transport": "地铁8号线奥林匹克公园站",
        "fee": "收费",
        "description": "中国唯一的国家级综合性科技馆，设有儿童科学乐园、华夏之光、探索与发现等五大主题展厅，以及球幕、巨幕等特效影院。",
        "official_url": "",
        "highlights": ["儿童科学乐园", "球幕影院", "互动体验", "科普教育"]
    },
    {
        "name": "北京天文馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科普馆",
        "address": "西城区西直门外大街138号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "中国第一座大型天文馆，A馆天象厅球幕电影超赞，B馆有太阳观测、陨石展览、互动体验。",
        "official_url": "",
        "highlights": ["天象厅", "球幕电影", "陨石展览", "宇宙探索"]
    },
    {
        "name": "国家自然博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "博物馆",
        "address": "东城区天桥南大街126号",
        "transport": "地铁8号线天桥站",
        "fee": "免费",
        "description": "国内自然类博物馆的天花板，拥有37.2万件珍稀标本，恐龙化石是招牌，还有古生物、动物、植物、人类进化等展陈。",
        "official_url": "",
        "highlights": ["恐龙化石", "古生物", "动物标本", "自然教育"]
    },
    {
        "name": "国家动物博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "博物馆",
        "address": "朝阳区北辰西路1号院5号",
        "transport": "地铁8号线奥林匹克公园站",
        "fee": "收费",
        "description": "中科院下属，动物标本种类数量国内顶尖，鸟类、昆虫、濒危动物展厅都很精彩。",
        "official_url": "",
        "highlights": ["动物标本", "鸟类展厅", "濒危动物", "科研科普"]
    },
    {
        "name": "中国消防博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科普馆",
        "address": "西城区广安门南街70号",
        "transport": "地铁7号线广安门内站",
        "fee": "免费",
        "description": "互动体验超强！可以学习消防知识，体验地震、地铁火灾疏散，还有模拟灭火。",
        "official_url": "",
        "highlights": ["消防知识", "互动体验", "模拟灭火", "安全教育"]
    },
    {
        "name": "北京汽车博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "博物馆",
        "address": "丰台区南四环西路126号",
        "transport": "地铁9号线科怡路站",
        "fee": "收费",
        "description": "汽车迷天堂！从老爷车到未来概念车，还有各种互动驾驶体验，被评为全国中小学生研学实践教育基地。",
        "official_url": "",
        "highlights": ["老爷车", "概念车", "模拟驾驶", "汽车文化"]
    },
    {
        "name": "北京动物园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "公园",
        "address": "西城区西直门外大街137号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "老牌经典动物园，看大熊猫、长颈鹿、大象等，海洋馆就在园内，有白鲸、鲨鱼、海豚表演。",
        "official_url": "",
        "highlights": ["大熊猫", "海洋馆", "动物表演", "亲子游玩"]
    },
    {
        "name": "北京海洋馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科普馆",
        "address": "西城区西直门外大街137号北京动物园内",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "北京动物园内的大型海洋馆，有雨林奇观、鲨鱼小镇、海底环游等展区，还有海豚、海狮表演。",
        "official_url": "",
        "highlights": ["海底隧道", "海豚表演", "海洋生物", "亲子科普"]
    },
    {
        "name": "北京欢乐谷",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区东四环小武基北路",
        "transport": "地铁7号线欢乐谷景区站",
        "fee": "收费",
        "description": "大型主题乐园，刺激项目与儿童区（甜品王国、爱琴港区域）兼备，夏天有夜场和水花派对等活动。",
        "official_url": "",
        "highlights": ["主题乐园", "儿童区", "夜场", "水花派对"]
    },
    {
        "name": "水立方嬉水乐园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区天辰东路11号国家游泳中心内",
        "transport": "地铁8号线奥体中心站",
        "fee": "收费",
        "description": "室内水上乐园！全年恒温，不怕晒不怕雨。有适合各年龄段的滑道、造浪池、漂流河、儿童戏水区。",
        "official_url": "",
        "highlights": ["室内水上乐园", "造浪池", "儿童戏水", "四季恒温"]
    },
    {
        "name": "欢乐水魔方水上乐园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "公园",
        "address": "丰台区小屯路11号",
        "transport": "地铁14号线郭庄子站",
        "fee": "收费",
        "description": "大型室外水上乐园，龙卷风、风暴谷、黑暗漩涡等刺激项目，也有梦幻漂流和儿童戏水池。",
        "official_url": "",
        "highlights": ["室外水乐园", "刺激滑道", "漂流", "亲子戏水"]
    },
    {
        "name": "朝阳公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区朝阳公园南路1号",
        "transport": "地铁14号线朝阳公园站",
        "fee": "免费",
        "description": "综合性公园，面积大，可划船、野餐、放风筝，北区有泡泡玛特城市乐园和索尼探梦科技馆。",
        "official_url": "",
        "highlights": ["划船", "野餐", "泡泡玛特乐园", "索尼探梦"]
    },
    {
        "name": "世界公园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "公园",
        "address": "丰台区花乡大葆台158号",
        "transport": "地铁房山线大葆台站",
        "fee": "收费",
        "description": "微缩景观看世界，对孩子认识世界地标有帮助，夏天有时有夜场或表演。",
        "official_url": "",
        "highlights": ["微缩景观", "世界地标", "夜场表演"]
    },
    {
        "name": "北京野生动物园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "大兴区",
        "type": "公园",
        "address": "大兴区榆垡镇万亩森林",
        "transport": "地铁4号线天宫院站换乘公交",
        "fee": "收费",
        "description": "互动性更强的野生动物园，可自驾或坐园区小火车进入猛兽区，步行区能喂羊驼、小鹿等温顺动物。",
        "official_url": "",
        "highlights": ["猛兽区", "自驾游览", "互动投喂", "萌宝幼儿园"]
    },
    {
        "name": "北京科学中心",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "科技馆",
        "address": "西城区北辰路9号院",
        "transport": "地铁8号线安华桥站",
        "fee": "免费",
        "description": "国家级科普圣地，有黑科技展馆、球幕影院，还有免费的超大儿童乐园，各种玩法都有。",
        "official_url": "",
        "highlights": ["儿童乐园", "球幕影院", "黑科技", "免费"]
    },
    {
        "name": "中国地质博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "博物馆",
        "address": "西城区西四羊肉胡同15号",
        "transport": "地铁4号线西四站",
        "fee": "收费",
        "description": "收藏地质标本55万余件，有巨型山东龙、中华龙鸟等恐龙系列化石，北京人等古人类化石。",
        "official_url": "",
        "highlights": ["恐龙化石", "古人类化石", "地质标本", "科普"]
    },
    {
        "name": "北京奥运博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "博物馆",
        "address": "朝阳区国家体育场南路1号",
        "transport": "地铁8号线奥体中心站",
        "fee": "免费",
        "description": "沉浸式感受奥运魅力，人少免费还免预约，可直接刷身份证进入，互动体验超级多。",
        "official_url": "",
        "highlights": ["奥运文化", "互动体验", "免费", "鸟巢周边"]
    },
    {
        "name": "中国航空博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "昌平区",
        "type": "博物馆",
        "address": "昌平区小汤山镇",
        "transport": "地铁5号线沙河站换乘公交",
        "fee": "免费",
        "description": "亚洲最大、世界前五的航空博物馆，馆内展出各类展品1400余项，可看到各种年代的战斗机、轰炸机等。",
        "official_url": "",
        "highlights": ["航空展品", "战斗机", "轰炸机", "航天梦想"]
    },
    {
        "name": "中国考古博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "博物馆",
        "address": "朝阳区国家体育场北路1号院1号楼",
        "transport": "地铁8号线奥林匹克公园站",
        "fee": "免费",
        "description": "国内第一家以考古命名的博物馆，可以参观精美的文物，摸一摸五千多年前的陶片，亲手敲一敲编钟。",
        "official_url": "",
        "highlights": ["考古文物", "陶片触摸", "编钟体验", "历史教育"]
    },
    {
        "name": "中国园林博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "丰台区",
        "type": "博物馆",
        "address": "丰台区射击场路15号",
        "transport": "地铁14号线园博园站",
        "fee": "免费",
        "description": "带娃打卡中国园林博物馆，一秒入江南，苏州畅园、岭南余荫山房、扬州片石山房为必逛的三大室内园林。",
        "official_url": "",
        "highlights": ["江南园林", "苏州畅园", "岭南园林", "古典韵味"]
    },
    {
        "name": "中国军事博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "博物馆",
        "address": "海淀区复兴路9号",
        "transport": "地铁1号线军事博物馆站",
        "fee": "免费",
        "description": "中国第一个综合类军事博物馆，飞机、坦克、大炮、导弹、火箭一应俱全，军事迷孩子的梦中情馆。",
        "official_url": "",
        "highlights": ["军事装备", "飞机坦克", "导弹火箭", "国防教育"]
    },
    {
        "name": "海淀公共安全馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "科普馆",
        "address": "海淀区新建宫门路2号",
        "transport": "地铁4号线西苑站",
        "fee": "免费",
        "description": "集消防、自然灾害、人体、交通等安全知识为一体，还有滑梯、模拟开车等娱乐项目。",
        "official_url": "",
        "highlights": ["安全知识", "模拟驾驶", "互动体验", "儿童安全"]
    },
    {
        "name": "乐高探索中心",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区朝阳北路101号长楹天街购物中心",
        "transport": "地铁6号线常营站",
        "fee": "收费",
        "description": "乐高迷的天堂，大型乐高游乐场，各种乐高主题的游乐设施和互动项目，能让孩子沉浸在积木世界里一整天。",
        "official_url": "",
        "highlights": ["乐高积木", "4D电影", "互动体验", "亲子游玩"]
    },
    {
        "name": "首都图书馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "图书馆",
        "address": "朝阳区东三环南路88号",
        "transport": "地铁10号线十里河站",
        "fee": "免费",
        "description": "北京市大型公共图书馆，有丰富的馆藏资源，定期举办阅读推广、讲座等活动。",
        "official_url": "",
        "highlights": ["阅读推广", "讲座活动", "儿童阅读区"]
    },
    {
        "name": "国家图书馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "海淀区",
        "type": "图书馆",
        "address": "海淀区中关村南大街33号",
        "transport": "地铁4号线国家图书馆站",
        "fee": "免费",
        "description": "中国国家图书馆，馆藏丰富，有专门的少年儿童馆，适合亲子阅读学习。",
        "official_url": "",
        "highlights": ["国家藏书", "少年儿童馆", "阅读学习"]
    },
    {
        "name": "中国妇女儿童博物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "东城区",
        "type": "博物馆",
        "address": "东城区北极阁路9号",
        "transport": "地铁5号线灯市口站",
        "fee": "免费",
        "description": "中国第一家以妇女儿童为主题的国家级博物馆，展示妇女儿童相关的历史文化和艺术。",
        "official_url": "",
        "highlights": ["妇女儿童", "历史文化", "亲子教育"]
    },
    {
        "name": "中国古动物馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "西城区",
        "type": "博物馆",
        "address": "西城区西直门外大街142号",
        "transport": "地铁4号线动物园站",
        "fee": "收费",
        "description": "展示古生物化石，有恐龙、猛犸象等古动物标本，适合对古生物感兴趣的孩子。",
        "official_url": "",
        "highlights": ["恐龙化石", "古动物", "古生物"]
    },
    {
        "name": "索尼探梦科技馆",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "科普馆",
        "address": "朝阳区朝阳公园南路1号",
        "transport": "地铁14号线朝阳公园站",
        "fee": "收费",
        "description": "以光与声音为主题的科技馆，互动有趣，适合儿童科学启蒙。",
        "official_url": "",
        "highlights": ["光与声音", "互动体验", "科学启蒙"]
    },
    {
        "name": "泡泡玛特城市乐园",
        "source": "北京本地宝",
        "city": "beijing",
        "district": "朝阳区",
        "type": "公园",
        "address": "朝阳区朝阳公园南路1号",
        "transport": "地铁14号线朝阳公园站",
        "fee": "收费",
        "description": "IP主题乐园，以泡泡玛特盲盒形象为主题，适合喜欢盲盒的小朋友。",
        "official_url": "",
        "highlights": ["泡泡玛特", "IP主题", "盲盒"]
    },
    {
        "name": "广东科学中心",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "科技馆",
        "address": "番禺区大学城科普路168号",
        "transport": "地铁4号线大学城北站",
        "fee": "收费",
        "description": "世界最大的科技馆/科学中心，室内遛娃宝藏地，有儿童天地、实验与发现馆以及太空主题展。",
        "official_url": "",
        "highlights": ["儿童天地", "太空主题", "互动体验", "科普教育"]
    },
    {
        "name": "广州青少年科技馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "科技馆",
        "address": "越秀区童心路西胜街42号",
        "transport": "地铁2号线越秀公园站",
        "fee": "免费",
        "description": "专为青少年设计的科技馆，有机器人、航模、编程等互动体验，定期举办科技讲座和比赛。",
        "official_url": "",
        "highlights": ["机器人", "编程", "科技讲座", "免费"]
    },
    {
        "name": "广州少年儿童图书馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "图书馆",
        "address": "越秀区中山四路42号",
        "transport": "地铁1号线农讲所站",
        "fee": "免费",
        "description": "专为少年儿童服务的公共图书馆，有丰富的儿童读物，定期举办绘本故事会、阅读推广等活动。",
        "official_url": "",
        "highlights": ["儿童阅读", "绘本故事", "阅读推广"]
    },
    {
        "name": "广州地铁博物馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "博物馆",
        "address": "海珠区新港东路万胜围地铁站A出口",
        "transport": "地铁8号线万胜围站",
        "fee": "免费",
        "description": "展示广州地铁发展历程，有各种地铁模型、模拟驾驶设备、互动游戏，孩子们可以体验模拟驾驶。",
        "official_url": "",
        "highlights": ["地铁模型", "模拟驾驶", "互动游戏", "科普"]
    },
    {
        "name": "广州市儿童公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "白云区",
        "type": "公园",
        "address": "白云区齐心路61号",
        "transport": "地铁2号线白云公园站",
        "fee": "免费",
        "description": "专为儿童设计的主题公园，有海盗船、旋转木马、淘气堡等设施，还有科普区和儿童剧场。",
        "official_url": "",
        "highlights": ["儿童游乐", "海盗船", "科普区", "免费"]
    },
    {
        "name": "广州动物园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "公园",
        "address": "越秀区先烈中路120号",
        "transport": "地铁5号线动物园站",
        "fee": "收费",
        "description": "华南地区最大的动物园，有憨态可掬的大熊猫、威风凛凛的华南虎，还有各种珍稀动物。",
        "official_url": "",
        "highlights": ["大熊猫", "华南虎", "珍稀动物", "亲子"]
    },
    {
        "name": "广州海洋馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "科普馆",
        "address": "越秀区先烈中路120号广州动物园内",
        "transport": "地铁5号线动物园站",
        "fee": "收费",
        "description": "广州动物园内的大型海洋馆，有360°海底隧道、珊瑚世界、水母幻境等，还有海洋生物表演。",
        "official_url": "",
        "highlights": ["海底隧道", "珊瑚世界", "水母", "表演"]
    },
    {
        "name": "正佳极地海洋世界",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "科普馆",
        "address": "天河区天河路228号正佳广场",
        "transport": "地铁3号线体育西路站",
        "fee": "收费",
        "description": "室内海洋馆，拥有白鲸、企鹅表演以及海底隧道观赏区，适合全年龄段家庭游玩。",
        "official_url": "",
        "highlights": ["白鲸", "企鹅", "海底隧道", "表演"]
    },
    {
        "name": "正佳雨林生态植物园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "公园",
        "address": "天河区天河路228号正佳广场7层",
        "transport": "地铁3号线体育西路站",
        "fee": "收费",
        "description": "模拟热带雨林生态环境，种植大量热带植物，还有鹦鹉、蜥蜴、水豚等小动物，可体验丛林天空步道。",
        "official_url": "",
        "highlights": ["热带雨林", "小动物", "天空步道", "生态"]
    },
    {
        "name": "正佳自然科学博物馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "博物馆",
        "address": "天河区天河路228号正佳广场6楼",
        "transport": "地铁3号线体育西路站",
        "fee": "收费",
        "description": "馆内有8个展区，大量化石、标本、模型及多媒体展示，恐龙化石展示区深受孩子们喜爱。",
        "official_url": "",
        "highlights": ["恐龙化石", "标本", "多媒体", "自然科学"]
    },
    {
        "name": "广州融创文旅城",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "花都区",
        "type": "公园",
        "address": "花都区凤凰北路78号",
        "transport": "地铁9号线花城路站",
        "fee": "收费",
        "description": "集乐园、雪世界、水世界、体育世界于一体，冰雪乐园让孩子在广州也能体验滑雪的乐趣。",
        "official_url": "",
        "highlights": ["雪世界", "水世界", "滑雪", "亲子"]
    },
    {
        "name": "永庆坊",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "荔湾区",
        "type": "文化中心",
        "address": "荔湾区恩宁路99号",
        "transport": "地铁1号线黄沙站",
        "fee": "免费",
        "description": "老广州的文化名片，可参观粤剧艺术博物馆，欣赏传统建筑，体验手工制作，感受老广州风情。",
        "official_url": "",
        "highlights": ["粤剧艺术", "传统建筑", "手工体验", "广府文化"]
    },
    {
        "name": "陈家祠",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "荔湾区",
        "type": "博物馆",
        "address": "荔湾区中山七路恩龙里34号",
        "transport": "地铁1号线陈家祠站",
        "fee": "收费",
        "description": "岭南建筑艺术的瑰宝，精美的木雕、石雕、砖雕让人叹为观止，可参加亲子导览活动。",
        "official_url": "",
        "highlights": ["岭南建筑", "木雕石雕", "砖雕", "传统文化"]
    },
    {
        "name": "岭南印象园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区大学城外环西路",
        "transport": "地铁4号线大学城南站",
        "fee": "收费",
        "description": "体验岭南传统文化的绝佳场所，有广彩、广绣、醒狮等传统手工艺展示和体验活动。",
        "official_url": "",
        "highlights": ["岭南文化", "广彩广绣", "醒狮", "手工艺"]
    },
    {
        "name": "海珠国家湿地公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "公园",
        "address": "海珠区新滘中路",
        "transport": "地铁3号线大塘站",
        "fee": "收费",
        "description": "可以进行观鸟活动和参加自然教育课程，春天时还会举办花展，适合亲近自然。",
        "official_url": "",
        "highlights": ["观鸟", "自然教育", "花展", "湿地"]
    },
    {
        "name": "华南植物园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "天河区",
        "type": "公园",
        "address": "天河区兴科路723号",
        "transport": "地铁6号线植物园站",
        "fee": "收费",
        "description": "让孩子认识各种奇花异草的绝佳场所，温室群景区、龙洞琪林都是拍照打卡点，还能参加植物科普活动。",
        "official_url": "",
        "highlights": ["温室群", "植物科普", "奇花异草", "拍照"]
    },
    {
        "name": "白云山",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "白云区",
        "type": "公园",
        "address": "白云区广园中路801号",
        "transport": "地铁2号线白云公园站",
        "fee": "收费",
        "description": "登高望远的好去处，可带孩子走轻松路线，沿途欣赏四季花海，山顶还能俯瞰广州全景。",
        "official_url": "",
        "highlights": ["云台花园", "摩星岭", "四季花海", "登高"]
    },
    {
        "name": "大夫山森林公园",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区禺山西路668号",
        "transport": "地铁3号线汉溪长隆站",
        "fee": "免费",
        "description": "广州绿肺之一，租辆单车骑行环湖，或者在草坪上野餐放风筝，园区还有儿童游乐区。",
        "official_url": "",
        "highlights": ["骑行", "野餐", "儿童游乐", "免费"]
    },
    {
        "name": "海鸥岛",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "番禺区",
        "type": "公园",
        "address": "番禺区石楼镇",
        "transport": "地铁4号线石碁站",
        "fee": "免费",
        "description": "珠江入海口湿地，骑行绿道、采摘农场、沙滩露营、红树林观鸟，日落时分骑行最美。",
        "official_url": "",
        "highlights": ["湿地", "骑行", "观鸟", "露营"]
    },
    {
        "name": "广州新儿童活动中心",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "白云区",
        "type": "青少年宫",
        "address": "白云区云城东路509号",
        "transport": "地铁2号线白云公园站",
        "fee": "免费",
        "description": "集科技、自然美学、广府文化科普于一体，有VR项目体验、互动游戏、科普展览等。",
        "official_url": "",
        "highlights": ["VR体验", "互动游戏", "广府文化", "免费"]
    },
    {
        "name": "广州开发区科技馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "黄埔区",
        "type": "科技馆",
        "address": "黄埔区萝岗街道萝平路与香雪七路交汇处",
        "transport": "地铁6号线香雪站",
        "fee": "免费",
        "description": "黄埔区科技馆，提供科技互动体验和科普教育活动。",
        "official_url": "",
        "highlights": ["科技互动", "科普教育", "免费"]
    },
    {
        "name": "广州艺术博物院",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "美术馆",
        "address": "越秀区麓湖路13号",
        "transport": "地铁5号线小北站",
        "fee": "免费",
        "description": "展示古今中外艺术作品，有岭南画派作品、历代书画等展览，适合艺术启蒙。",
        "official_url": "",
        "highlights": ["艺术展览", "岭南画派", "书画", "艺术启蒙"]
    },
    {
        "name": "南越王博物院",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "越秀区",
        "type": "博物馆",
        "address": "越秀区解放北路867号",
        "transport": "地铁2号线越秀公园站",
        "fee": "免费",
        "description": "展示南越王墓出土文物，包括金缕玉衣、丝缕玉衣等珍贵文物，了解南越国历史。",
        "official_url": "",
        "highlights": ["南越王墓", "金缕玉衣", "历史文物"]
    },
    {
        "name": "广州市文化馆新馆",
        "source": "广州本地宝",
        "city": "guangzhou",
        "district": "海珠区",
        "type": "文化中心",
        "address": "海珠区新滘中路288号",
        "transport": "地铁3号线大塘站",
        "fee": "免费",
        "description": "占地面积全国居首的文化馆，融合汉唐风格与岭南风情，含翰墨园、广绣园等多个主题园区。",
        "official_url": "",
        "highlights": ["岭南园林", "汉唐风格", "亲子文化", "拍照"]
    },
    {
        "name": "上海自然博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "静安区",
        "type": "博物馆",
        "address": "静安区北京西路510号",
        "transport": "地铁13号线自然博物馆站",
        "fee": "收费",
        "description": "亚洲最大自然博物馆之一，恐龙模型、非洲动物展区逼真，互动装置多，如化石挖掘体验。",
        "official_url": "",
        "highlights": ["恐龙化石", "非洲动物", "化石挖掘", "互动"]
    },
    {
        "name": "上海天文馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "科普馆",
        "address": "浦东新区南汇新城环湖北三路388号",
        "transport": "地铁16号线滴水湖站",
        "fee": "收费",
        "description": "世界最大的天文馆，有球幕影院、太阳系展区、宇宙探索等互动展项，适合天文爱好者。",
        "official_url": "",
        "highlights": ["球幕影院", "太阳系", "宇宙探索", "互动"]
    },
    {
        "name": "上海儿童博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "长宁区",
        "type": "博物馆",
        "address": "长宁区宋园路61号",
        "transport": "地铁10号线宋园路站",
        "fee": "免费",
        "description": "专为3-10岁儿童设计，有太空舱模拟、航海体验区，免费且人少。",
        "official_url": "",
        "highlights": ["太空舱", "航海体验", "免费", "儿童专属"]
    },
    {
        "name": "上海地铁博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "闵行区",
        "type": "博物馆",
        "address": "闵行区吴中路1799-7号",
        "transport": "地铁10号线龙溪路站",
        "fee": "免费",
        "description": "中国第一家展示城市轨道交通发展历程的专业展馆，有模拟驾驶、VR互动体验等项目。",
        "official_url": "",
        "highlights": ["地铁发展", "模拟驾驶", "VR体验", "免费"]
    },
    {
        "name": "上海海洋水族馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "科普馆",
        "address": "浦东新区陆家嘴环路1388号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "展示各种海洋生物，有海底隧道、鲨鱼馆、水母馆等，适合亲子海洋探索。",
        "official_url": "",
        "highlights": ["海底隧道", "鲨鱼", "水母", "海洋生物"]
    },
    {
        "name": "上海海昌海洋公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区银飞路166号",
        "transport": "地铁16号线临港大道站",
        "fee": "收费",
        "description": "一站式海洋亲子乐园，有虎鲸表演、北极熊展馆、海底隧道，还有儿童游乐设施。",
        "official_url": "",
        "highlights": ["虎鲸表演", "北极熊", "海底隧道", "亲子游乐"]
    },
    {
        "name": "上海野生动物园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区南六公路178号",
        "transport": "地铁16号线野生动物园站",
        "fee": "收费",
        "description": "国家级野生动物园，车行猛兽区+步行萌宠区双模式，能近距离投喂互动。",
        "official_url": "",
        "highlights": ["猛兽区", "步行区", "互动投喂", "大熊猫"]
    },
    {
        "name": "上海欢乐谷",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区林湖路888号",
        "transport": "地铁9号线佘山站",
        "fee": "收费",
        "description": "大型主题乐园，有刺激项目和儿童区，适合不同年龄段的孩子游玩。",
        "official_url": "",
        "highlights": ["主题乐园", "刺激项目", "儿童区", "亲子"]
    },
    {
        "name": "上海迪士尼乐园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区川沙新镇黄赵路310号",
        "transport": "地铁11号线迪士尼站",
        "fee": "收费",
        "description": "全球知名主题乐园，适合全年龄段儿童，有梦幻城堡、花车巡游和亲子项目。",
        "official_url": "",
        "highlights": ["梦幻城堡", "花车巡游", "亲子项目", "主题乐园"]
    },
    {
        "name": "乐高探索中心",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "普陀区",
        "type": "公园",
        "address": "普陀区大渡河路196号长风大悦城",
        "transport": "地铁15号线长风公园站",
        "fee": "收费",
        "description": "室内乐高主题乐园，有4D电影、迷你上海积木展，适合低龄儿童动手创作。",
        "official_url": "",
        "highlights": ["乐高积木", "4D电影", "迷你上海", "动手创作"]
    },
    {
        "name": "上海汽车博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "嘉定区",
        "type": "博物馆",
        "address": "嘉定区安亭博园路7565号",
        "transport": "地铁11号线安亭站",
        "fee": "收费",
        "description": "男孩最爱！古董车收藏丰富，可体验儿童驾驶项目。",
        "official_url": "",
        "highlights": ["古董车", "儿童驾驶", "汽车文化"]
    },
    {
        "name": "东方明珠塔",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区世纪大道1号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "上海标志性建筑，可登塔俯瞰上海全景，有悬空观光廊、历史陈列馆等。",
        "official_url": "",
        "highlights": ["登高观光", "悬空廊", "历史陈列", "地标"]
    },
    {
        "name": "上海中心大厦",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "文化中心",
        "address": "浦东新区陆家嘴环路1000号",
        "transport": "地铁2号线陆家嘴站",
        "fee": "收费",
        "description": "上海最高建筑，118层观光厅可俯瞰上海全貌，适合亲子登高体验。",
        "official_url": "",
        "highlights": ["最高建筑", "118层", "俯瞰上海", "观光"]
    },
    {
        "name": "徐家汇书院",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "图书馆",
        "address": "徐汇区漕溪北路158号",
        "transport": "地铁1/9/11号线徐家汇站",
        "fee": "免费",
        "description": "现代化图书馆，建筑设计精美，有丰富的阅读空间和展览活动。",
        "official_url": "",
        "highlights": ["阅读空间", "建筑设计", "展览", "免费"]
    },
    {
        "name": "世纪公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "浦东新区",
        "type": "公园",
        "address": "浦东新区锦绣路1001号",
        "transport": "地铁2号线世纪公园站",
        "fee": "免费",
        "description": "超大绿地公园，可搭帐篷、放风筝、踢球，园内有儿童乐园。",
        "official_url": "",
        "highlights": ["草坪", "儿童乐园", "野餐", "免费"]
    },
    {
        "name": "共青森林公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "杨浦区",
        "type": "公园",
        "address": "杨浦区军工路2000号",
        "transport": "地铁8号线翔殷路站",
        "fee": "免费",
        "description": "市区内超大森林绿地，可野餐、划船、骑亲子自行车，常有花卉展。",
        "official_url": "",
        "highlights": ["森林", "划船", "骑行", "花卉展"]
    },
    {
        "name": "辰山植物园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "松江区",
        "type": "公园",
        "address": "松江区辰花公路3888号",
        "transport": "地铁9号线洞泾站",
        "fee": "收费",
        "description": "超大温室花园、矿坑瀑布，儿童可奔跑玩耍，适合亲子自然探索。",
        "official_url": "",
        "highlights": ["温室花园", "矿坑瀑布", "自然探索", "亲子"]
    },
    {
        "name": "徐汇滨江滑板公园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "公园",
        "address": "徐汇区龙腾大道",
        "transport": "地铁7号线龙华中路站",
        "fee": "免费",
        "description": "滨江骑行道+专业滑板场地，可带娃骑车、玩滑板，欣赏黄浦江景。",
        "official_url": "",
        "highlights": ["滑板", "骑行", "黄浦江", "免费"]
    },
    {
        "name": "长风海洋世界",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "普陀区",
        "type": "科普馆",
        "address": "普陀区大渡河路451号",
        "transport": "地铁15号线长风公园站",
        "fee": "收费",
        "description": "长风公园内的海洋世界，有白鲸表演、海底隧道，适合亲子海洋探索。",
        "official_url": "",
        "highlights": ["白鲸表演", "海底隧道", "海洋生物"]
    },
    {
        "name": "上海植物园",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "公园",
        "address": "徐汇区龙吴路1111号",
        "transport": "地铁3号线石龙路站",
        "fee": "收费",
        "description": "上海市中心的植物园，有多个专类园，可认识各种植物，适合自然教育。",
        "official_url": "",
        "highlights": ["植物", "自然教育", "专类园"]
    },
    {
        "name": "上海昆虫博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "徐汇区",
        "type": "博物馆",
        "address": "徐汇区枫林路300号",
        "transport": "地铁7号线东安路站",
        "fee": "收费",
        "description": "展示各种昆虫标本，有蝴蝶、甲虫等，适合对昆虫感兴趣的孩子。",
        "official_url": "",
        "highlights": ["昆虫标本", "蝴蝶", "甲虫", "科普"]
    },
    {
        "name": "上海消防博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "长宁区",
        "type": "博物馆",
        "address": "长宁区中山西路229号",
        "transport": "地铁3/4号线延安西路站",
        "fee": "免费",
        "description": "展示上海消防历史，有消防车、消防装备等展品，还有互动体验区。",
        "official_url": "",
        "highlights": ["消防历史", "消防车", "互动体验", "免费"]
    },
    {
        "name": "上海科技馆分馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "静安区",
        "type": "科技馆",
        "address": "静安区北京西路510号",
        "transport": "地铁13号线自然博物馆站",
        "fee": "收费",
        "description": "上海科技馆分馆，以自然科学为主题，有丰富的互动展项和科普活动。",
        "official_url": "",
        "highlights": ["自然科学", "互动展项", "科普活动"]
    },
    {
        "name": "上海少年儿童图书馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "长宁区",
        "type": "图书馆",
        "address": "长宁区延安西路1538号",
        "transport": "地铁3/4号线延安西路站",
        "fee": "免费",
        "description": "专为少年儿童服务的公共图书馆，有丰富的儿童读物和阅读活动。",
        "official_url": "",
        "highlights": ["儿童阅读", "读物", "阅读活动", "免费"]
    },
    {
        "name": "世界技能博物馆",
        "source": "上海本地宝",
        "city": "shanghai",
        "district": "杨浦区",
        "type": "博物馆",
        "address": "杨浦区黄兴路221号",
        "transport": "地铁12号线隆昌路站",
        "fee": "免费",
        "description": "展示世界技能大赛相关内容，有各种技能互动体验，适合青少年职业启蒙。",
        "official_url": "",
        "highlights": ["技能体验", "职业启蒙", "互动", "免费"]
    },
    {
        "name": "浙江省博物馆（之江馆）",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区江涵路300号",
        "transport": "地铁6号线枫桦西路站",
        "fee": "免费",
        "description": "之江文化中心单体建筑面积最大的场馆，集收藏、保护、研究、展示于一体，有多种数字互动体验项目。",
        "official_url": "",
        "highlights": ["数字互动", "文物展览", "之江文化", "免费"]
    },
    {
        "name": "浙江省博物馆（孤山馆）",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区孤山路25号",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "位于西湖边的博物馆，展示浙江历史文化和艺术藏品，周边风景优美。",
        "official_url": "",
        "highlights": ["西湖边", "历史文化", "艺术藏品", "免费"]
    },
    {
        "name": "浙江自然博物院（杭州馆）",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "博物馆",
        "address": "拱墅区西湖文化广场6号",
        "transport": "地铁1号线西湖文化广场站",
        "fee": "免费",
        "description": "以自然生命人为主题，有恐龙骨架、生物标本等展陈，适合亲子自然探索。",
        "official_url": "",
        "highlights": ["恐龙骨架", "生物标本", "自然探索", "免费"]
    },
    {
        "name": "浙江省科技馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "科技馆",
        "address": "拱墅区西湖文化广场2号",
        "transport": "地铁1号线西湖文化广场站",
        "fee": "免费",
        "description": "一至三层为常设展厅，有宇宙遨游、气象万千、海底巡礼、前沿科技等展区，互动体验丰富。",
        "official_url": "",
        "highlights": ["宇宙遨游", "互动体验", "前沿科技", "免费"]
    },
    {
        "name": "浙江省地质博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区",
        "transport": "地铁",
        "fee": "免费",
        "description": "展陈面积约6300平方米，设有地质历史厅、矿产资源厅、地质环境厅等，适合地质科普。",
        "official_url": "",
        "highlights": ["地质历史", "矿产资源", "地质科普", "免费"]
    },
    {
        "name": "浙江省非物质文化遗产馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区江涵路300号之江文化中心",
        "transport": "地铁6号线枫桦西路站",
        "fee": "免费",
        "description": "中国首座大型区域综合性非物质文化遗产馆，展示浙江非遗文化，有互动体验。",
        "official_url": "",
        "highlights": ["非遗文化", "互动体验", "浙江文化", "免费"]
    },
    {
        "name": "浙江图书馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "图书馆",
        "address": "西湖区江涵路300号之江文化中心",
        "transport": "地铁6号线枫桦西路站",
        "fee": "免费",
        "description": "浙江省大型公共图书馆，有丰富的馆藏资源，适合亲子阅读学习。",
        "official_url": "",
        "highlights": ["阅读学习", "馆藏丰富", "免费"]
    },
    {
        "name": "中国杭州低碳科技馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "科技馆",
        "address": "滨江区江汉路1888号",
        "transport": "地铁6号线江汉路站",
        "fee": "免费",
        "description": "以低碳为主题的科技馆，有巨幕影院、儿童乐园、4D小火车、科普活动免费开放。",
        "official_url": "",
        "highlights": ["低碳主题", "巨幕影院", "儿童乐园", "免费"]
    },
    {
        "name": "杭州亚运会博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "博物馆",
        "address": "滨江区奥体中心体育场地下一层",
        "transport": "地铁6号线奥体中心站",
        "fee": "免费",
        "description": "展示杭州亚运会相关内容，有互动体验，可了解亚运历史和文化。",
        "official_url": "",
        "highlights": ["亚运会", "互动体验", "体育文化", "免费"]
    },
    {
        "name": "良渚博物院",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "博物馆",
        "address": "余杭区美丽洲路1号",
        "transport": "地铁2号线良渚站",
        "fee": "免费",
        "description": "集收藏、研究、展示良渚文化于一体的考古遗址博物馆，有玉琮等珍贵文物。",
        "official_url": "",
        "highlights": ["良渚文化", "玉琮", "考古", "免费"]
    },
    {
        "name": "中国丝绸博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区玉皇山路73-1号",
        "transport": "公交12路",
        "fee": "免费",
        "description": "世界上最大的丝绸博物馆，收藏丝绸之路沿线出土的丝绸文物，展示丝绸发展脉络。",
        "official_url": "",
        "highlights": ["丝绸文化", "丝绸之路", "文物", "免费"]
    },
    {
        "name": "中国水利博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "博物馆",
        "address": "萧山区水博大道1号",
        "transport": "自驾",
        "fee": "免费",
        "description": "展示中华民族五千年治水历程，重点展示新中国水利建设成就，夜景灯光漂亮。",
        "official_url": "",
        "highlights": ["水利历史", "治水成就", "夜景", "免费"]
    },
    {
        "name": "中国茶叶博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区龙井路88号",
        "transport": "公交27路",
        "fee": "免费",
        "description": "我国唯一以茶和茶文化为主题的国家级专题博物馆，分为龙井馆和双峰馆。",
        "official_url": "",
        "highlights": ["茶文化", "龙井", "茶叶", "免费"]
    },
    {
        "name": "中国湿地博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区天目山路402号",
        "transport": "公交194路",
        "fee": "免费",
        "description": "以湿地为主题的国家级博物馆，建筑如同隐藏在西溪的小山丘，展示湿地生态。",
        "official_url": "",
        "highlights": ["湿地生态", "西溪", "自然教育", "免费"]
    },
    {
        "name": "中国动漫博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "滨江区",
        "type": "博物馆",
        "address": "滨江区白马湖路375号",
        "transport": "公交137路",
        "fee": "免费",
        "description": "动漫专题博物馆，沿着动漫发展史，问候曾经陪伴过的荧屏伙伴，寻找一起度过的岁月。",
        "official_url": "",
        "highlights": ["动漫历史", "荧屏伙伴", "互动体验", "免费"]
    },
    {
        "name": "杭州博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "博物馆",
        "address": "上城区粮道山18号",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "反映杭州历史变迁的人文类综合性博物馆，馆内陈列丰富，有杭州出土文物精品陈列。",
        "official_url": "",
        "highlights": ["杭州历史", "出土文物", "人文", "免费"]
    },
    {
        "name": "良渚古城遗址公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "余杭区",
        "type": "公园",
        "address": "余杭区瓶窑镇凤都路",
        "transport": "地铁2号线良渚站",
        "fee": "收费",
        "description": "体验和感悟中华五千年文明，涵盖宫殿区、内城与外城，可乘坐观光车游览。",
        "official_url": "",
        "highlights": ["五千年文明", "考古遗址", "观光车", "文化"]
    },
    {
        "name": "杭州野生动物世界",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "富阳区",
        "type": "公园",
        "address": "富阳区受降镇杭富路九龙大道1号",
        "transport": "公交514路",
        "fee": "收费",
        "description": "大型野生动物世界，有各种珍稀动物，可自驾或步行游览，适合亲子游玩。",
        "official_url": "",
        "highlights": ["野生动物", "自驾游览", "亲子游玩"]
    },
    {
        "name": "杭州植物园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区桃源岭1号",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "位于西湖边的植物园，有多个专类园，四季花卉不断，适合自然教育和亲子散步。",
        "official_url": "",
        "highlights": ["植物", "自然教育", "西湖边", "四季花卉"]
    },
    {
        "name": "西溪国家湿地公园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区天目山路518号",
        "transport": "地铁3号线西溪湿地南站",
        "fee": "收费",
        "description": "国家5A级景区，以自然湿地为特色，可乘船游览，体验江南水乡风情。",
        "official_url": "",
        "highlights": ["湿地", "乘船", "江南水乡", "5A景区"]
    },
    {
        "name": "西湖风景名胜区",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "公园",
        "address": "西湖区西湖街道",
        "transport": "地铁1号线龙翔桥站",
        "fee": "免费",
        "description": "杭州标志性景区，西湖十景闻名天下，可游船、散步、参观周边景点。",
        "official_url": "",
        "highlights": ["西湖十景", "游船", "白堤苏堤", "免费"]
    },
    {
        "name": "杭州乐园",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "萧山区",
        "type": "公园",
        "address": "萧山区风情大道2555号",
        "transport": "地铁1号线湘湖站",
        "fee": "收费",
        "description": "大型主题乐园，有刺激项目和儿童区，适合亲子游玩。",
        "official_url": "",
        "highlights": ["主题乐园", "刺激项目", "儿童区", "亲子"]
    },
    {
        "name": "杭州少年儿童图书馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "图书馆",
        "address": "西湖区曙光路75号",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "专为少年儿童服务的公共图书馆，有丰富的儿童读物和阅读活动。",
        "official_url": "",
        "highlights": ["儿童阅读", "读物", "阅读活动", "免费"]
    },
    {
        "name": "杭州科技馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "科技馆",
        "address": "拱墅区西湖文化广场",
        "transport": "地铁1号线西湖文化广场站",
        "fee": "免费",
        "description": "杭州市级科技馆，有互动科技体验展，适合儿童科学启蒙。",
        "official_url": "",
        "highlights": ["互动体验", "科学启蒙", "免费"]
    },
    {
        "name": "杭州中国茶叶博物馆龙井馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区翁家山268号",
        "transport": "公交27路",
        "fee": "免费",
        "description": "中国茶叶博物馆龙井馆区，展示龙井茶文化和茶叶制作工艺。",
        "official_url": "",
        "highlights": ["龙井茶文化", "茶叶制作", "免费"]
    },
    {
        "name": "杭州西湖博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "上城区",
        "type": "博物馆",
        "address": "上城区南山路89号",
        "transport": "公交Y2路",
        "fee": "免费",
        "description": "展示西湖历史文化和自然风光，位于西湖边，风景优美。",
        "official_url": "",
        "highlights": ["西湖历史", "自然风光", "免费"]
    },
    {
        "name": "杭州京杭大运河博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "博物馆",
        "address": "拱墅区金华路88号",
        "transport": "地铁5号线大运河站",
        "fee": "免费",
        "description": "展示京杭大运河历史文化，有运河文物、历史资料等展陈。",
        "official_url": "",
        "highlights": ["运河文化", "历史文物", "免费"]
    },
    {
        "name": "杭州工艺美术博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "拱墅区",
        "type": "博物馆",
        "address": "拱墅区小河路334号",
        "transport": "公交151路",
        "fee": "免费",
        "description": "展示杭州传统工艺美术，有陶瓷、刺绣、木雕等展品，适合传统文化启蒙。",
        "official_url": "",
        "highlights": ["传统工艺", "陶瓷刺绣", "木雕", "免费"]
    },
    {
        "name": "杭州中国湿地博物馆",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "博物馆",
        "address": "西湖区天目山路402号",
        "transport": "公交194路",
        "fee": "免费",
        "description": "国家级湿地博物馆，展示湿地生态系统和生物多样性，有互动体验。",
        "official_url": "",
        "highlights": ["湿地生态", "生物多样性", "互动体验", "免费"]
    },
    {
        "name": "杭州青少年活动中心",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "西湖区",
        "type": "青少年宫",
        "address": "西湖区昭庆寺里街22号",
        "transport": "公交Y2路",
        "fee": "收费",
        "description": "杭州市青少年校外活动场所，有各种兴趣培训和活动。",
        "official_url": "",
        "highlights": ["兴趣培训", "青少年活动"]
    },
    {
        "name": "杭州嘟嘟城",
        "source": "杭州本地宝",
        "city": "hangzhou",
        "district": "江干区",
        "type": "公园",
        "address": "江干区新业路331-399号",
        "transport": "地铁4号线市民中心站",
        "fee": "收费",
        "description": "儿童职业体验乐园，孩子们可以体验各种职业角色，如医生、警察、消防员等。",
        "official_url": "",
        "highlights": ["职业体验", "角色扮演", "儿童乐园"]
    }
]

with open('venue_info.json', 'r', encoding='utf-8') as f:
    venues = json.load(f)

existing_names = {v['name'] for v in venues}
added_count = 0

for venue in new_venues:
    if venue['name'] not in existing_names:
        venues.append(venue)
        print(f"添加: {venue['name']} ({venue['city']})")
        added_count += 1

with open('venue_info.json', 'w', encoding='utf-8') as f:
    json.dump(venues, f, ensure_ascii=False, indent=2)

print(f"\n共添加 {added_count} 个场馆")