import json
import os

DATA_FILE = 'output/exhibitions.json'
OUTPUT_FILE = 'output/exhibitions.json'

new_activities = [
    # ========== 北京补充活动（第四批）==========
    {"name": "米小圈之银河系侦探社儿童剧", "venue": "五棵松爱乐汇艺术空间", "city": "beijing", "district": "海淀区", "start_date": "2026-07-17", "end_date": "2026-07-19", "fee": "收费", "description": "国民IP改编舞台剧，米小圈携手姜小牙铁头组建银河系侦探社，奇幻冒险与逻辑推理融合。", "source": "北京广播电视台", "highlights": ["儿童剧", "米小圈", "侦探"], "type": "演出"},
    {"name": "长安在哪里唐诗儿童剧", "venue": "五棵松爱乐汇艺术空间", "city": "beijing", "district": "海淀区", "start_date": "2026-07-31", "end_date": "2026-08-09", "fee": "收费", "description": "唐诗遇上侦探推理，带领孩子穿越千年溯源盛唐长安，沉浸式感受大唐诗意文脉。", "source": "北京广播电视台", "highlights": ["唐诗", "儿童剧", "国风"], "type": "演出"},
    {"name": "大秦兵马俑甲骨文学校儿童剧", "venue": "五棵松爱乐汇艺术空间", "city": "beijing", "district": "海淀区", "start_date": "2026-08-12", "end_date": "2026-08-23", "fee": "收费", "description": "聚焦秦汉历史文明，奇幻舞台剧情解锁兵马俑甲骨文背后的历史奥秘。", "source": "北京广播电视台", "highlights": ["兵马俑", "甲骨文", "历史"], "type": "演出"},
    {"name": "看得见的敦煌壁画儿童剧", "venue": "五棵松爱乐汇艺术空间", "city": "beijing", "district": "海淀区", "start_date": "2026-09-04", "end_date": "2026-09-13", "fee": "收费", "description": "丝路敦煌主题儿童剧，在壁画中感受敦煌之美与丝绸之路文化。", "source": "北京广播电视台", "highlights": ["敦煌", "壁画", "丝路"], "type": "演出"},
    {"name": "中秋诗词主题儿童剧", "venue": "五棵松爱乐汇艺术空间", "city": "beijing", "district": "海淀区", "start_date": "2026-09-24", "end_date": "2026-09-27", "fee": "收费", "description": "中秋档期诗词主题儿童剧，在传统节日中感受诗词之美。", "source": "北京广播电视台", "highlights": ["中秋", "诗词", "儿童剧"], "type": "演出"},
    {"name": "故宫以东古建艺术季", "venue": "天坛神乐署", "city": "beijing", "district": "东城区", "start_date": "2026-07-14", "end_date": "2026-10-31", "fee": "收费", "description": "古建艺术季从7月持续至10月，涵盖古建汇演、艺术共创、文化市集四大板块。", "source": "东城区文旅局", "highlights": ["古建", "艺术季", "天坛"], "type": "演出"},
    {"name": "城垣听笛秋日城墙音乐会", "venue": "明城墙遗址公园", "city": "beijing", "district": "东城区", "start_date": "2026-09-01", "end_date": "2026-09-30", "fee": "收费", "description": "中央音乐学院笛子乐团在六百年青砖灰瓦间奏响民族管乐华章。", "source": "东城区文旅局", "highlights": ["音乐会", "笛子", "明城墙"], "type": "演出"},
    {"name": "变奏北京创意融合音乐会", "venue": "北京鼓楼", "city": "beijing", "district": "东城区", "start_date": "2026-10-01", "end_date": "2026-10-31", "fee": "收费", "description": "在北京鼓楼上演创意融合音乐会，观众可在不同空间连续观演。", "source": "东城区文旅局", "highlights": ["音乐会", "鼓楼", "融合"], "type": "演出"},
    {"name": "东四胡同彩画技艺体验", "venue": "东四胡同博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-14", "end_date": "2026-10-31", "fee": "收费", "description": "面向亲子家庭开展古建彩画修复技艺体验，学习传统彩画工艺。", "source": "东城区文旅局", "highlights": ["彩画", "非遗", "胡同"], "type": "亲子活动"},
    {"name": "老舍故居剧本交流活动", "venue": "老舍故居纪念馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-14", "end_date": "2026-10-31", "fee": "免费", "description": "依托丹柿小院开展剧本交流与片段表演，推进名人故居活态利用。", "source": "东城区文旅局", "highlights": ["老舍", "戏剧", "故居"], "type": "讲座"},
    {"name": "服贸会机器人消费体验展", "venue": "首钢园", "city": "beijing", "district": "石景山区", "start_date": "2026-09-09", "end_date": "2026-09-15", "fee": "收费", "description": "大都乐活机器人消费场景互动体验区，零售汽车服装四足仿生体育竞技六大板块。", "source": "北京发布", "highlights": ["机器人", "服贸会", "科技"], "type": "展览"},
    {"name": "京核无界杂技剧", "venue": "首钢园大跳台南广场", "city": "beijing", "district": "石景山区", "start_date": "2026-09-09", "end_date": "2026-09-15", "fee": "收费", "description": "中国杂技团力作，硬核工业质感与先锋艺术美学的跨界碰撞。", "source": "北京发布", "highlights": ["杂技", "首钢", "工业风"], "type": "演出"},
    {"name": "中国国际糖果季", "venue": "首钢园", "city": "beijing", "district": "石景山区", "start_date": "2026-09-09", "end_date": "2026-10-07", "fee": "收费", "description": "第二届中国国际糖果季，音乐演绎数字艺术潮流消费运动休闲创意市集多元业态。", "source": "北京发布", "highlights": ["糖果季", "市集", "潮流"], "type": "演出"},
    {"name": "澄古匠心黄花梨家具展", "venue": "中国国家博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-09-01", "end_date": "2026-12-31", "fee": "免费", "description": "九十余件黄花梨紫檀家具作品，型艺材韵俱全，传统家具艺术大展。", "source": "国家博物馆", "highlights": ["黄花梨", "家具", "国博"], "type": "展览"},
    {"name": "百年巨匠专题展", "venue": "中国国家博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "聚焦二十世纪教科文卫体各领域100位大师巨匠，350余件展品六大篇章。", "source": "国家博物馆", "highlights": ["百年巨匠", "大师", "国博"], "type": "展览"},
    {"name": "安溪历史文化展", "venue": "中国国家博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-09-01", "end_date": "2026-12-31", "fee": "免费", "description": "160余件套展品，展示安溪历史文化艺术创造和民俗风情。", "source": "国家博物馆", "highlights": ["安溪", "茶文化", "民俗"], "type": "展览"},
    {"name": "古人类进化史展", "venue": "中国国家博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "220余件组文物，全面讲述人类从猿到人的百万年活动历程。", "source": "国家博物馆", "highlights": ["古人类", "进化", "考古"], "type": "展览"},
    {"name": "德化白瓷展", "venue": "中国国家博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "400余件组德化白瓷展品，何朝宗款观音像等传世精品齐聚。", "source": "国家博物馆", "highlights": ["德化白瓷", "瓷器", "国博"], "type": "展览"},
    {"name": "全国十大考古新发现展", "venue": "中国国家博物馆", "city": "beijing", "district": "东城区", "start_date": "2026-09-01", "end_date": "2026-12-31", "fee": "免费", "description": "43家文博考古机构近400件最新考古出土文物，四大板块讲述中华文明发展历程。", "source": "国家博物馆", "highlights": ["考古", "十大发现", "国博"], "type": "展览"},
    {"name": "故宫茶文化特展", "venue": "故宫博物院午门展厅", "city": "beijing", "district": "东城区", "start_date": "2026-09-01", "end_date": "2026-12-31", "fee": "免费", "description": "茶从中国走向世界，茶起源于中国盛行于世界，以茶为媒交融互鉴。", "source": "故宫博物院", "highlights": ["茶", "故宫", "文化"], "type": "展览"},
    {"name": "故宫丝路联合考古展", "venue": "故宫博物院神武门展厅", "city": "beijing", "district": "东城区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "唐三彩小海神角杯陶胡人俑座灯与中亚金牌费尔干纳石雕汇聚一堂。", "source": "故宫博物院", "highlights": ["丝路", "考古", "故宫"], "type": "展览"},
    {"name": "文艺复兴大师作品展广州站", "venue": "广东省博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-10-18", "fee": "收费", "description": "格拉斯哥博物馆藏意大利艺术真迹，提香贝利尼丁托列托等大师作品齐聚。", "source": "广州日报", "highlights": ["文艺复兴", "意大利", "大师"], "type": "展览"},
    {"name": "青州微笑佛造像艺术展", "venue": "广州艺术博物院", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "华南首次大规模高规格古青州造像展，62件造像精品22件一级文物。", "source": "广州日报", "highlights": ["青州", "佛造像", "艺术"], "type": "展览"},
    {"name": "一念敦煌大展", "venue": "广州艺术博物院", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "收费", "description": "敦煌主题大展，口碑不俗人气火热，近距离感受敦煌艺术魅力。", "source": "广州日报", "highlights": ["敦煌", "艺术", "大展"], "type": "展览"},
    {"name": "热贡唐卡数字艺术特展", "venue": "广州人民艺术中心", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "收费", "description": "青海热贡唐卡艺术经典之作与数字化创新成果，全套数字化观展服务。", "source": "广州日报", "highlights": ["唐卡", "热贡", "数字艺术"], "type": "展览"},
    {"name": "花漾穆夏新艺术美学展", "venue": "广州人民艺术中心", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "收费", "description": "穆夏10余幅近130年历史石版画原作，百年美学跨界漫步。", "source": "广州日报", "highlights": ["穆夏", "新艺术", "石版画"], "type": "展览"},
    {"name": "中非文化艺术展", "venue": "广州海事博物馆", "city": "guangzhou", "district": "黄埔区", "start_date": "2026-07-01", "end_date": "2026-10-31", "fee": "免费", "description": "中部非洲面具雕像兵器仪式用品百余件精品，全方位展现中非文化艺术。", "source": "广州日报", "highlights": ["非洲", "艺术", "面具"], "type": "展览"},
    {"name": "星火启程农讲所文物展", "venue": "农讲所纪念馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "118件藏品72件珍贵文物，农民运动讲习所历史展，一级文物齐聚。", "source": "广州日报", "highlights": ["农讲所", "红色", "文物"], "type": "展览"},
    {"name": "救民水火北伐纪念展", "venue": "黄埔军校旧址纪念馆", "city": "guangzhou", "district": "黄埔区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "纪念国民革命军一百周年展，北伐画史376幅珍贵照片。", "source": "广州日报", "highlights": ["黄埔军校", "北伐", "历史"], "type": "展览"},
    {"name": "萧华长征记忆展", "venue": "广州起义纪念馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "开国上将红色诗人萧华革命风范与长征记忆，长征组歌深度解读。", "source": "广州日报", "highlights": ["萧华", "长征", "红色"], "type": "展览"},
    {"name": "星火百年革命美术展", "venue": "广州艺术博物院", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "52件套革命历史题材美术精品，赖少其黄新波等知名艺术家经典力作。", "source": "广州日报", "highlights": ["革命美术", "艺术", "历史"], "type": "展览"},
    {"name": "虫篆微观奇境昆虫艺术展", "venue": "广东省博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-17", "end_date": "2026-10-18", "fee": "免费", "description": "昆虫为纽带融合科普教育艺术创作互动体验，昆虫科普艺术游园会配套活动。", "source": "广州日报", "highlights": ["昆虫", "科普", "艺术"], "type": "展览"},
    {"name": "韶关星空露营追流星雨", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-08-12", "end_date": "2026-08-14", "fee": "收费", "description": "追英仙座流星雨研学营，博物馆星空夜宿，真化石清修师十大研学课程。", "source": "广州日报", "highlights": ["流星雨", "露营", "研学"], "type": "亲子活动"},
    {"name": "博物馆星空夜宿", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "在博物馆与恐龙化石同眠，独特的夜宿体验，含讲解与科普活动。", "source": "广州日报", "highlights": ["夜宿", "博物馆", "恐龙"], "type": "亲子活动"},
    {"name": "真化石清修师研学", "venue": "正佳自然科学博物馆", "city": "guangzhou", "district": "天河区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "学习古生物化石修复技术，亲手清理修复真实化石标本。", "source": "广州日报", "highlights": ["化石", "修复", "研学"], "type": "亲子活动"},
    {"name": "白江湖森林公园溯溪", "venue": "白江湖森林公园", "city": "guangzhou", "district": "增城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "广州溯溪第一谷，原生态溪谷风光，戏水纳凉摸鱼嬉闹亲子友好。", "source": "广州日报", "highlights": ["溯溪", "森林", "亲子"], "type": "亲子活动"},
    {"name": "流溪河三桠塘幽谷溯溪", "venue": "流溪河国家森林公园", "city": "guangzhou", "district": "从化区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "溪水终年不竭串起浅滩叠水清潭，负氧离子浓度15000个每立方厘米。", "source": "广州日报", "highlights": ["溯溪", "流溪河", "森林"], "type": "亲子活动"},
    {"name": "石门国家森林公园亲水游", "venue": "石门国家森林公园", "city": "guangzhou", "district": "从化区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "桃花源相思古榕两大亲水秘境，海拔800米高山天池碧波泛舟。", "source": "广州日报", "highlights": ["亲水", "天池", "森林"], "type": "亲子活动"},
    {"name": "白水寨瀑布嬉水", "venue": "白水寨风景名胜区", "city": "guangzhou", "district": "增城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "落差428.5米天然瀑布，奇趣水谷生态嬉水乐园，亲子复合型乐园。", "source": "广州日报", "highlights": ["瀑布", "嬉水", "亲子"], "type": "亲子活动"},
    {"name": "广州戏水季森系溯溪", "venue": "广州各大森林公园", "city": "guangzhou", "district": "增城区", "start_date": "2026-07-12", "end_date": "2026-08-31", "fee": "免费", "description": "2026广州戏水季盛大开幕，四大主题戏水板块同步开放，森系溯溪花漾嬉水酷玩逐浪城央沁凉。", "source": "广州日报", "highlights": ["戏水季", "溯溪", "亲子"], "type": "亲子活动"},
    {"name": "市儿童公园戏水乐园", "venue": "广州市儿童公园", "city": "guangzhou", "district": "白云区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "三大玩水片区全面开启，龙舟戏水乐园海洋童趣戏水区旱喷广场，市区遛娃好去处。", "source": "广州日报", "highlights": ["儿童公园", "戏水", "免费"], "type": "亲子活动"},
    {"name": "白云山明珠楼亲水游", "venue": "白云山风景名胜区", "city": "guangzhou", "district": "白云区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "明珠楼景区浅滩休闲戏水，麓湖景区水上运动嘉年华龙舟皮划艇桨板全龄段趣味。", "source": "广州日报", "highlights": ["白云山", "亲水", "运动"], "type": "亲子活动"},
    {"name": "星罗纪大森林溯溪漂流", "venue": "广州星罗纪大森林景区", "city": "guangzhou", "district": "增城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "腾龙高空漂流连环弯道，龙溪谷天然山泉溯溪踩水打水仗捞小鱼。", "source": "广州日报", "highlights": ["漂流", "溯溪", "森林"], "type": "亲子活动"},
    {"name": "森林海旅游度假区狂欢", "venue": "森林海旅游度假区", "city": "guangzhou", "district": "增城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "泼水狂欢派对水上飞人表演与夜间烟花秀，从白天畅玩至夜晚。", "source": "广州日报", "highlights": ["森林海", "泼水", "烟花"], "type": "演出"},
    {"name": "金山水上运动嘉年华", "venue": "广州麓湖公园", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "龙舟体验皮划艇水上自行车桨板运动，全龄段趣味玩法悉数上线。", "source": "广州日报", "highlights": ["水上运动", "龙舟", "皮划艇"], "type": "亲子活动"},
    {"name": "大丰门峡谷漂流探险", "venue": "增城区大丰水峡谷乐园", "city": "guangzhou", "district": "增城区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "收费", "description": "峡谷漂流瀑布溪降飞拉达攀岩五色湖游船等探险玩法。", "source": "广州日报", "highlights": ["漂流", "峡谷", "探险"], "type": "亲子活动"},
    {"name": "长隆水上乐园暑期狂欢", "venue": "长隆水上乐园", "city": "guangzhou", "district": "番禺区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "70余项水上设施，造浪池大喇叭漂流河，夏季玩水首选之地。", "source": "广州本地宝", "highlights": ["长隆", "水上乐园", "暑期"], "type": "亲子活动"},
    {"name": "梦想号大洋钻探讲座", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-16", "end_date": "2026-07-16", "fee": "免费", "description": "深海钻探中心首席科学家孙珍讲座，介绍大洋钻探计划与梦想号钻探船。", "source": "科普广州", "highlights": ["大洋钻探", "科学家", "讲座"], "type": "讲座"},
    {"name": "近视防控科普专场", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-14", "end_date": "2026-07-17", "fee": "免费", "description": "科普宣讲加互动摊位，离焦读写台近视防控智能穿戴眼镜，免费视力检测。", "source": "科普广州", "highlights": ["近视防控", "眼健康", "科普"], "type": "讲座"},
    {"name": "金山地质博物馆科普展", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-14", "end_date": "2026-07-14", "fee": "免费", "description": "30余件珍稀标本恐龙蛋贵州龙三叶虫澄江动物群化石陨石矿物，贵州龙拓印实操。", "source": "科普广州", "highlights": ["地质", "化石", "拓印"], "type": "展览"},
    {"name": "地理科普定向闯关", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-15", "end_date": "2026-07-15", "fee": "免费", "description": "地理科普讲堂地学派定向闯关快闪科技游园，VR地理无人机模拟趣味竞答。", "source": "科普广州", "highlights": ["地理", "VR", "闯关"], "type": "亲子活动"},
    {"name": "智慧体育互动体验", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-16", "end_date": "2026-07-16", "fee": "免费", "description": "智慧体育一体机互动体验，实时记录运动数据，动作姿态矫正体能提升方案。", "source": "科普广州", "highlights": ["智慧体育", "AI", "运动"], "type": "亲子活动"},
    {"name": "口腔健康科普专场", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-17", "end_date": "2026-07-17", "fee": "免费", "description": "科普宣讲加互动摊位形式，普及儿童护牙知识。", "source": "科普广州", "highlights": ["口腔健康", "护牙", "科普"], "type": "讲座"},
    {"name": "花卉科普植物义诊", "venue": "广州青少年科技馆", "city": "guangzhou", "district": "越秀区", "start_date": "2026-07-17", "end_date": "2026-07-17", "fee": "免费", "description": "红掌等多样绿植展示，居家养护干货分享，植物义诊解答绿植养护难题。", "source": "科普广州", "highlights": ["花卉", "植物", "义诊"], "type": "讲座"},
    {"name": "上海儿童剧奥特传奇", "venue": "九棵树未来艺术中心", "city": "shanghai", "district": "奉贤区", "start_date": "2026-08-08", "end_date": "2026-08-08", "fee": "收费", "description": "圆谷正版授权奥特曼系列舞台剧奥特传奇第3部外星生物来袭。", "source": "奉贤文旅", "highlights": ["奥特曼", "儿童剧", "正版"], "type": "演出"},
    {"name": "屁屁侦探儿童剧", "venue": "九棵树未来艺术中心", "city": "shanghai", "district": "奉贤区", "start_date": "2026-08-16", "end_date": "2026-08-16", "fee": "收费", "description": "东映原版动漫舞台剧屁屁侦探之怪盗U对怪盗U。", "source": "奉贤文旅", "highlights": ["屁屁侦探", "动漫", "儿童剧"], "type": "演出"},
    {"name": "唐诗迷境寻诗历险记", "venue": "九棵树未来艺术中心", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-26", "end_date": "2026-07-26", "fee": "收费", "description": "奇幻探险亲子舞台剧唐诗迷境寻诗历险记。", "source": "奉贤文旅", "highlights": ["唐诗", "探险", "儿童剧"], "type": "演出"},
    {"name": "布鲁布鲁冰原历险记", "venue": "九棵树未来艺术中心", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-12", "end_date": "2026-07-12", "fee": "收费", "description": "沉浸式木偶剧布鲁布鲁之冰原历险记。", "source": "奉贤文旅", "highlights": ["木偶剧", "冰原", "沉浸式"], "type": "演出"},
    {"name": "魔艺总动员魔术秀", "venue": "九棵树未来艺术中心", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-26", "end_date": "2026-07-26", "fee": "收费", "description": "魔艺总动员魔都双星魔术秀，亲子魔术互动表演。", "source": "奉贤文旅", "highlights": ["魔术", "亲子", "互动"], "type": "演出"},
    {"name": "绿野仙踪3D多媒体音乐剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-07-15", "end_date": "2026-08-31", "fee": "收费", "description": "3D多媒体儿童音乐剧绿野仙踪，经典童话全新演绎。", "source": "保利城市剧院", "highlights": ["绿野仙踪", "3D", "音乐剧"], "type": "演出"},
    {"name": "爱丽丝梦游仙境音乐剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-07-15", "end_date": "2026-08-31", "fee": "收费", "description": "加拿大多媒体亲子音乐剧爱丽丝梦游仙境中文版。", "source": "保利城市剧院", "highlights": ["爱丽丝", "音乐剧", "多媒体"], "type": "演出"},
    {"name": "布鲁伊的大宝藏舞台剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-07-15", "end_date": "2026-08-31", "fee": "收费", "description": "英国BBC正版授权亲子互动舞台剧布鲁伊的大宝藏。", "source": "保利城市剧院", "highlights": ["布鲁伊", "BBC", "舞台剧"], "type": "演出"},
    {"name": "红舞鞋法语原版音乐剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-08-21", "end_date": "2026-08-23", "fee": "收费", "description": "法语原版音乐剧红舞鞋首次来华，长三角仅此一站，法国金牌团队打造。", "source": "保利城市剧院", "highlights": ["音乐剧", "法语原版", "红舞鞋"], "type": "演出"},
    {"name": "天鹅湖芭蕾舞剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-12-01", "end_date": "2026-12-31", "fee": "收费", "description": "经典芭蕾舞剧天鹅湖，芭蕾皇冠上最璀璨的钻石。", "source": "保利城市剧院", "highlights": ["天鹅湖", "芭蕾", "经典"], "type": "演出"},
    {"name": "胡桃夹子芭蕾舞剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-12-01", "end_date": "2026-12-31", "fee": "收费", "description": "经典芭蕾舞剧胡桃夹子，圣诞季必看经典。", "source": "保利城市剧院", "highlights": ["胡桃夹子", "芭蕾", "圣诞"], "type": "演出"},
    {"name": "吉赛尔芭蕾舞剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-12-01", "end_date": "2026-12-31", "fee": "收费", "description": "芭蕾舞剧吉赛尔，芭蕾水准的黄金标尺，浪漫芭蕾代表作。", "source": "保利城市剧院", "highlights": ["吉赛尔", "芭蕾", "浪漫"], "type": "演出"},
    {"name": "玉蜻蜓越剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-09-24", "end_date": "2026-09-25", "fee": "收费", "description": "越剧诞生120周年，王君安领衔主演越剧传统老戏玉蜻蜓。", "source": "保利城市剧院", "highlights": ["越剧", "王君安", "传统"], "type": "演出"},
    {"name": "何文秀越剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-09-25", "end_date": "2026-09-25", "fee": "收费", "description": "尹派经典剧目何文秀，越剧名家王君安主演。", "source": "保利城市剧院", "highlights": ["越剧", "尹派", "经典"], "type": "演出"},
    {"name": "彩虹的尽头舞台剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-11-15", "end_date": "2026-11-15", "fee": "收费", "description": "上海话剧艺术中心制作舞台剧彩虹的尽头，朱迪嘉兰的人生故事。", "source": "保利城市剧院", "highlights": ["话剧", "朱迪嘉兰", "艺术"], "type": "演出"},
    {"name": "谋杀派对悬疑话剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-12-01", "end_date": "2026-12-31", "fee": "收费", "description": "阿加莎克里斯蒂悬疑话剧谋杀派对，侦探小说女王作品。", "source": "保利城市剧院", "highlights": ["悬疑", "阿加莎", "话剧"], "type": "演出"},
    {"name": "骆驼祥子话剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-10-01", "end_date": "2026-10-31", "fee": "收费", "description": "老舍经典话剧骆驼祥子，讲述北平底层众生相。", "source": "保利城市剧院", "highlights": ["老舍", "话剧", "经典"], "type": "演出"},
    {"name": "朱自清舞剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-09-12", "end_date": "2026-09-12", "fee": "收费", "description": "舞剧朱自清，致敬一代知识分子的精神与风骨。", "source": "保利城市剧院", "highlights": ["舞剧", "朱自清", "红色"], "type": "演出"},
    {"name": "天山雪杂技剧", "venue": "保利上海城市剧院", "city": "shanghai", "district": "闵行区", "start_date": "2026-09-01", "end_date": "2026-09-30", "fee": "收费", "description": "杂技剧天山雪，70多年沪疆情谊，20多个高难度杂技节目。", "source": "保利城市剧院", "highlights": ["杂技", "新疆", "沪疆"], "type": "演出"},
    {"name": "CHINA白白瓷艺术展", "venue": "上海世界技能博物馆", "city": "shanghai", "district": "杨浦区", "start_date": "2026-07-16", "end_date": "2026-10-31", "fee": "收费", "description": "数十位中国工艺美术大师100余件白瓷艺术瑰宝，德化白瓷最高水平。", "source": "七月看展指南", "highlights": ["白瓷", "德化", "工艺"], "type": "展览"},
    {"name": "贾科梅蒂艺术大展", "venue": "上海民生现代美术馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-17", "end_date": "2026-12-06", "fee": "收费", "description": "212件重量级藏品，完整覆盖20世纪传奇艺术家贾科梅蒂创作全周期。", "source": "七月看展指南", "highlights": ["贾科梅蒂", "雕塑", "现代艺术"], "type": "展览"},
    {"name": "玻璃应力威尼斯狂欢展", "venue": "上海久事美术馆", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-18", "end_date": "2026-10-18", "fee": "收费", "description": "全球近20个国家约50位艺术家参展，玻璃材料的抵抗合作与联结。", "source": "七月看展指南", "highlights": ["玻璃", "威尼斯", "艺术"], "type": "展览"},
    {"name": "陈世英他界之器展", "venue": "龙美术馆西岸馆", "city": "shanghai", "district": "徐汇区", "start_date": "2026-07-18", "end_date": "2026-10-25", "fee": "收费", "description": "三件巨型钛金属雕塑为核心，梳理陈世英钛金属雕塑创作脉络。", "source": "七月看展指南", "highlights": ["陈世英", "钛金属", "雕塑"], "type": "展览"},
    {"name": "长安画派与海派绘画展", "venue": "上海美术馆中华艺术宫", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-16", "end_date": "2026-09-16", "fee": "免费", "description": "赵望云石鲁何海霞方济众刘海粟吴湖帆等名家70余件经典力作。", "source": "七月看展指南", "highlights": ["长安画派", "海派", "国画"], "type": "展览"},
    {"name": "康雍乾时期文物特展", "venue": "闵行博物馆", "city": "shanghai", "district": "闵行区", "start_date": "2026-07-01", "end_date": "2026-10-25", "fee": "免费", "description": "110余件套珍贵文物，青花斗彩鸡缸杯明黄色缎绣金龙龙袍太上皇帝之宝玺。", "source": "七月看展指南", "highlights": ["康雍乾", "文物", "龙袍"], "type": "展览"},
    {"name": "吴钧陶手稿文献展", "venue": "上海图书馆东馆", "city": "shanghai", "district": "浦东新区", "start_date": "2026-07-01", "end_date": "2026-09-30", "fee": "免费", "description": "百岁翻译家诗人吴钧陶先生珍贵一手文献，完整呈现坎坷却坚韧的人生轨迹。", "source": "七月看展指南", "highlights": ["吴钧陶", "翻译", "手稿"], "type": "展览"},
    {"name": "佘山度假区盛夏狂欢季", "venue": "上海佘山国家旅游度假区", "city": "shanghai", "district": "松江区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "趣佘山GO狂欢，七大主题板块二十余项特色活动，青年潮玩亲子游乐自然研学。", "source": "上海文旅局", "highlights": ["佘山", "狂欢", "亲子"], "type": "亲子活动"},
    {"name": "庄行伏羊美食嘉年华", "venue": "花米庄行景区", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-09-10", "fee": "收费", "description": "上海庄行伏羊美食嘉年华，全羊宴市集草地Live光影秀水岸集市。", "source": "上海文旅局", "highlights": ["伏羊节", "美食", "非遗"], "type": "演出"},
    {"name": "大宁公园荷花游园会", "venue": "大宁公园", "city": "shanghai", "district": "静安区", "start_date": "2026-07-18", "end_date": "2026-08-02", "fee": "免费", "description": "花开夏时荷夜未央主题游园会，全程免票，每周末设夜游专场。", "source": "上海文旅局", "highlights": ["荷花", "游园会", "夜游"], "type": "亲子活动"},
    {"name": "放鹤谷千灯会", "venue": "放鹤谷鲜花农场", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-30", "fee": "收费", "description": "国家级非遗四川自贡灯会，50亩花田升级为梦幻灯海，白天赏花夜晚观灯。", "source": "上海文旅局", "highlights": ["灯会", "自贡", "非遗"], "type": "演出"},
    {"name": "诗韵上海逐景寻诗打卡", "venue": "上海全域", "city": "shanghai", "district": "黄浦区", "start_date": "2026-07-08", "end_date": "2026-08-31", "fee": "免费", "description": "依托旅游节全域文旅地标植入诗词文化元素，边走边打卡集章，品读上海古韵。", "source": "上海旅游节", "highlights": ["诗词", "打卡", "集章"], "type": "亲子活动"},
    {"name": "海滨新天地恐龙展", "venue": "海滨新天地", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "大型恐龙主题展，逼真恐龙模型，互动体验项目，亲子科普好去处。", "source": "奉贤文旅", "highlights": ["恐龙", "亲子", "科普"], "type": "展览"},
    {"name": "碧海金沙水上乐园", "venue": "碧海金沙", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "上海唯一的碧海金沙人造沙滩，水上乐园沙滩运动，夏日亲子戏水好去处。", "source": "奉贤文旅", "highlights": ["沙滩", "水上乐园", "碧海金沙"], "type": "亲子活动"},
    {"name": "泡泡公园蚂蚁乐园", "venue": "上海之鱼泡泡公园", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "网红秋千3米高双滑道滑梯等大型无动力游乐设施，亲子撒欢好去处。", "source": "奉贤文旅", "highlights": ["泡泡公园", "无动力", "免费"], "type": "亲子活动"},
    {"name": "年丰公园水上运动", "venue": "上海之鱼年丰公园", "city": "shanghai", "district": "奉贤区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "皮划艇桨板卡丁船等水上项目，专业教练指导，泛舟湖上碧波穿行。", "source": "奉贤文旅", "highlights": ["皮划艇", "水上运动", "上海之鱼"], "type": "亲子活动"},
    {"name": "寻城记吴越童行研学", "venue": "杭州各文旅点位", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "4条亲子研学专线，吴越文化主题，邀少年探野听涛问城观澜。", "source": "杭州文广旅游局", "highlights": ["吴越", "研学", "亲子"], "type": "亲子活动"},
    {"name": "科技研学阿里机器人小镇", "venue": "阿里巴巴全球总部", "city": "hangzhou", "district": "余杭区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "10条精品科技研学线路，阿里总部机器人小镇梦想小镇，人工智能数字经济航空航天。", "source": "杭州文广旅游局", "highlights": ["科技", "研学", "阿里"], "type": "亲子活动"},
    {"name": "宋韵非遗上城坊巷研学", "venue": "上城区历史街区", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "宋韵非遗上城坊巷研学之旅，体验宋韵文化与非遗技艺。", "source": "杭州文广旅游局", "highlights": ["宋韵", "非遗", "研学"], "type": "亲子活动"},
    {"name": "运河百艺薪火传承研学", "venue": "拱墅区运河", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "运河百艺薪火传承非遗研学之旅，运河文化与非遗匠心。", "source": "杭州文广旅游局", "highlights": ["运河", "非遗", "研学"], "type": "亲子活动"},
    {"name": "循迹世界遗产西湖研学", "venue": "西湖风景名胜区", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "循迹世界遗产传承文脉匠心研学之旅，西湖文化与非遗匠心。", "source": "杭州文广旅游局", "highlights": ["西湖", "世界遗产", "研学"], "type": "亲子活动"},
    {"name": "小书虫漫游记暑期阅读", "venue": "杭州图书馆少儿分馆", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "联动全市400余家杭州书房，开展小书虫漫游记暑期阅读活动。", "source": "杭州文广旅游局", "highlights": ["阅读", "图书馆", "暑期"], "type": "讲座"},
    {"name": "杭图有约主题读书会", "venue": "杭州图书馆", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "杭州图书馆定期举办杭图有约主题读书会。", "source": "杭州文广旅游局", "highlights": ["读书会", "图书馆", "免费"], "type": "讲座"},
    {"name": "阅西湖图书馆之夜", "venue": "晓风书屋阅见西湖", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "晓风书屋阅见西湖定期举办阅读经典的意义阅西湖图书馆之夜读书分享会。", "source": "杭州文广旅游局", "highlights": ["读书", "西湖", "夜读"], "type": "讲座"},
    {"name": "第34届全国书博会", "venue": "杭州国际博览中心", "city": "hangzhou", "district": "萧山区", "start_date": "2026-07-24", "end_date": "2026-07-27", "fee": "免费", "description": "八大展厅九大专题展览十一项重点活动，发放300万元惠民购书券。", "source": "杭州文广旅游局", "highlights": ["书博会", "图书", "文化"], "type": "展览"},
    {"name": "宋词之都文脉走读", "venue": "杭州全城", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "免费", "description": "三秋桂子十里荷花柳永等8条文脉走读线路，杭州宋词之都文化体验。", "source": "杭州文广旅游局", "highlights": ["宋词", "走读", "文化"], "type": "亲子活动"},
    {"name": "南湖奇妙夜平行世界主场", "venue": "临平平行世界", "city": "hangzhou", "district": "临平区", "start_date": "2026-08-01", "end_date": "2026-08-31", "fee": "免费", "description": "8月奇妙夜主场，集聚夜游科技吴越文博国潮市集剧本游等业态。", "source": "杭州文广旅游局", "highlights": ["奇妙夜", "平行世界", "夜游"], "type": "演出"},
    {"name": "吴越奇妙夜吴越里主场", "venue": "吴越里", "city": "hangzhou", "district": "临安区", "start_date": "2026-10-01", "end_date": "2026-10-08", "fee": "免费", "description": "10月奇妙夜主场，国庆期间吴越文化主题夜游。", "source": "杭州文广旅游局", "highlights": ["奇妙夜", "吴越", "国庆"], "type": "演出"},
    {"name": "西湖夜跑荧光跑道", "venue": "西湖绿道", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "夜游新十品之夜跑，西湖青山湖白马湖荧光跑道等多条网红绿道。", "source": "杭州文广旅游局", "highlights": ["夜跑", "荧光", "绿道"], "type": "亲子活动"},
    {"name": "千岛湖萤火虫夜赏", "venue": "千岛湖", "city": "hangzhou", "district": "淳安县", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "夜赏千岛湖萤火虫，光影自然景观，浪漫夏日亲子体验。", "source": "杭州文广旅游局", "highlights": ["萤火虫", "千岛湖", "夜赏"], "type": "亲子活动"},
    {"name": "钱塘江夜游船", "venue": "钱塘江游船", "city": "hangzhou", "district": "滨江区", "start_date": "2026-07-01", "end_date": "2026-12-31", "fee": "收费", "description": "夜游钱塘江，欣赏两岸灯光秀与城市夜景。", "source": "杭州文广旅游局", "highlights": ["游船", "钱塘江", "灯光秀"], "type": "亲子活动"},
    {"name": "垂云通天河西游幻梦", "venue": "垂云通天河", "city": "hangzhou", "district": "桐庐县", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "溶洞西游幻梦暗河演艺，NPC互动龟仙人太上老君猪八戒牛魔王全员在线。", "source": "杭州文广旅游局", "highlights": ["溶洞", "西游记", "NPC"], "type": "演出"},
    {"name": "孔庙府学荷香市集", "venue": "杭州孔庙", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "巨型仿真荷叶排布，天然清凉取景秘境，宋风古风写真好去处。", "source": "杭州文广旅游局", "highlights": ["孔庙", "荷花", "市集"], "type": "亲子活动"},
    {"name": "吴山夜游吴山夜话", "venue": "吴山景区", "city": "hangzhou", "district": "上城区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "吴山夜话沉浸式夜游，南宋文化主题，体验临安城繁华夜景。", "source": "杭州文广旅游局", "highlights": ["吴山", "夜游", "南宋"], "type": "演出"},
    {"name": "小河直街夜游", "venue": "小河直街历史街区", "city": "hangzhou", "district": "拱墅区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "运河边的历史街区，夜游体验老杭州运河文化与夜市烟火气。", "source": "杭州文广旅游局", "highlights": ["小河直街", "运河", "夜市"], "type": "亲子活动"},
    {"name": "梦想小镇科技研学", "venue": "梦想小镇", "city": "hangzhou", "district": "余杭区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "免费", "description": "互联网创业小镇，科技研学参观，了解创新创业文化。", "source": "杭州文广旅游局", "highlights": ["梦想小镇", "科技", "研学"], "type": "亲子活动"},
    {"name": "机器人小镇科技探索", "venue": "机器人小镇", "city": "hangzhou", "district": "萧山区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "近距离观摩机器人全地形实战测试，与工程师对话，动手拼装机械狗。", "source": "杭州文广旅游局", "highlights": ["机器人", "科技", "研学"], "type": "亲子活动"},
    {"name": "天目山自然科考营", "venue": "天目山", "city": "hangzhou", "district": "临安区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "天目山国家级自然保护区，植物昆虫鸟类多样性科学考察夏令营。", "source": "杭州本地宝", "highlights": ["天目山", "自然", "科考"], "type": "亲子活动"},
    {"name": "莫干山自然探索营", "venue": "莫干山", "city": "hangzhou", "district": "临平区", "start_date": "2026-07-01", "end_date": "2026-08-31", "fee": "收费", "description": "莫干山自然探索夏令营，竹林徒步户外生存攀岩皮划艇多元体验。", "source": "杭州本地宝", "highlights": ["莫干山", "自然", "户外"], "type": "亲子活动"},
    {"name": "山的迁徙黄靖杰个展", "venue": "浙江美术馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-01", "end_date": "2026-07-31", "fee": "免费", "description": "几何图形重构新式山水，当代艺术语境中展现东方的浪漫与诗意。", "source": "七月看展指南", "highlights": ["黄靖杰", "当代艺术", "山水"], "type": "展览"},
    {"name": "羽民岛2影子的背面", "venue": "东信和创园", "city": "hangzhou", "district": "西湖区", "start_date": "2026-07-04", "end_date": "2026-07-26", "fee": "免费", "description": "陶艺与铸造玻璃作品，光影虚实的静谧对话。", "source": "七月看展指南", "highlights": ["陶艺", "玻璃", "艺术"], "type": "展览"},
    {"name": "蒙太奇从辩证法到动力学", "venue": "中国美术学院美术馆", "city": "hangzhou", "district": "西湖区", "start_date": "2026-04-10", "end_date": "2026-09-01", "fee": "免费", "description": "静态文献与动态影像交错，展现蒙太奇的魅力。", "source": "七月看展指南", "highlights": ["蒙太奇", "影像", "国美"], "type": "展览"},
    {"name": "豪劲与醇和书法展", "venue": "杭州市临平博物馆", "city": "hangzhou", "district": "临平区", "start_date": "2026-05-16", "end_date": "2026-08-23", "fee": "免费", "description": "书法艺术专题展，豪劲与醇和两种风格的书法美学对比。", "source": "七月看展指南", "highlights": ["书法", "临平", "展览"], "type": "展览"},
]

if __name__ == '__main__':
    if not os.path.exists(DATA_FILE):
        print(f"文件 {DATA_FILE} 不存在！")
        exit(1)
    
    with open(DATA_FILE, 'r', encoding='utf-8') as f:
        exhibitions = json.load(f)
    
    existing_names = {e['name'] for e in exhibitions}
    added_count = 0
    
    for activity in new_activities:
        if activity['name'] not in existing_names:
            exhibitions.append(activity)
            print(f"添加: {activity['name']} ({activity['city']})")
            added_count += 1
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(exhibitions, f, ensure_ascii=False, indent=2)
    
    print(f"\n共添加 {added_count} 个活动")
    
    city_counts = {}
    for e in exhibitions:
        city_counts[e['city']] = city_counts.get(e['city'], 0) + 1
    print(f"\n各城市活动数量:")
    for city, count in sorted(city_counts.items()):
        print(f"  {city}: {count}")
